### PR TITLE
CI: GHC 9.2.7 Support

### PR DESCRIPTION
**Pull request by andys8**
Draft for now to check with CI what needs to be changed.

Solves #3511

### CODE REVIEW

**Comment by andys8** [comment]
Looks like GHC 9.2.7 can't be installed with [chocolatey on Windows](https://community.chocolatey.org/packages/ghc#versionhistory), but that's also the case for 9.2.6 :thinking: 

image

**Comment by andys8** [comment]
* CI had exceptions for `9.2.5`. Not sure if this was due to issues with `9.2.5` or `9.2` in general.
* Nix failing due to cachix. Related or flaky?
* Can't be installed on Windows? Expected or does another place need to be updated?

**Comment by michaelpj** [comment]
> Looks like GHC 9.2.7 can't be installed with [chocolatey on Windows](https://community.chocolatey.org/packages/ghc#versionhistory), but that's also the case for 9.2.6

Right, but we never got to 9.2.6 in our CI, we were on 9.2.5. Looks like we're blocked on https://github.com/haskell/actions/issues/190

> CI had exceptions for 9.2.5. Not sure if this was due to issues with 9.2.5 or 9.2 in general.

Almost always major-version related so updating them is right.

> Nix failing due to cachix. Related or flaky?

It's flaky, that's why it's not required.

So overall I think this PR looks right, we just need the setup action to support it.

**Comment by andys8** [comment]
Cool, maybe the change we're waiting for isn't far away. 
https://github.com/Mistuke/GhcChoco/commit/bcbf15ac06f3a57c6d57bcdb0afd7cc8fbc9c699

**Comment by michaelpj** [comment]
Hmm, I don't understand how github action updates work. They released a minor version that supports the new GHCs, so shouldn't this now work?

**Comment by andys8** [comment]
I don't quite understand how HLS CI works and which of the jobs are known to be flaky 😅

The latest run seems to have failed for 9.0.2 which should be unrelated to the changes in this PR. Still not sure if my changes are complete and correct, though.

https://wire.softgarden.io/job/25936684/Senior-Haskell-Developer-m-f-d-?jobDbPVId=65019903&l=en

**Comment by fendor** [comment]
Haskell setup actions are broken for windows https://github.com/haskell/actions/issues/202#issuecomment-1465822109

**Review by Anton-Latukha — APPROVED** [review]

**Comment by July541** [comment]
Just a kindly reminder, do you still have the plan to continue?

**Comment by andys8** [comment]
Resolved the merge conflicts

**Comment by fendor** [comment]
@andys8 Yep, will do!

**Comment by fendor** [comment]
As @July541 correctly identified, there are indeed three test-cases that were incorrectly marked as broken because the distribution issue for GHC 9.2.7 has been fixed.
I removed the special casing, since our CI doesn't support more than one GHC 9.2 version and adding extra CPP seemed like a bad idea.

**Comment by fendor** [comment]
@andys8 thank you for the PR, sorry it took us so long to get it finally merged!

**Comment by andys8** [comment]
No need to apologize. Thanks for your work.

**Pull request merged**
