### PR TITLE
re-enable haddock

### PR DESCRIPTION
**Pull request by kokobd**
Currently, we disable `-haddock` option in `cabal.project` because `ghc-lib` 9.2 doesn't build on GHC 8.10.
For now, we can remove the dependency on `ghc-lib` in `hls-hlint-plugin`, using `ghc-lib-parser` instead. (actually `hlint` itself doesn't depend on `ghc-lib`) Meanwhile, I've opened an issue in `ghc-lib`, see: https://github.com/digital-asset/ghc-lib/issues/391

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3015"></a>

### CODE REVIEW

**Comment by kokobd** [comment]
> so it depends on `ghc-lib`

@michaelpj hlint depends on `ghc-lib-parser` actually, see: https://hackage.haskell.org/package/hlint-3.4/hlint.cabal

**Comment by michaelpj** [comment]
So it does! Seems fine to me, but @pepeiborra might have thoughts since I know he did stuff in this area recently.

**Comment by pepeiborra** [comment]
Looks great to me

**Review by pepeiborra — APPROVED** [review]

**Comment by kokobd** [comment]
@mergifyio refresh

**Pull request merged**
