### PR TITLE
Update to lsp-1.2

### PR DESCRIPTION
**Pull request by wz1000**

### CODE REVIEW

**Comment by wz1000** [comment]
A lot of code action tests are failing because they use incorrect ranges and `lsp-test` recently became more strict about this: https://github.com/haskell/lsp/commit/f90b00266ea4c750df913fbfa6802f5eb24bb426

:( It is a lot of work to fix all of them.

**Comment by jneira** [comment]
MAybe we could restore the old function in lsp, make it deprecated and translate tests progressively?

**Review by pepeiborra — APPROVED** [review]
Very nice!

**Comment by wz1000** [comment]
Benchmarks seem to show some very minor improvements in allocations, possibly because `lsp-types` started using `StrictData`.

**Pull request merged**
