### PR TITLE
Shut the Shake session on exit, instead of restarting it

### PR DESCRIPTION
**Pull request by pepeiborra**
Restarting the session will result in progress reporting and other messages
being sent to the client, which might have already closed the stream

Result of @berberman investigation in #1628

### CODE REVIEW

**Comment by isovector** [comment]
Does this fix the mysterious `resource vanished` errors that happen when running tests in parallel?

**Comment by pepeiborra** [comment]
> Does this fix the mysterious `resource vanished` errors that happen when running tests in parallel? <3

Doesn't seem to fix that

**Comment by pepeiborra** [comment]
> > Does this fix the mysterious `resource vanished` errors that happen when running tests in parallel? <3
> 
> Doesn't seem to fix that

I just gave up and bisected it to 132193e1 (https://github.com/haskell/haskell-language-server/pull/1373). It must be an issue with opening the mysql db before it has been released or similar. /cc @wz1000

**Review by jneira — APPROVED** [review]
LGTM, the change makes totally sense, not sure why `restartShakeSession` was even used at first.

**Comment by wz1000** [comment]
I will try to take a look when I find the time.

**Comment by berberman** [comment]
Hmm, I cherry-picked this to #1628, but test didn't show the fix

**Pull request merged**
