### PR TITLE
Enable `aarch64-darwin` in `flake.nix`

### PR DESCRIPTION
**Pull request by Gabriel439**
Currently only GHC 8.10.7 builds on `aarch64-darwin` after this change

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2561"></a>

### CODE REVIEW

**Review by jneira — COMMENTED** [review]
happy to see you here and thanks for fix the builds for that arch 🙂 
lgtm but will wait for an actual nix user review to merge

**Review by berberman — APPROVED** [review]
LGTM. It seems that GitHub actions don't support aarch64-darwin yet. Is there anyway to test the build?

**Comment by jneira** [comment]
we are building aarch64-darwin in the gitlab repo, only for ghc-8.10.7, it would be matter to change the gitlab CI config to use several ghcs

**Comment by Anton-Latukha** [comment]
Awaited by PR CircleCI builds are not present in the [dashboard queue](https://app.circleci.com/pipelines/github/haskell/haskell-language-server?filter=all).

**Comment by Anton-Latukha** [comment]
[skip circleci]

**Review by michaelpj — APPROVED** [review]

**Pull request merged**
