### PR TITLE
Add a pre commit hook for code formatting

### PR DESCRIPTION
**Pull request by Ailrun**
Resolves partially #693.

I will format code base after this PR. I think it's quite hard to find a time slot when there is no "big" PR, so it's maybe better to send the setting first, and format after (in time slots between big PRs), so that other big PRs can use the setting to format them by their own.

### CODE REVIEW

**Comment by jneira** [comment]
many thanks, agree with the exposed plan
there is no way to only use one config file?

**Review by pepeiborra — APPROVED** [review]
fuckyeah

**Comment by Ailrun** [comment]
@jneira As far as there are different default extensions per directory, no

**Comment by jneira** [comment]
wow 1100 lines of config are hard to digest for me too
could we alliviate it in some way? maybe removing comments for all files but the top one?

**Comment by Ailrun** [comment]
@jneira Yeah sure, all those comments are of the default config generator, and we have [a reference link](https://github.com/jaspervdj/stylish-haskell/blob/main/data/stylish-haskell.yaml), I think it's good to go.

**Comment by Ailrun** [comment]
@jneira How about now?

**Review by jneira — APPROVED** [review]
Yeah, it looks much better now, many thanks!!

**Pull request merged**
