### PR TITLE
added completion for language to { -# LANGUAGE

### PR DESCRIPTION
**Pull request by alexnaspo**
fixes https://github.com/haskell/haskell-language-server/issues/681

### CODE REVIEW

**Comment by pepeiborra** [comment]
I'm not sure what's going on here, but we already have completions for pragmas and they seem to work for me: 

https://github.com/haskell/haskell-language-server/blob/868e4768fd7d91352672060709c88f65d3102644/ghcide/src/Development/IDE/Plugin/Completions/Logic.hs#L658-L671

Perhaps you could look into refining the existing completion snippet so that it inserts the pragma close tokens `#-}` and/or characterise whether it works in all situations?


https://user-images.githubusercontent.com/26626/131214843-883082cf-af8e-4996-b54c-2b2bd523d24c.mov

**Comment by alexnaspo** [comment]
@pepeiborra - sure I can take a look at that. Do I you think I should move the auto completions into the pragmas plugin?

The difference here is that it auto completes on "language" rather than "{-# LANGUAGE" as the ticket requests

**Comment by ndmitchell** [comment]
Haskell is case-insensitive for its pragmas, so `lAnGuAgE` works just fine. Perhaps the completions module just needs to be educated to that fact?

**Comment by pepeiborra** [comment]
> @pepeiborra - sure I can take a look at that. Do you think I should move the auto completions into the pragmas plugin?

That would be great

**Comment by alexnaspo** [comment]
> > @pepeiborra - sure I can take a look at that. Do you think I should move the auto completions into the pragmas plugin?
> 
> That would be great

I opened up a separate PR because it no longer closes the above ticket @pepeiborra

**Comment by jneira** [comment]
@alexnaspo so could we close this one, as it is included in #2134 iiuc?

**Pull request closed without merging**
