### PR TITLE
Reimplement shake (continued)

### PR DESCRIPTION
**Pull request by pepeiborra**
Rebase of #1759 including bugfixes

- [x] pass all the tests
- [x] fix performance regressions (or mitigate via reverse deps)
- [x] implement reverse deps
- [x] test scalability
- [x] implement applicative parallelism (left for future work)

# Summary of changes

* hls-graph is now a full implementation of a reactive dependency graph (aka build system) and no longer wraps Shake. 
* "reactive" means that his-graph tracks reverse dependencies in order to minimize rebuilds when a list of external changes (e.g. which file has been edited) is provided. This in turn means that ghcide now scales much better - rebuilds are no longer linear in the number of transitive module imports (modulo the TH `NeedsCompilation` rule)
* A new flag `--conservative-change-tracking` is added to ghcide to disable reactive change tracking. The flag is intended for debugging only and not for users. A new benchmark example "cabal-conservative" uses it to measure the performance difference.
* Performance in the Cabal example is equal or better (up to 2X) than before
* Build profiling is supported and extends the Shake profiling to include information about dirty nodes and visited nodes.
* Fake `Binary` instances no longer needed and removed from the codebase

# What's missing

* Applicative parallelism - left for future work, hoping someone smarter than me can do it. Doesn't seem to have a major impact, probably will speed up startup times a bit?

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2060"></a>

### CODE REVIEW

**Comment by pepeiborra** [comment]
This seems working now. Performance is a mixed bag, I will look at mining the data later today or tomorrow. 

Before merging I need to implement reverse dependency tracking and measure scalability.

**Comment by pepeiborra** [comment]
# Performance

## Without reverse dependency tracking

Total Time, allocations and max residency are both in the ballpark of Shake, with ups and downs. Using the Cabal example where HEAD is 3dfc695, we have:

* edit total time Is 16.7% higher
* hover total time is 8% lower
* hover after edit total time is 8% higher
* getDefinition total time is 33% lower
* code actions total time is 115% higher (but allocations are slightly lower, weird)
* code actions after edit total time is 18% lower but max residency is 60% higher
* document symbols after edit total time is 500% higher (weird, would be worth repeating), allocations are 160% higher, and max residency is 77% higher 
* etc.
Full results obtained from the Github CI run (agreed, not the most isolated environment):
```
version    name                             success   samples   startup              setup          userTime             delayedTime             totalTime            maxResidency   allocatedBytes
5
upstream   edit                             True      50        2.272495847          0.0            0.312656619          5.235386871999999       5.556636593          176MB          7443MB
6
HEAD       edit                             True      50        2.939898887          0.0            1.525507581000001    4.951573532000001       6.481253863          206MB          8662MB
7
upstream   hover                            True      50        2.2531108630000003   0.0            5.4577234090000015   3.1075063e-2            5.492708015000001    176MB          7121MB
8
HEAD       hover                            True      50        2.833231339          0.0            5.007434441000001    4.3085500000000006e-2   5.060099354          177MB          6940MB
9
upstream   hover after edit                 True      50        2.729492039          0.0            5.381235953999998    22.509599982            27.895088985         204MB          37031MB
10
HEAD       hover after edit                 True      50        2.567809608          0.0            5.418567334000003    24.762967906999993      30.185962892000003   332MB          40195MB
11
upstream   getDefinition                    True      50        2.307331066          0.0            5.701828237000002    1.2548546000000004e-2   5.7181945270000005   175MB          7120MB
12
HEAD       getDefinition                    True      50        2.995683892          0.0            3.585127652000001    0.18568288699999988     3.7749409870000004   173MB          6968MB
13
upstream   getDefinition after edit         True      50        2.14589879           0.0            6.631301436000003    20.42667203700001       27.062120324000002   205MB          36189MB
14
HEAD       getDefinition after edit         True      50        2.7035592150000003   0.0            5.951320493000001    22.8122467              28.768026244         338MB          38282MB
15
upstream   completions                      True      50        1.761511226          0.0            8.047872840000002    1.7012296e-2            8.073320538          203MB          12450MB
16
HEAD       completions                      True      50        2.615275548          0.0            7.111024207000004    1.6015886e-2            7.1318453470000005   198MB          12273MB
17
upstream   completions after edit           True      50        2.258389204          0.0            10.073498866000001   18.923962975000002      29.00345751          236MB          42098MB
18
HEAD       completions after edit           True      50        3.0192549090000003   0.0            10.222434903         20.109549577000003      30.340781481         366MB          44555MB
19
upstream   code actions                     True      50        5.333430205          1.4487374e-2   0.648637333          1.6679171369999999      2.320392221          168MB          7450MB
20
HEAD       code actions                     True      50        2.206230134          2.5243695e-2   1.0010000770000003   3.9947446900000005      5.015267196          163MB          6962MB
21
upstream   code actions after edit          True      50        1.916653975          0.0            20.624939044         1.4387978480000005      22.068674153         191MB          29346MB
22
HEAD       code actions after edit          True      50        2.801418785          0.0            14.555310371000004   3.566505903             18.127092237         303MB          25500MB
23
upstream   code actions after cradle edit   True      50        2.1320045110000003   0.0            13.655822500000003   5.446925311000002       19.107695167000003   209MB          26052MB
24
HEAD       code actions after cradle edit   True      50        2.198851487          0.0            14.194154865000002   5.844885103000003       20.044018823000002   335MB          27824MB
25
upstream   documentSymbols after edit       True      50        1.354437694          0.0            2.6904143140000003   3.9411810650000003      6.638646066000001    179MB          10999MB
26
HEAD       documentSymbols after edit       True      50        2.18587876           0.0            15.608887073999998   4.314848547999999       19.938731197000003   318MB          26012MB
27
upstream   hole fit suggestions             True      50        2.1463324790000002   0.0            47.15185008600001    1.8690116999999996e-2   47.177355986         218MB          60676MB
28
HEAD       hole fit suggestions             True      50        2.551580878          0.0            46.36738798099999    1.8521415e-2            46.392119067         327MB          60259MB
```

## With reverse dependency tracking
Using the Cabal example where HEAD is ac99d9c, we see that total time is lower for most examples but max residency is considerably higher, presumably due to the additional state to track reverse dependencies (or a bug):

* edit total time is 20% lower
* hover after edit total time is 29% lower
* get definition after edit total time is 33% lower but max residency is 180% higher
* completions after edit total time is 30% lower but max residency is 160% higher
* code actions after edit total time is 44% lower
* code actions after cradle edit total time is 59% lower 
* document symbols after edit total time is 36.8% higher, allocations are 15% higher, and max residency is 222% higher
* etc.
Full results:
```
version    name                             success   samples   startup              setup                   userTime             delayedTime             totalTime            maxResidency   allocatedBytes
5
upstream   edit                             True      50        2.0464692120000003   0.0                     3.771236898          6.215939686999999       9.993117938000001    181MB          11779MB
6
HEAD       edit                             True      50        2.5070064260000002   0.0                     3.010397536000001    4.968224615999996       7.983422218          252MB          9115MB
7
upstream   hover                            True      50        1.509634178          0.0                     4.79936772           0.10946838299999999     4.913372751000001    178MB          7116MB
8
HEAD       hover                            True      50        2.7730088910000004   0.0                     5.180883135999997    3.504994100000001e-2    5.230458685          178MB          6997MB
9
upstream   hover after edit                 True      50        2.487633504          0.0                     6.890062458999999    24.930129366            31.825360113000002   207MB          36933MB
10
HEAD       hover after edit                 True      50        2.418334638          0.0                     6.181287432          16.530389695000004      22.717214748         582MB          24948MB
11
upstream   getDefinition                    True      50        1.9895303180000001   0.0                     6.801371679000001    1.5523176000000007e-2   6.821346994000001    177MB          7089MB
12
HEAD       getDefinition                    True      50        3.1426977000000003   0.0                     5.140733387999998    2.8642663999999988e-2   5.174019203          179MB          6983MB
13
upstream   getDefinition after edit         True      50        2.2615483110000003   0.0                     7.9594969220000005   23.39991231600001       31.364496515000003   207MB          36138MB
14
HEAD       getDefinition after edit         True      50        2.871311716          0.0                     6.121026748000002    14.691798131            20.817694644000003   591MB          23630MB
15
upstream   completions                      True      50        1.9937127120000002   0.0                     8.869379315000002    2.0308336e-2            8.895150961          205MB          12447MB
16
HEAD       completions                      True      50        2.5907287070000002   0.0                     7.1039445489999995   2.3898504000000008e-2   7.133802204          205MB          12265MB
17
upstream   completions after edit           True      50        2.383978646          0.0                     10.788709890999996   21.624756953            32.422100895         236MB          42126MB
18
HEAD       completions after edit           True      50        2.780890566          0.0                     12.749612272000006   10.316970059999997      23.079330996000003   614MB          29711MB
19
upstream   code actions                     True      50        2.051170527          1.4181572000000002e-2   0.9363013359999999   5.652116202             6.593045581          173MB          7130MB
20
HEAD       code actions                     True      50        2.985416648          1.1376260000000001e-2   1.102338611          3.7641862959999997      4.886573626000001    170MB          6984MB
21
upstream   code actions after edit          True      50        2.073519519          0.0                     20.554091040000003   5.455980662             26.016013051         195MB          30579MB
22
HEAD       code actions after edit          True      50        3.0034777970000004   0.0                     10.574070786         4.022146447000003       14.603397271         595MB          16776MB
23
upstream   code actions after cradle edit   True      50        2.161535727          0.0                     21.136283263         7.025362857000003       28.167373854         224MB          32129MB
24
HEAD       code actions after cradle edit   True      50        3.1631840380000003   0.0                     8.233220917000002    3.441370713             11.680453183000001   524MB          13065MB
25
upstream   documentSymbols after edit       True      50        2.708412006          0.0                     3.2785558110000004   5.482434728             8.77287724           177MB          11079MB
26
HEAD       documentSymbols after edit       True      50        2.825938144          0.0                     7.695673330000002    4.3817235619999995      12.094445087         571MB          12748MB
27
upstream   hole fit suggestions             True      50        2.468067436          0.0                     53.709667893         2.5438521000000002e-2   53.74341694          216MB          60727MB
28
HEAD       hole fit suggestions             True      50        3.059986549          0.0                     43.864609649         2.6667305000000002e-2   43.898593311000006   603MB          45390MB
```

I will try to rerun the benchmarks in a more isolated environment again. 

The next step will be to measure scalability

**Comment by pepeiborra** [comment]
Repeated the benchmarks in a more isolated environment (Xeon gold 6138 w/ 256GB RAM, 80 virtual cores) and noticed some failed runs due to "Index out of range" crashes in this branch. I guess there must be a parallelism bug somewhere that doesn't arise in the 1-core Github CI agents. Will need to investigate more

**Comment by pepeiborra** [comment]
It reproduces reliably with `ghcide -j64` but not with lower parallelism settings

**Comment by pepeiborra** [comment]
Tracked it down to the GHC thread manager by editing base to use `error` instead of `errorWithoutStackTrace` and add `HasCallStack` constraints until getting a fully defined call stack:

image

```
-- | Retrieve the system event manager for the capability on which the
-- calling thread is running.
--
-- This function always returns 'Just' the current thread's event manager
-- when using the threaded RTS and 'Nothing' otherwise.
getSystemEventManager :: IO (Maybe EventManager)
getSystemEventManager = do
  t <- myThreadId
  (cap, _) <- threadCapability t
  eventManagerArray <- readIORef eventManager
  mmgr <- readIOArray eventManagerArray cap
  return $ fmap snd mmgr
```

https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/GHC/Event/Thread.hs#L182

It looks like `eventManagerArray` is still empty when the runtime tries to index it. This is likely a GHC bug, unless we are doing something wrong like dynamically changing the number of capabilities multiple times.

**Comment by pepeiborra** [comment]
The problem was that we were calling `withNumCapabilities` on every build, resetting the number of caps to 1 in between builds.

**Comment by pepeiborra** [comment]
I believe the performance regressions are due to the parallel evaluation of all the dependencies of a node. Shake is lazy (firstJustM) whereas hls-graph is eager (mapConcurrently)

**Comment by pepeiborra** [comment]
Performance regressions have been mitigated via both a) reverse deps and b) avoiding new threads for trivial lookups. Will follow up with benchmark results soon.

**Comment by pepeiborra** [comment]
# Benchmark results
* All results are expressed in percentages relative to the upstream baseline. 
* The benchmarks are reproducible with `cabal bench ghcide`.
* Summary of results: most experiments stay the same or show an improvement, the only regression is in "document symbols after edit" and it's fairly minor.
* These benchmarks do not illustrate scalability, which I have verified separately on a very large example (~50k modules and >3e7 loc) - the edit experiment is easily 25-50X faster and "after edit" experiments see similar speedups.

## Single core (GitHub Actions CI)
The timings are neither accurate (since the CI environment is hardly isolated) nor representative of real-world performance (since it's a single core CPU) so instead we look only at allocations:

### Cabal example
* The new his-graph allocates 65% as much in the edit experiment. This is reflected in all the "after edit" experiments: hover after edit 75%, getDefinition 75%, completions 78%, code actions 50%.
* Allocations stay similar for most other experiments.

### lsp-types example

I think the usage of TH implies that more things become dirty and need to be visited after an edit, negating the gains of reactive change tracking:

* Allocations stay the same for the edit experiment and increase for the "after edit" experiments. The worst offender is "document symbols after edit" where the allocations are 263%. 
* Allocations stay similar for most other experiments.

## Multi core (Xeon 80 virtual cores)
We look at the timings since the benchmarks were conducted in (approximate) isolation:

### Cabal example
* Edit takes 65% user/total time
* All the after edit experiments take 50% total time
* Document symbols after edit takes 155% user time

version | name | startup | userTime | delayedTime | totalTime | maxResidency | allocatedBytes
-- | -- | -- | -- | -- | -- | -- | --
upstream | edit | 2.53598466 | 24.708606 | 2.43E-02 | 24.74456663 | 219MB | 42700MB
HEAD | edit | 2.94472737 | 16.193653 | 2.45E-02 | 16.22790349 | 240MB | 28790MB
upstream | hover | 2.70296467 | 3.44515804 | 2.20E-02 | 3.473129757 | 193MB | 7306MB
HEAD | hover | 2.92276704 | 2.48070108 | 2.26E-02 | 2.508136966 | 192MB | 7042MB
upstream | hover after edit | 2.58683972 | 2.99076219 | 17.33699553 | 20.33697424 | 220MB | 41926MB
HEAD | hover after edit | 2.79762781 | 2.43766115 | 8.549337048 | 10.99359032 | 231MB | 25373MB
upstream | getDefinition | 2.6557737 | 3.22899011 | 1.30E-02 | 3.248923772 | 198MB | 7213MB
HEAD | getDefinition | 2.67640801 | 2.26901574 | 1.28E-02 | 2.286713812 | 191MB | 6992MB
upstream | getDefinition after edit | 2.69654158 | 3.90109566 | 15.30939572 | 19.21719319 | 219MB | 39367MB
HEAD | getDefinition after edit | 2.83993573 | 2.7949717 | 6.794373219 | 9.595843293 | 219MB | 23017MB
upstream | completions | 2.75133872 | 7.21575148 | 3.16E-02 | 7.255552856 | 231MB | 13253MB
HEAD | completions | 2.96077855 | 5.77697681 | 3.26E-02 | 5.815469853 | 233MB | 12958MB
upstream | completions after edit | 3.0430138 | 7.69445346 | 12.42929006 | 20.13263993 | 258MB | 46061MB
HEAD | completions after edit | 2.72593185 | 6.1292988 | 3.799156817 | 9.937221021 | 249MB | 29693MB
upstream | code actions | 2.60981211 | 0.49602793 | 1.83E-02 | 0.519892269 | 185MB | 7252MB
HEAD | code actions | 2.72057365 | 0.40000988 | 1.99E-02 | 0.424569303 | 186MB | 7012MB
upstream | code actions after edit | 2.50886645 | 18.6275946 | 1.79E-02 | 18.65236915 | 209MB | 33999MB
HEAD | code actions after edit | 3.04432092 | 9.85958574 | 1.94E-02 | 9.884338527 | 226MB | 19215MB
upstream | code actions after cradle edit | 2.56835005 | 188.931965 | 2.26E-02 | 188.9634708 | 360MB | 324016MB
HEAD | code actions after cradle edit | 2.67213333 | 162.305268 | 2.18E-02 | 162.3353871 | 476MB | 303821MB
upstream | documentSymbols after edit | 2.56464055 | 3.31414918 | 2.843750416 | 6.166337438 | 203MB | 13589MB
HEAD | documentSymbols after edit | 2.68454996 | 5.14052794 | 1.988428998 | 7.136795205 | 228MB | 16407MB
upstream | hole fit suggestions | 2.52554848 | 39.1149239 | 2.86E-02 | 39.15389641 | 229MB | 62589MB
HEAD | hole fit suggestions | 2.97602832 | 28.4869678 | 2.74E-02 | 28.52315337 | 246MB | 46201MB

### cabal-1module example

The default Cabal example performs edits to two modules. To better illustrate the benefits of reactive change tracking, I have added a variation that only edits one example:
* edit takes 46% user/total time
* Most after edit experiments take 33% total time (3X faster)
* code actions after edit takes 25% user time  (4X faster)

version | name | startup | userTime | delayedTime | totalTime | maxResidency | allocatedBytes
-- | -- | -- | -- | -- | -- | -- | --
upstream | edit | 2.48501666 | 23.6376006 | 2.49655876 | 26.14557464 | 206MB | 40900MB
HEAD | edit | 2.61512174 | 10.6523906 | 1.901214414 | 12.5637833 | 217MB | 22514MB
upstream | hover | 3.23378772 | 2.29598115 | 0.121211323 | 2.422728695 | 179MB | 7692MB
HEAD | hover | 2.93107088 | 1.94912751 | 2.21E-02 | 1.976057272 | 182MB | 6668MB
upstream | hover after edit | 2.57750427 | 2.96890254 | 19.59170611 | 22.57029029 | 205MB | 39941MB
HEAD | hover after edit | 2.80093193 | 2.31926988 | 7.488339257 | 9.814434468 | 200MB | 21418MB
upstream | getDefinition | 2.49619366 | 4.11669638 | 1.88E-02 | 4.141482597 | 183MB | 7054MB
HEAD | getDefinition | 2.68944126 | 2.16104519 | 2.38E-02 | 2.190701358 | 180MB | 6748MB
upstream | getDefinition after edit | 2.52113195 | 4.35008456 | 18.67110407 | 23.03062437 | 206MB | 37714MB
HEAD | getDefinition after edit | 2.57353766 | 2.55862184 | 5.379343998 | 7.944271746 | 204MB | 19271MB
upstream | completions | 2.71271268 | 4.3491541 | 2.76E-02 | 4.382326515 | 215MB | 8644MB
HEAD | completions | 2.79735139 | 2.99245545 | 2.42E-02 | 3.021610079 | 210MB | 8119MB
upstream | completions after edit | 2.50743504 | 5.40487089 | 17.26615878 | 22.67934809 | 242MB | 39833MB
HEAD | completions after edit | 2.71608766 | 3.61525078 | 4.155283425 | 7.778108361 | 242MB | 21380MB
upstream | code actions | 2.70054214 | 0.90298905 | 2.126290701 | 3.035142643 | 199MB | 7520MB
HEAD | code actions | 2.63301218 | 0.65997027 | 1.620024849 | 2.284751954 | 198MB | 7008MB
upstream | code actions after edit | 2.58818866 | 18.7127663 | 2.186310954 | 20.90721214 | 225MB | 33751MB
HEAD | code actions after edit | 2.56561631 | 4.38817674 | 1.920228921 | 6.314646523 | 221MB | 15211MB
upstream | code actions after cradle edit | 2.49314033 | 187.417995 | 2.10E-02 | 187.449082 | 389MB | 333329MB
HEAD | code actions after cradle edit | 2.66418871 | 163.503891 | 2.22E-02 | 163.5336644 | 477MB | 312314MB
upstream | documentSymbols after edit | 2.54009097 | 2.00810659 | 3.379384641 | 5.397430896 | 182MB | 11090MB
HEAD | documentSymbols after edit | 2.68806718 | 3.4662947 | 2.138651834 | 5.616096477 | 199MB | 13541MB
upstream | hole fit suggestions | 2.50779208 | 36.8980504 | 2.80E-02 | 36.93669408 | 216MB | 55486MB
HEAD | hole fit suggestions | 2.84546459 | 22.6475412 | 2.60E-02 | 22.68281609 | 207MB | 37020MB




### lsp-types example
* code actions after edit takes 72% user time
* most other experiments stay the same


version | name | startup | userTime | delayedTime | totalTime | maxResidency | allocatedBytes
-- | -- | -- | -- | -- | -- | -- | --
upstream | edit | 1.37620278 | 40.6878197 | 2.39E-02 | 40.72336873 | 255MB | 55379MB
HEAD | edit | 1.33751171 | 39.252613 | 2.20E-02 | 39.28358766 | 275MB | 52757MB
upstream | hover | 1.3453145 | 11.2155751 | 2.35E-02 | 11.24619299 | 222MB | 8832MB
HEAD | hover | 1.29731494 | 10.1681567 | 3.01E-02 | 10.20483367 | 215MB | 8650MB
upstream | hover after edit | 1.41179167 | 10.5409676 | 21.34668909 | 31.89528199 | 243MB | 44155MB
HEAD | hover after edit | 1.31959952 | 10.0501625 | 18.51681424 | 28.57285371 | 258MB | 39617MB
upstream | getDefinition | 1.32569416 | 10.2969265 | 2.79E-02 | 10.33113972 | 221MB | 8792MB
HEAD | getDefinition | 1.32550522 | 11.0909744 | 2.52E-02 | 11.12093204 | 214MB | 8577MB
upstream | getDefinition after edit | 1.29433365 | 10.0885509 | 20.91779332 | 31.01287115 | 246MB | 41791MB
HEAD | getDefinition after edit | 1.31599043 | 9.94149777 | 17.65923814 | 27.60692905 | 265MB | 40997MB
upstream | completions | 1.42880118 | 11.5031083 | 2.78E-02 | 11.53675342 | 286MB | 10698MB
HEAD | completions | 1.25005949 | 11.0161325 | 2.89E-02 | 11.05022731 | 284MB | 10647MB
upstream | completions after edit | 1.3672182 | 11.7100197 | 19.74023712 | 31.45877638 | 307MB | 44027MB
HEAD | completions after edit | 1.33621014 | 11.5872805 | 16.67003411 | 28.26342589 | 324MB | 41335MB
upstream | code actions | 1.40727354 | 0.94465022 | 3.06E-02 | 0.981459938 | 265MB | 9564MB
HEAD | code actions | 1.38878761 | 0.93801064 | 3.01E-02 | 0.973410457 | 263MB | 9600MB
upstream | code actions after edit | 1.30505035 | 43.2282183 | 2.95E-02 | 43.26561631 | 283MB | 54477MB
HEAD | code actions after edit | 1.29945591 | 31.3152023 | 9.924278858 | 41.2455266 | 323MB | 52227MB
upstream | code actions after cradle edit | 1.2998428 | 0 | 0 | 99.34283133 | 528MB | 263308MB
HEAD | code actions after cradle edit | 1.32474777 | 0 | 0 | 50.84505475 | 714MB | 140620MB
upstream | documentSymbols after edit | 1.31251317 | 2.008693 | 9.878942893 | 11.89351432 | 223MB | 12738MB
HEAD | documentSymbols after edit | 1.39438832 | 1.95289526 | 9.832242459 | 11.79196715 | 242MB | 15781MB
upstream | hole fit suggestions | 1.5162005 | 132.872453 | 3.07E-02 | 132.9143751 | 284MB | 195549MB
HEAD | hole fit suggestions | 1.32091473 | 130.736872 | 2.66E-02 | 130.7728339 | 336MB | 216767MB

**Comment by pepeiborra** [comment]
@mpickering @wz1000 it would be great if you could give this branch a go with GHC
@adamse same with the SCL codebase.

**Comment by adamse** [comment]
I will try it, should I use plain ghcide or does it work with full hls too?

**Comment by pepeiborra** [comment]
> I will try it, should I use plain ghcide or does it work with full hls too?

Whichever you use normally. The changes here apply to both.

**Comment by adamse** [comment]
Anything in particular I should report back on @pepeiborra ?

**Comment by pepeiborra** [comment]
> Anything in particular I should report back on @pepeiborra ?

Does it work and feel faster? Does it use more or less RAM?

**Comment by jneira** [comment]
hlint is not happy:

```
 ghcide/bench/lib/Experiments.hs:170:19-43: Warning: Use all
Found:
  null . concat . catMaybes
Perhaps:
  all null . catMaybes
```

**Comment by wz1000** [comment]
@pepeiborra I tried out this branch and it seems to work fine on GHC. I couldn't use it much though as I'm mostly working on the lexer for the past few days (I don't think it would be too hard to have it supported in HLS but it would require some changes to hadrian as well).

**Review by jneira — APPROVED** [review]
Approving it by pure trust :slightly_smiling_face: 
Do you think it could be included in the next release or we should wait and dogfooding in master?

**Comment by adamse** [comment]
I was on a previous version of this work before, so I cannot really say how it compares to stock hls for memory usage etc right now.

One problem I've been having is that changes made to module dependencies that did not come from the editor are not picked up.

For example: I'm editing some haskell module using the mu-ffi stub modules. If I regenerate the ffi stub modules to get access to a new record field HLS never notices that the stub module changed on disk. It seems that sometimes opening the stub module in the editor helps, but other times I've had to delete the caches and restart HLS.

**Comment by pepeiborra** [comment]
> I was on a previous version of this work before, so I cannot really say how it compares to stock hls for memory usage etc right now.
> 
> One problem I've been having is that changes made to module dependencies that did not come from the editor are not picked up.
> 
> For example: I'm editing some haskell module using the mu-ffi stub modules. If I regenerate the ffi stub modules to get access to a new record field HLS never notices that the stub module changed on disk. It seems that sometimes opening the stub module in the editor helps, but other times I've had to delete the caches and restart HLS.

Thanks! This is useful feedback. 

We no longer rebuild everything - only the things that have changed in the IDE. That said, we set up file system watches for all the Haskell files in the workspace, and dirty the build graph on file system changes. 

Questions:

1. Does your editor support file system watches? If it's VSCode then yes.
2. Do the stub modules live inside the workspace?

**Comment by pepeiborra** [comment]
> Approving it by pure trust 🙂
> Do you think it could be included in the next release or we should wait and dogfooding in master?

Wait until 1.5.0. 
Also, it would be good if @ndmitchell can take a look!

**Comment by pepeiborra** [comment]
> > I was on a previous version of this work before, so I cannot really say how it compares to stock hls for memory usage etc right now.
> > One problem I've been having is that changes made to module dependencies that did not come from the editor are not picked up.
> > For example: I'm editing some haskell module using the mu-ffi stub modules. If I regenerate the ffi stub modules to get access to a new record field HLS never notices that the stub module changed on disk. It seems that sometimes opening the stub module in the editor helps, but other times I've had to delete the caches and restart HLS.
> 
> Thanks! This is useful feedback.
> 
> We no longer rebuild everything - only the things that have changed in the IDE. That said, we set up file system watches for all the Haskell files in the workspace, and dirty the build graph on file system changes. After regenerating the stubs, you may need to force a rebuild by making an edit in any file.
> 
> If that does not help:
> 
> 1. Does your editor support file system watches? If it's VSCode then yes.
> 2. Do the stub modules live inside the workspace?

Another thing that could be happening here is that your LSP client is sending relative paths in the watched file notification. Can you find and share the below line in your logs, after updating the stub modules:
```
2021-09-11 12:31:12.851695 [ThreadId 16] DEBUG hls:	Restarting build session due to [FileEvent {_uri = Uri {getUri = "file:///Users/pepe/scratch/haskell-language-server/ghcide/test/data/recomp/B.hs"}, _xtype = FcChanged}] for keys [GetModificationTime_ {missingFileDiagnostics = True}; /Users/pepe/scratch/haskell-language-server/ghcide/test/data/recomp/B.hs,GetModificationTime_ {missingFileDiagnostics = True}; ...] (aborting the previous one took 0.00s)
```

**Comment by adamse** [comment]
I'm using vim with coc, I don't know about file watches. I'm not sure what you mean with workspace in "Do the stub modules live inside the workspace?". I'll take a look at the logs, do I have to do anything to get DEBUG messages?

**Comment by pepeiborra** [comment]
> I'm using vim with coc, I don't know about file watches. I'm not sure what you mean with workspace in "Do the stub modules live inside the workspace?". 

Are the files in a folder container below the workspace root? Back in the day they were, but I don't know if they still are after the FromMu rewrite.

> I'll take a look at the logs, do I have to do anything to get DEBUG messages?

Yes, you need to start ghcide with `--verbose` or HLS with `-d`

**Comment by vapourismo** [comment]
The stub modules are located within the workspace but in the build output folder. Maybe they are ignored by Vim/the editor because of that?

**Comment by pepeiborra** [comment]
> The stub modules are located within the workspace but in the build output folder. Maybe they are ignored by Vim/the editor because of that?

Most probably, if the client is`.gitignore` aware.

**Comment by mpickering** [comment]
I will try out your branch now @pepeiborra

**Comment by mpickering** [comment]
> I will try out your branch now @pepeiborra

Initial impressions are that performance is much better than before. I will report back if I find any issues.

**Comment by jneira** [comment]
hmm there is a test fail in tactics which seems non transient:

```
providers
      Produces (homomorphic) lambdacase code actions:                                 FAIL (2.21s)
        predicate failed on: False
        Use -p '/Produces (homomorphic) lambdacase code actions/' to rerun this test only.
     Suggests homomorphism if the domain is bigger than the codomain:                FAIL (2.45s)
        predicate failed on: False
```

will rerun just in case

**Comment by pepeiborra** [comment]
> hmm there is a test fail in tactics which seems non transient:
> 
> ```
> providers
>       Produces (homomorphic) lambdacase code actions:                                 FAIL (2.21s)
>         predicate failed on: False
>         Use -p '/Produces (homomorphic) lambdacase code actions/' to rerun this test only.
>      Suggests homomorphism if the domain is bigger than the codomain:                FAIL (2.45s)
>         predicate failed on: False
> ```
> 
> will rerun just in case

But they only fail on Windows and pass everywhere else. Must be a timing issue

**Comment by jneira** [comment]
Curious

```
    Received an exepected error in a response for id SomeLspId (IdInt 1):
    ResponseError {_code = InternalError, _message = "Error: Could not get AST", _xdata = Nothing}
```

and like the other ones in windows and ghc 9

**Comment by pepeiborra** [comment]
> Curious
> 
> ```
>     Received an exepected error in a response for id SomeLspId (IdInt 1):
>     ResponseError {_code = InternalError, _message = "Error: Could not get AST", _xdata = Nothing}
> ```
> 
> and like the other ones in windows and ghc 9

Really? The Windows and GHC 9 job is responsible for 90% of the flaky failures. A few recent examples:

* https://github.com/haskell/haskell-language-server/runs/3615398393?check_suite_focus=true
* https://github.com/haskell/haskell-language-server/runs/3604918635?check_suite_focus=true
* https://github.com/haskell/haskell-language-server/runs/3570839437?check_suite_focus=true
* https://github.com/haskell/haskell-language-server/runs/3569413696?check_suite_focus=true

"Error: Could not get AST" is just the message produced by the rename plugin, the real issue is a few lines above it:
```
                "message": "C:\\Users\\runneradmin\\AppData\\Local\\ghcide\\main-f2d48aeee863b17c96d5d471fac02998fdcdb256\\ext5483: renameFile:renamePath:MoveFileEx \"\\\\\\\\?\\\\C:\\\\Users\\\\runneradmin\\\\AppData\\\\Local\\\\ghcide\\\\main-f2d48aeee863b17c96d5d471fac02998fdcdb256\\\\ext5483\" Just \"\\\\\\\\?\\\\C:\\\\Users\\\\runneradmin\\\\AppData\\\\Local\\\\ghcide\\\\main-f2d48aeee863b17c96d5d471fac02998fdcdb256\\\\Main.hie\": permission denied (Access is denied.)",
```

**Comment by jneira** [comment]
> Really? The Windows and GHC 9 job is responsible for 90% of the flaky failures.

yeah i saw that pattern too and it is killing ci, but it worked better not much time ago, just after adding it, no?
and otoh i did not see this ones from tactics in master, maybe it is coincidence?

we have to analyze what tests are the more frequently failing ones, to try to infer the cause and eventually mark them as ignored in windows and ghc-9 if necessary

**Comment by pepeiborra** [comment]
> > Really? The Windows and GHC 9 job is responsible for 90% of the flaky failures.
> 
> yeah i saw that pattern too and it is killing ci, but it worked better not much time ago, just after adding it, no?
> and otoh i did not see this ones from tactics in master, maybe it is coincidence?

The new graph engine runs things in a different way and as a result, the diagnostics reporting cadence is different from the Shake engine. As a result some tests became more flaky, including those tactics plugin tests. I have fixed those and other tests to make them insensitive to the order diagnostics are reported.   

> we have to analyze what tests are the more frequently failing ones, to try to infer the cause and eventually mark them as ignored in windows and ghc-9 if necessary

I don't know, it seems fairly widespread. Analysing and fixing it would be time consuming. 
Maybe just run fewer test suites in Windows?

**Comment by mpickering** [comment]
I am using this branch daily now and didn't notice any issues last week.

**Comment by jneira** [comment]
> Maybe just run fewer test suites in Windows?

hmm If we would have to skip one of them i would prefer it is not the last ghc version one. We have to live with it for long time.

**Comment by pepeiborra** [comment]
@jneira the hls-rename-plugin tests seem to become very flaky with this change in Windows. I wonder if this is because the new graph backend is spawning more threads. Could you do the following and report:

a) Use this branch on Windows for a few days and let us know if you observe any crashes,
b) Try to reproduce the test failures in the rename plugin.

**Comment by jneira** [comment]
I've installed this version using the new feature `ghcup compile`, but hls-rename-plugin is not activated by default so have to install it enabling it. In ci logs i see error in hls-eval-plugin (as hls-rename-plugin tests are not enabled neither afaics) so i am gonna test it too

**Comment by pepeiborra** [comment]
Finally!
😱😱😱😱😱

**Pull request merged**
