### PR TITLE
Use custom config for completions plugin

### PR DESCRIPTION
**Pull request by berberman**
* Remove `haskell.completionSnippetsOn`
* Use `Properties` (#1576) to define the custom config, including switches of whether to enable snippets and auto extending import lists.

Clients now shoud provide JSON value like:
```json
"ghcide-completions":{
      "globalOn":true,
      "config":{
         "autoExtendOn":true,
         "snippetsOn":true
      },
      "completionOn":true
}
```

in the section `haskell.plugin` to control completions plugin.

### CODE REVIEW

**Comment by michaelpj** [comment]
Do we want to call it "ghcide-completions"? `ghcide` is more-or-less not user-facing any more, perhaps we should try and avoid mentioning the name in user-visible config? Could we just call it "completions"?

**Comment by berberman** [comment]
The name "ghcide-completions" comes from its descriptor:
https://github.com/haskell/haskell-language-server/blob/b9c6e6cf4de5a0778c5ddb5d5e62fc8d1e0d78ef/ghcide/src/Development/IDE/Plugin/HLS/GhcIde.hs#L22-L29
In my opnion we'd better not introduce new names for the key, but use descriptors to keep things simple. Besides, I don't think it would be great to call the key "completions", because there might be other plugins are providing completion functionality as well.

**Review by jneira — APPROVED** [review]
lgtm

**Comment by pepeiborra** [comment]
One option is to merge all the "ghcide-" descriptors into a single one and call it simply "HLS"

**Comment by berberman** [comment]
Currently `CustomConfig` blocks defining the merge operation of descriptors, which means we need define the custom config for type lenses plugin and completions plugin in one `Properties` if we merge ghcide descriptors together. This would bring unnecessary couplings, imho.

**Pull request merged**
