### PR TITLE
Activate typechecking in non-lsp mode

### LINKED ISSUE #84: haskell-language-server 0.1 stops before checking files
Running haskell-language-server (or the included ghcide binary) just stops before checking any source files. 
e.g. within the haskell-language-server directory:
```
> ln -s hie.yaml.stack hie.yaml
> haskell-language-server                                                                                                                                      
ghcide version: 0.1.0.0 (GHC: 8.6.5) (PATH: /home/phil/.local/bin/haskell-language-server) (GIT hash: 019b02831595b6a3be6776bfc56060ab918876e7)
(haskell-language-server)Ghcide setup tester in /home/phil/projects/hackage/haskell-language-server.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/6: Finding files to test in /home/phil/projects/hackage/haskell-language-server
Found 97 files

Step 2/6: Looking for hie.yaml files that control setup
Found 2 cradles

Step 3/6: Initializing the IDE

Step 4/6: Type checking the files
```

The same happens when I run ghcide:
```
> ghcide                                                                                                                                                       ghcide version: 0.1.0 (GHC: 8.6.5) (PATH: /home/phil/.local/bin/ghcide) (GIT hash: )                                                                                                                                                           
Ghcide setup tester in /home/phil/projects/hackage/haskell-language-server.                                                                                                                                                                    
Report bugs at https://github.com/digital-asset/ghcide/issues                                                                                                                                                                                  
                                                                                                                                                                                                                                               
Step 1/6: Finding files to test in /home/phil/projects/hackage/haskell-language-server                                                                                                                                                         
Found 97 files                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                               
Step 2/6: Looking for hie.yaml files that control setup                                                                                                                                                                                        
Found 2 cradles

Step 3/6: Initializing the IDE
[DEBUG] Warning: Client does not support watched files. Falling back to OS polling

Step 4/6: Type checking the files
[DEBUG] Set files of interest to: [NormalizedFilePath "/home/phil/projects/hackage/haskell-language-server/ghcide/src/Development/IDE/Core/FileStore.hs"
<...snip...>
```

This is on NixOs, but I installed haskell-lanaguage-server just by `stack install` without any configuration changes.

### PR DESCRIPTION
**Pull request by jneira**
* Fixes #84

### CODE REVIEW

**Comment by Philonous** [comment]
The `haskell-language-server` executable now tries to type check the project, but the `ghcide` that is installed alongside it still stops after step 4/6.

**Comment by jneira** [comment]
@Philonous ideally the ghcide executable should not even be built in this project: we use ghcide as library in a submodule that points to other repo but we cant exclude (easily) the executable from the build. So, in general, fixes in the ghcide executable should belongs to ghcide itself (well actually the fork we are using: https://github.com/mpickering/ghcide/tree/hls)

That said it is a tiny patch and i will open another one upstream

I'll make another pr to the above repo to activate it though.

**Comment by Philonous** [comment]
@jneira That is fair enough, and I don't really mind, I just wanted to let you know in case you missed it.

**Comment by jneira** [comment]
@Philonous yeah, thanks for that i only want to clarify the relation between hls and ghcide, it is a little bit blurry, even for me! 😄

**Comment by jneira** [comment]
> That said it is a tiny patch and i will open another one upstream

It turned out that it is already fixed in  https://github.com/mpickering/ghcide/tree/hls so all done here

**Pull request merged**
