### PR TITLE
Restore kick (#676)

### PR DESCRIPTION
**Pull request by wz1000**
Fix https://github.com/haskell/haskell-language-server/issues/676

Another indicator that we should probably merge ghcide and HLS.

### CODE REVIEW

**Comment by pepeiborra** [comment]
While this is an unfortunate bug and probably my fault, I don't know that merging the projects is the only or even the best solution!

Better end to end testing would have prevented this. Run the ghcide test suite against HLS.

**Review by pepeiborra — APPROVED** [review]

**Comment by wz1000** [comment]
> Better end to end testing would have prevented this. Run the ghcide test suite against HLS.

That might take a bit of work though, since many ghcide tests could break due to the additional HLS stuff. Now that we are depreciating the ghcide executable, I wonder if having separate repositories actually buys us anything.

**Comment by jneira** [comment]
Imo yo have both separated helps to keep their responsabilities separated too. 
Not sure it it worths the extra effort.

Now almost only the Main.hs is duplicated between them and that is the origin of the bug afaics. 

https://github.com/haskell/haskell-language-server/blob/c64490f5a04d30730bb478f70e65bd108f425135/src/Ide/Main.hs#L126-L141

Not sure if we can reduce the duplication move it to the ghcide lib

**Comment by jneira** [comment]
Thanks for the fix! I will cut a new release asap

**Pull request merged**
