### PR TITLE
Add linux mint builds

### PR DESCRIPTION
**Pull request by hasufell**
https://github.com/haskell/haskell-language-server/issues/3247

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3263"></a>

### CODE REVIEW

**Comment by hasufell** [comment]
gitlab pipeline succeeded: https://gitlab.haskell.org/maerwald/haskell-language-server/-/pipelines/57536

**Comment by andys8** [comment]
Hey there, there seems to be a builds of debian, none for ubuntu, and now builds for mint. I'm just wondering in the reasoning why explicit builds for mint are added, but I guess for Ubuntu not necessary. Or why Ubuntu (more common) wouldn't work for mint? What is the reasoning here? I'm just curious 😉

**Comment by hasufell** [comment]
https://github.com/haskell/haskell-language-server/pull/3191

**Comment by andys8** [comment]
Ah, okay 😉 And why isn't Ubuntu sufficient for mint?

**Comment by hasufell** [comment]
> Ah, okay 😉 And why isn't Ubuntu sufficient for mint?

See https://github.com/haskell/haskell-language-server/issues/3247#issuecomment-1272220609

**Comment by michaelpj** [comment]
This is for the old gitlab CI

**Pull request closed without merging**
