### PR TITLE
Use latest fourmolu

### PR DESCRIPTION
**Pull request by googleson78**
My motivation for this is that the latest `fourmolu` has more config options which I want to use.

### CODE REVIEW

**Comment by googleson78** [comment]
Hm, maybe the formatting changed since that version, and so I need to just change the test?

**Comment by googleson78** [comment]
Also I'm not sure if configs are being loaded correctly, need to investigate.

**Comment by georgefst** [comment]
Thanks for having a go at this!

This is very much on my radar. We've just got one more patch to go in before we finally make a major release. I'd expect that'll be on Hackage by the weekend. And I've already rewritten the HLS plugin locally. Perhaps I should have put that here as a draft PR to save you the time. In general, I'll be pretty vigilant about keeping this up to date, since HLS is also the main way I interact with Fourmolu.

**Comment by georgefst** [comment]
Yeah, the test is broken because the default is now to respect import groups.

But anyway, this should unfortunately probably be closed in favour of the PR I'll be opening in a few days.

**Comment by googleson78** [comment]
is subsumed by #455

**Pull request closed without merging**
