### PR TITLE
Prepare 0.6 release

### PR DESCRIPTION
**Pull request by jneira**
* i want to add screenshots for hlint and module plugins

### CODE REVIEW

**Review by bubba — APPROVED** [review]
LGTM!

**Review by isovector — APPROVED** [review]

**Comment by bubba** [comment]
@jneira Argh, looks like we got really unlucky and GitHub decided to break just as we were making the release: https://github.com/actions/upload-release-asset/issues/68

**Comment by bubba** [comment]
Once it gets fixed on their end you can try deleting the tag and release and trying again

**Comment by jneira** [comment]
oh, i thought that rerunning the job, it will upload the artifacts 😟

**Comment by jneira** [comment]
@bubba i've deleted the tag and release and include your last fixes, let's see what happens now

**Comment by jneira** [comment]
@bubba it is unfortunate that the tag and release had to be deleted to trigger a clean github action.
I thought we could at least delete only uploaded artifacts and rerun the build but the tar job cant be rerunned (??)

**Pull request merged**
