### PR TITLE
Class plugin bump up

### PR DESCRIPTION
**Pull request by Ailrun**
Now it supports GHC 9.0

Ref: #297

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2475"></a>

### CODE REVIEW

**Review by jneira — COMMENTED** [review]
great, we are getting closer to ghc-9 full support
I would take a look to hls .cabal file, now plugins have ghc bounds in that file to allow hackage installations and ghc-9

**Comment by Ailrun** [comment]
Oops, you are right, I missed the hls .cabal file. I will fix that soon.

**Review by jneira — APPROVED** [review]
many thanks! to merge when ci is happy

**Comment by Anton-Latukha** [comment]
Looks like 1 test build was not terminating. Restarted the workflow.

**Comment by Anton-Latukha** [comment]
Thank you, @Ailrun, & everybody,

**Comment by Ailrun** [comment]
@Anton-Latukha
> simultaneously aborted with error return code

This part is actually because I cancelled it. It's somehow blocked indefinitely. Thank you for the restart.

**Pull request merged**
