### PR TITLE
Remove custom version of operational

### PR DESCRIPTION
**Pull request by jneira**
* After a ghc-9.0.1 compat versions has been published in hackage (see https://github.com/HeinrichApfelmus/operational/issues/29)

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2249"></a>

### CODE REVIEW

**Comment by jneira** [comment]
I've removed the source package from nix but it needs something to use operational released version (see fail here: https://github.com/haskell/haskell-language-server/runs/3752456136)
Any nix expert could propose or commit the proper fix? @berberman?

**Comment by michaelpj** [comment]
Pushed a fix, I hope.

**Comment by michaelpj** [comment]
Now it's just some windows thing?

**Comment by jneira** [comment]
> 
> 
> Now it's just some windows thing?

Yeah the same thing in all prs since #2060 was merged (window tests were flaky before but they passed from time to time, now it is very improbable). I tried to fix it without luck in #2248 and pepe in #2243

**Comment by jneira** [comment]
@michaelpj so this would be good to merge?

**Comment by michaelpj** [comment]
Oh yes certainly, I was just wondering what was up with the Windows stuff.

**Comment by jneira** [comment]
> 
> 
> Oh yes certainly, I was just wondering what was up with the Windows stuff.

the label still needs some approving review to be effective :slightly_smiling_face:

**Review by michaelpj — APPROVED** [review]

**Comment by michaelpj** [comment]
Oh lol, I forgot we required approving reviews, sorry.

**Pull request merged**
