### PR TITLE
Reformat all files

### PR DESCRIPTION
**Pull request by Ailrun**
This is a successor of #1384.

However, some CPP modules do not work with any formatters (including `stylish-haskell`, `ormolu`, `brittany`), so I format them by manually removing and then re-adding CPP parts.

### CODE REVIEW

**Review by jneira — APPROVED** [review]
thanks! it seems the code base was following the formatter rules, not much locs

**Comment by Ailrun** [comment]
@Mergifyio rebase

**Comment by isovector** [comment]
Can I opt out of changes like this for tactics in the future? Splitting up imports over multiple lines severely breaks my workflow.

**Comment by Ailrun** [comment]
@isovector May I ask what kinds of workflow, if you don't mind? As we now have a pre-commit hook and will add CI checker, format will be enforced (except for hie-compat, with the justification of "we want to leave the code as close to original GHC code as possible)

**Pull request merged**
