### PR TITLE
Remove HIE_CACHE from circleci cache key

### PR DESCRIPTION
**Pull request by jneira**
This was added in https://github.com/haskell/haskell-ide-engine/pull/968#issuecomment-445067713
I think it is better to make explicit the invalidation with a commit, to make clear in the commit history when it was done

Will delete the env var from circleci config once this is merged

### CODE REVIEW

**Comment by jneira** [comment]
As this will invalidate the cache for all prs, it will better wait to merge the ready ones

**Comment by Ailrun** [comment]
I think it's better to merge this after this release, as I will prepare the release in a few hours.

**Comment by jneira** [comment]
> 
> 
> I think it's better to merge this after this release, as I will prepare the release in a few hours.

Sure, this can wait

Hey it will continue being July release for one day :smile:

**Review by bubba — APPROVED** [review]

**Review by Ailrun — APPROVED** [review]

**Comment by jneira** [comment]
* I've deleted the env var from circleci settings

**Pull request merged**
