### PR TITLE
cabal-ghc921.project: updated index-state

### PR DESCRIPTION
**Pull request by Anton-Latukha**

### CODE REVIEW

**Comment by jneira** [comment]
hard to make the cache works without some of changes in .cabal config files in the branch
an alternative could be enable manual runs of the caching workflow in any branch, see #2528

**Comment by Anton-Latukha** [comment]
Yes.

But as we discussed earlier updates to Hackage are still wanted.

Closing since: https://github.com/haskell/haskell-language-server/pull/2503#issuecomment-1000497645

**Comment by Anton-Latukha** [comment]
Nope.

Would keep it to monitor the package dependency & configuration troubles on consistent code (if that would be possible), until GHC 9.2 support would solve into a particular index & be near merge.

**Comment by pepeiborra** [comment]
> Nope.
> 
> Would keep it to monitor the package dependency & configuration troubles on consistent code (if that would be possible), until GHC 9.2 support would solve into a particular index & be near merge.

Thank you for your help @Anton-Latukha. Your last commit seems to have broken Cabal. I am going to revert it in order to unblock this PR.

What is it that you are trying to accomplish? Can it wait until we have finished with this PR? I don't think that the cache performance is a priority right now.

**Comment by michaelpj** [comment]
This got bumped recently, I think this is superseded?

**Comment by Anton-Latukha** [comment]
Yep.

**Pull request closed without merging**
