### PR TITLE
Introduce golden testing

### PR DESCRIPTION
**Pull request by Ailrun**
This PR introduces a golden testing facility and restores most of the format tests.

Related comments: https://github.com/haskell/haskell-language-server/pull/146#discussion_r436191050

@alanz, I want to join this project team. Is it possible to join?

### CODE REVIEW

**Comment by jneira** [comment]
I am in favor too for some cases, formatting could be one of them.
However, one caveat is string files are platform dependent (at least new lines). I guess those tests pass in linux but not sure if it will do in windows (an its "lovely" `\r\n\`)
If you use unicode the fun could be endless (i hope it will be not the case)

**Comment by Ailrun** [comment]
@jneira Hm, so `documentContents` can start to use `\r\n` even when the initial file is written in `\n`? Sound depressing... anyhow, that case I will add some kinds of normalization before the saves begin.

**Comment by jneira** [comment]
@ailrun let me checkout the branch and run them to confirm it, i hope maybe i am wrong 😄

**Comment by Ailrun** [comment]
OK, I will wait your confirmation then.

**Comment by jneira** [comment]
Well, tests are passing cause the crlf conversion is already being done, a pleasant surprise:

```
stylish-haskell
      formats a document:                                                 warning: LF will be replaced by CRLF in C:\TEMP\StyB51A.actual.
The file will have its original line endings in your working directory
OK (21.80s)
      formats a range:                                                    warning: LF will be replaced by CRLF in C:\TEMP\StyC6FE.actual.
The file will have its original line endings in your working directory
OK (20.56s)
    brittany
      formats a document with LF endings:                                 warning: LF will be replaced by CRLF in C:\TEMP\BriE360.actual.
The file will have its original line endings in your working directory
OK (19.45s)
      formats a document with CRLF endings:                               warning: LF will be replaced by CRLF in C:\TEMP\BriF3FB.actual.
The file will have its original line endings in your working directory
OK (21.09s)
      formats a range with LF endings:                                    warning: LF will be replaced by CRLF in C:\TEMP\Bri60D.actual.
The file will have its original line endings in your working directory
OK (20.53s)
      formats a range with CRLF endings:                                  warning: LF will be replaced by CRLF in C:\TEMP\Bri12C0.actual.
The file will have its original line endings in your working directory
OK (19.20s)
    ormolu
      formats correctly:                                                  warning: LF will be replaced by CRLF in C:\TEMP\For1D31.actual.
The file will have its original line endings in your working directory
OK (14.64s)
```

🎉

**Comment by Ailrun** [comment]
Great! Let me merge this since it works in Windows too :)

**Comment by jneira** [comment]
I wonder where the conversion is being done, maybe `tasty-golden`?

**Pull request merged**
