### PR TITLE
Lock-less hls-graph 

### PR DESCRIPTION
**Pull request by pepeiborra**
First PR extracted from #2357. While I don't have performance measurements for this change alone, the final performance results are in https://github.com/haskell/haskell-language-server/pull/2357#issuecomment-981146589

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2411"></a>

### CODE REVIEW

**Review by jneira — APPROVED** [review]
lgtm by pure trust 😉
hope the performance will not be worse in machines with few cores or with j2

**Comment by pepeiborra** [comment]
> lgtm by pure trust 😉, thanks!
> 
> hope the performance will not be worse in machines with few cores or with j2

Check the comment on the mother PR, performance does regress with j2 but is competitive with j4. This is expected and I think it's a reasonable trade off.

**Comment by jneira** [comment]
> > lgtm by pure trust wink, thanks!
> > hope the performance will not be worse in machines with few cores or with j2
> 
> Check the comment on the mother PR, performance does regress with j2 but is competitive with j4. This is expected and I think it's a reasonable trade off.

thanks for the reference,it seems the loss is reasonable, will complain if it is not as i have to live with 2 cores in my main dev laptop :stuck_out_tongue_closed_eyes:

**Comment by pepeiborra** [comment]
Let's not merge this just yet

**Pull request merged**
