### PR TITLE
hls-cabal-plugin: refactor context search to use `readFields`

### PR DESCRIPTION
**Pull request by fendor**
Replace the more brittle parser with cabal's `readFields`.

Ready for review :)

### CODE REVIEW

**Review by soulomoon — APPROVED** [review]
look good to me, very interesting idea!

**Comment by soulomoon** [comment]
Why is the test not running

**Comment by fendor** [comment]
Hm, I am also confused. Perhaps all my force pushing messed up the CI :)

**Comment by soulomoon** [comment]
Will it help with https://github.com/haskell/haskell-language-server/issues/3333

**Comment by fendor** [comment]
No, this tries to fix some bugs in the cabal file completions that I encountered while dogfooding the plugin. This does not affect the tests at all.

The tests are flaky, for the same reason hlint tests are/were flaky, afaict.

**Pull request merged**
