### PR TITLE
Fix #723 (Instance declarations in hs-boot files result in GHC errors)

### LINKED ISSUE #723: Instance declarations in hs-boot files result in GHC errors
Hi, I've come across this issue where any hs-boot file containing instance 
declarations results in the following error on the module:

```
File:     /home/ben/dev/ghcide_boot_file/src/X.hs-boot
Hidden:   no
Range:    1:1-2:1
Source:   compile
Severity: DsError
Message: 
  Compilation Issue
  lookup_final_id

  $fxShowY
  Call stack:
  CallStack (from HasCallStack):
  callStackDoc, called at compiler/utils/Outputable.hs:1159:37 in ghc:Outputable
  pprPanic, called at compiler/main/TidyPgm.hs:201:12 in ghc:TidyPgm
  Please report this bug to the compiler authors.
```

This causes any modules dependent on the hs-boot module to also fail.

For reference:
- `X.hs-boot`
```hs
module X (Y) where

data Y

instance Show Y
instance Eq Y
```

- `X.hs`
```hs
module X (Y) where

data Y = Y
  deriving (Show, Eq)
```

### PR DESCRIPTION
**Pull request by nitros12**
Hi, I've put together a fix for #723. 

The core of it is just using `mkBootModDetailsTc` instead of `tidyProgram` on boot files.

### CODE REVIEW

**Comment by pepeiborra** [comment]
how do we know that this works? Can we have a test?

**Comment by nitros12** [comment]
I've updated the boot test to include an instance declaration, is this okay?

**Comment by pepeiborra** [comment]
> I've updated the boot test to include an instance declaration, is this okay?

Did you check that the extended test fails without your fix?

**Comment by nitros12** [comment]
Turns out the error only presented itself when template haskell was enabled in the module with a boot file, the test now correctly fails on master and passes with this PR.

**Review by pepeiborra — COMMENTED** [review]
Looks good, thanks!

**Review by pepeiborra — APPROVED** [review]

**Pull request merged**
