### PR TITLE
Allow hole filling to deal with recursion

### PR DESCRIPTION
**Pull request by isovector**
@TOTBWF and I are back with more! This PR enhances the "attempt to fill hole" code action, allowing it to implement self-recursive functions. The generated code ensures recursion occurs only on structurally-smaller values, and preserves the positional ordering of homomorphically destructed arguments.

It's clever enough to implement `foldr`:

foldr

and nontrivial functor instances:

tree

### CODE REVIEW

**Comment by isovector** [comment]
Realized there's more infrastructure work I want to do here before merging. Can't figure out how to turn it into a draft PR, sorry.

**Comment by alanz** [comment]
I made it a draft, there was a thing on the top right, near where you add reviewers. It looks like plain text, but is clickable

**Comment by isovector** [comment]
@WorldSEnder would love to have you on board! Feel free to reach out to me (fpslack: isovector, email: sandy@sandymaguire.me) if you're interested in helping.

**Comment by isovector** [comment]
No longer WIP, and tests are green. This is mostly tactics-internal changes, though I'd appreciate a review on the changes in `plugins/tactics/src/Ide/Plugin/Tactic/GHC.hs ` relating to CPP. @alanz @wz1000

**Review by jneira — APPROVED** [review]
I dont know the tactic plugin code enough to do a proper review but trusting yours :smiley:

**Pull request merged**
