### PR TITLE
Retrieve Type from typecheck result for type lenses

### LINKED ISSUE #1468: CodeLens to add type signature inserts invalid type signature
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.0.0.0 (GHC: 8.10.3) (PATH: /home/berberman/.cabal/store/ghc-8.10.3/haskell-language-server-1.0.0.0-c7859e8f45ef6bd2fac7adc65982f4e497ee3c40299bcc89c5915aaa0534ebc3/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          Not found
ghc:            8.10.3
```
Which lsp-client do you use:
vscode

### Steps to reproduce

Create a module with functions that lead to ambiguity:

```haskell
module Test where

head = 233

(+) = undefined
```

### Expected behaviour

```haskell
module Test where

head :: Integer
head = 233

(+) :: a
(+) = undefined

```

### Actual behaviour

Type signatures are qualified with the module name, which are invalid.

```haskell
module Test where

Test.head :: Integer
head = 233

(Test.+) :: a
(+) = undefined
```

### PR DESCRIPTION
**Pull request by berberman**
Closes #1468 and #622

Parsing error messages from GHC would be tricky, so let's render signatures by ourselves, using information from typecheck. I'll add tests later.

### CODE REVIEW

**Comment by pepeiborra** [comment]
Can we have tests for non trivial things like: 

1. Polymorphic types
2. Rank-n types and other types with `forall`
2. Types with identifiers out of scope
3. Types with type operators
4. Types with promoted constructors and literals


We know that GHC error messages can handle all of the above, by definition, but we need to make sure that the solution in this PR can as well.

**Comment by berberman** [comment]
Is it a new non-deterministic failure?
```
boot-def-test: FAIL (0.92s)
  test\\exe\\Main.hs:3226:
  number of definitions
  expected: 1
   but got: 0
```

**Comment by Ailrun** [comment]
Yeah, it looks so...

**Comment by berberman** [comment]
This PR is ready for review.

**Pull request closed without merging**
