### PR TITLE
Add support for Fourmolu 0.14.0.0

### PR DESCRIPTION
**Pull request by brandonchinn178**
This was just released: https://github.com/fourmolu/fourmolu/releases/tag/v0.14.0.0

Also includes some minor refactoring. I think it should be pretty uncontroversial, but if not, I can break out into a separate PR

### CODE REVIEW

**Review by michaelpj — APPROVED** [review]
Looks fine to me.

**Comment by michaelpj** [comment]
You need to bump the `index-state` in `cabal.project`. I'm curious, did this build locally for you?

**Comment by brandonchinn178** [comment]
> You need to bump the `index-state` in `cabal.project`. I'm curious, did this build locally for you?

Nope 😄 Just pushed without testing. Sorry, just tested and it should work now

**Comment by michaelpj** [comment]
I wondered but I didn't think you could have done the refactoring like that :joy:

**Comment by brandonchinn178** [comment]
Just made good guesses in the refactor? 😂 

Anyway, the test failures are unrelated. The Nix failure does seem relevant 
```
       > Setup: Encountered missing or private dependencies:
       > fourmolu >=0.14 && <0.15
```
but I'm not sure how to update the Nix files

**Comment by July541** [comment]
I'm thinking is it possible to separate nix stuffs from the hls repo🤔️

**Comment by michaelpj** [comment]
That's why the check is not required :)

**Pull request merged**
