### PR TITLE
Don't run hlint on testdata directories

### LINKED ISSUE #3900: CI: Hlint should not lint test data files.
Current Hlint in CI is linting files that should not be lint, and report bug and warning on test data.
most testdata is in `test/testdata` for each sub project.
We can easily turn them off by using:
`hlint ./ --ignore-glob="**test/testdata/*.hs"`

### PR DESCRIPTION
**Pull request by fendor**
closes #3900

### CODE REVIEW

**Comment by fendor** [comment]
@soulomoon Does this look good?

**Comment by soulomoon** [comment]
Wired, It is still there,

**Comment by soulomoon** [comment]
weird, it is still there, take a look at https://github.com/haskell/haskell-language-server/actions/runs/7206841824/job/19632462805?pr=3901#step:4:133.

**Comment by soulomoon** [comment]
perhaps it is some kind of HLint bug?

**Comment by fendor** [comment]
Hm, maybe it only accepts the `ignore-glob` param once?

**Comment by fendor** [comment]
No, no idea, can't reproduce locally.

**Comment by soulomoon** [comment]
May be we can bumbup the version as in https://github.com/rwe/actions-hlint-setup
```
name: lint
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.1.6'

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v1
      with:
        path: src/
        fail-on: warning
```

**Comment by fendor** [comment]
No, ignore-glob is seemingly only recognised by the cli. But on CI, not even that seems to be true.

**Comment by fendor** [comment]
I did it! It looks like `@actions/exec` does something funky with cmd arguments that contain quotes. I don't really know what's going, but I am suspecting that a shell is acting up, maybe escaping or resolving `*`?

**Comment by soulomoon** [comment]
LGTM, it seems checks for the testdata's files is gone.

**Comment by michaelpj** [comment]
What's this file doing, then? Isn't it exactly what we want? https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-semantic-tokens-plugin/.hlint.yaml

**Comment by fendor** [comment]
Yeah that looks good, I was looking for a different option, apparently. Will update the PR and delete the respective .hlint.yaml files.

**Review by michaelpj — APPROVED** [review]

**Comment by fendor** [comment]
Doesn't seem to be working yet

**Comment by soulomoon** [comment]
Since none of us can repro locally, I tend to think there is a Github action CI up stream bug.

**Comment by fendor** [comment]
Adding 
```
- ignore: { "within": '**/testdata/**' }
- ignore: { "within": '**/test/data/**' }
```
does not work for me locally either. That may be a hlint bug worth discussing upstream.

**Comment by soulomoon** [comment]
create a ticket to hlint #1552

**Comment by soulomoon** [comment]
I realize, It might be a conlict between `--git` and `--ignore-glob`  @fendor

**Comment by soulomoon** [comment]
I found the source, this pull request https://github.com/ndmitchell/hlint/issues/1552 should fix the ignore-glob problem.

**Review by soulomoon — COMMENTED** [review]
looking good, the problem can be fixed with it once the hlint support ignore glob with arg `--git`

**Comment by michaelpj** [comment]
This seems semantically correct even if there's a hlint problem, so let's merge it anyway.

**Review by soulomoon — APPROVED** [review]

**Pull request merged**
