### PR TITLE
Remove hspec-expectations

### PR DESCRIPTION
**Pull request by bubba**
Use @? and @?= instead, since they give easier to read error messages. The `shouldX` functions all just end up dumping the Show instance of a HSpecFailure or what have you which is hard to read. It also doesn't look like hspec-expectations is that actively maintained anymore

### CODE REVIEW

**Comment by jneira** [comment]
I think it was added for legibility reasons, continuing hie style. Iirc @alanz (ad @fendor?) did prefer to not use operators.
I am slightly inclined to `shouldBe` but not stronger opinion about

**Comment by fendor** [comment]
According to https://hackage.haskell.org/package/hspec-expectations-0.8.2/docs/Test-Hspec-Expectations.html#v:shouldBe

```haskell
shouldBe :: (HasCallStack, Show a, Eq a) => a -> a -> Expectation
actual `shouldBe` expected = actual @?= expected
```
I am confused why this displays differently?

I am the one most opposed to operators such as `@?=`, `@=?` and `@?`, as they all look the same for me at the first sight.

**Comment by alanz** [comment]
I have no strong preference on this, but generally prefer idiomatic coding. So if we are using tasty, it makes.sense to use the tasty operators.

**Comment by bubba** [comment]
> According to https://hackage.haskell.org/package/hspec-expectations-0.8.2/docs/Test-Hspec-Expectations.html#v:shouldBe
> 
> 
> 
> ```haskell
> 
> shouldBe :: (HasCallStack, Show a, Eq a) => a -> a -> Expectation
> 
> actual `shouldBe` expected = actual @?= expected
> 
> ```
> 
> I am confused why this displays differently?
> 
> 
> 
> I am the one most opposed to operators such as `@?=`, `@=?` and `@?`, as they all look the same for me at the first sight.

It's using `@?=` from `Test.HUnit`, not `Test.Tasty.HUnit`, which unfortunately doesn't get caught by Tasty and pretty printed. Converting it was pretty simple, since we were only using a handful of the combinators. The vast majority of assertions were of the form `shouldBe`

**Comment by fendor** [comment]
I see. I still very much dislike these operators and like avoid them.
However, I also see the argument for more idiomatic code. We can't get Tasty to catch and display correctly?

**Pull request merged**
