### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by Ailrun**
To include OS

### CODE REVIEW

**Review by jneira — APPROVED** [review]
Wow, that was fast, many thanks

**Comment by Ailrun** [comment]
@jneira Unfortunately, it looks like CI skipping still does not work... Maybe we are skipping things too early?

**Comment by Ailrun** [comment]
Anyway, I will merge this manually for now

**Comment by jneira** [comment]
mmm in the report I see 12/16 successful checks and there are 4 circleci unfinished jobs (they are not skipped only gha ones)

**Comment by Ailrun** [comment]
@jneira The report says that, but the GitHub branch rule does not work with that 12 successful checks.

**Comment by jneira** [comment]
mmm after circleci jobs has finished all checks are green and I think you had been able to merge it
as commented above circleci jobs are not affected by any skip rule so they are executed and handled like in any other pr (so you can't merge if they fail or are unfinished)

**Pull request merged**
