### PR TITLE
Use object code for TH+UnboxedTuples/Sums

### PR DESCRIPTION
**Pull request by wz1000**
1. Modules that use TH themselves but aren't depended on by anything that uses TH don't need to be compiled
2. Any module that needs to be compiled and uses unboxed sums/tuples needs to be compiled using object code
3. Any module that is depended on by anything that uses object code needs to be compiled using object code.

Logic from https://gitlab.haskell.org/ghc/ghc/-/blob/963e1e9aedf0ee70d4e817640ec9845ed00ce0cf/compiler/GHC/Driver/Make.hs#L2268

### CODE REVIEW

**Comment by michaelpj** [comment]
FYI you might be interested in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4412, which will hopefully get into 9.2 and should make this work without object code. We actually use a GHC with that patch applied at work precisely so that HLS works with unboxed tuples and sums :sweat_smile:

**Comment by hamishmack** [comment]
We have back ported the patch to 8.10.3 (and newer) and [include it in haskell.nix](https://github.com/input-output-hk/haskell.nix/blob/master/overlays/patches/ghc/ghc-8.10.3-ubxt.patch).  Any haskell.nix project that uses ghc 8.10 and has a shell created with `shellFor { tools = { haskell-language-server = "latest"; }; }` should use it correctly.

If you use nix and want to try it out while developing `haskell-language-server` itself, I have included a suitable `.nix` file in #1386.

**Comment by wz1000** [comment]
That is good to hear, but an important question remains. Is it possible to detect the presence of this patch at compile time? We would like to merge this PR to properly support users of unpatched GHCs. However, it may have some negative impact in terms of performance, linker issues etc. for users of patched GHCs.

**Comment by wz1000** [comment]
I suppose it might be OK if it were possible to detect it at runtime either, but a configuration option seems less than ideal

**Comment by hamishmack** [comment]
I'm not how we could detect the patch in ghc 8.10 (@angerman or @luite might have an idea).  We could set a flag when building `haskell-language-server` if that helps.  We have a [good place to put it](https://github.com/input-output-hk/haskell.nix/blob/master/overlays/hackage-quirks.nix#L68-L74).

**Comment by hamishmack** [comment]
A cabal flag that is

**Comment by pepeiborra** [comment]
You could change the version number to e.g. 8.10.13, or 8.100.3

**Comment by hamishmack** [comment]
> You could change the version number to e.g. 8.10.13, or 8.100.3

That might break other things that expect 8.10.3.

Perhaps `haskell-language-server` could check for version `9.2` (when we expect the unboxed tuple patch to lade in GHC).  If it sees that version it could assume unboxed tuple support is present and that using object code is unnecessary.

Then in haskell.nix we could include a patch for `haskell-language-server` that would just change that threshold from `9.2` to `8.10.3` (but it might be cleaner if there was a `ghc-has-unboxed-tuples-patch` cabal flag it could set instead).

**Comment by wz1000** [comment]
@michaelpj @hamishmack I've added a cabal flag called `ghc-patched-unboxed-bytecode` (quite a mouthful, I know). It would be great if you guys could add it to `haskell.nix` or whatever after adding a configuration to CI testing it. You don't need to test everything, just `--pattern=TemplateHaskell` should be enough.

**Review by pepeiborra — APPROVED** [review]
It's a bit bad that we are forced to do a whole project analysis in `NeedsCompilation`, which is used by other core rules like `GetModIface`. But that's already the status quo, this PR doesn't make it materially worse.

**Comment by wz1000** [comment]
I don't see a way around the whole project analysis, even GHC executes this logic in the "downsweep" step which is a whole project analysis starting from the highest nodes in the module graph and proceeding down to the leaves.

**Pull request merged**
