### PR TITLE
ghcide - enable ApplicativeDo everywhere

### PR DESCRIPTION
**Pull request by pepeiborra**
Shake has applicative parallelism for rules, meaning that all "contiguous" (that is, not separated by `join` or `bind`) calls to `apply` will evaluate in parallel (but note that the rest of the `Action` logic still evaluated sequentially, so this doesn't replace `parallel`).

ApplicativeDo created type errors in some modules, disabled locally with NoApplicativeDo

### CODE REVIEW

**Comment by wz1000** [comment]
What sort of errors does `ApplicativeDo` lead to? Why is `NoApplicativeDo` every necessary?

**Comment by pepeiborra** [comment]
```

src/Development/IDE/Core/Actions.hs:92:6: error:
    • Couldn't match expected type ‘a1’
                  with actual type ‘(HieASTs a2, HieDb,
                                     Data.Map.Internal.Map ModuleName NormalizedFilePath,
                                     PositionMapping, Position)’
        because type variable ‘a2’ would escape its scope
      This (rigid, skolem) type variable is bound by
        a pattern with constructor:
          HAR :: forall a.
                 Module
                 -> HieASTs a
                 -> RefMap a
                 -> Data.Map.Internal.Map Name [RealSrcSpan]
                 -> HieKind a
                 -> HieAstResult,
        in a pattern binding in
             a 'do' block
        at src/Development/IDE/Core/Actions.hs:90:6-19
    • In the second argument of ‘($)’, namely
        ‘do ide <- ask
            opts <- liftIO $ getIdeOptionsIO ide
            (HAR _ hf _ _ _, mapping) <- useE GetHieAst file
            (ImportMap imports, _) <- useE GetImportMap file
            !pos' <- MaybeT (pure $ fromCurrentPosition mapping pos)
            hiedb <- lift $ asks hiedb
            dbWriter <- lift $ asks hiedbWriter
            toCurrentLocations mapping
              <$>
                AtPoint.gotoDefinition
                  hiedb (lookupMod dbWriter) opts imports hf pos'’
      In the expression:
        runMaybeT
          $ do ide <- ask
               opts <- liftIO $ getIdeOptionsIO ide
               (HAR _ hf _ _ _, mapping) <- useE GetHieAst file
               (ImportMap imports, _) <- useE GetImportMap file
               !pos' <- MaybeT (pure $ fromCurrentPosition mapping pos)
               hiedb <- lift $ asks hiedb
               dbWriter <- lift $ asks hiedbWriter
               toCurrentLocations mapping
                 <$>
                   AtPoint.gotoDefinition
                     hiedb (lookupMod dbWriter) opts imports hf pos'
      In an equation for ‘getDefinition’:
          getDefinition file pos
            = runMaybeT
                $ do ide <- ask
                     opts <- liftIO $ getIdeOptionsIO ide
                     (HAR _ hf _ _ _, mapping) <- useE GetHieAst file
                     (ImportMap imports, _) <- useE GetImportMap file
                     !pos' <- MaybeT (pure $ fromCurrentPosition mapping pos)
                     hiedb <- lift $ asks hiedb
                     dbWriter <- lift $ asks hiedbWriter
                     toCurrentLocations mapping
                       <$>
                         AtPoint.gotoDefinition
                           hiedb (lookupMod dbWriter) opts imports hf pos'
    • Relevant bindings include
        hf :: HieASTs a2
          (bound at src/Development/IDE/Core/Actions.hs:90:12)
   |
92 |     !pos' <- MaybeT (pure $ fromCurrentPosition mapping pos)
   |      ^^^^

src/Development/IDE/Core/Actions.hs:95:24: error:
    • Couldn't match expected type ‘PositionMapping’
                  with actual type ‘PositionMapping’
    • In the first argument of ‘toCurrentLocations’, namely ‘mapping’
      In the first argument of ‘(<$>)’, namely
        ‘toCurrentLocations mapping’
      In a stmt of a 'do' block:
        toCurrentLocations mapping
          <$>
            AtPoint.gotoDefinition
              hiedb (lookupMod dbWriter) opts imports hf pos'
   |
95 |     toCurrentLocations mapping <$> AtPoint.gotoDefinition hiedb (lookupMod dbWriter) opts imports hf pos'
   |                        ^^^^^^^

src/Development/IDE/Core/Actions.hs:95:59: error:
    • Couldn't match expected type ‘HieDb’ with actual type ‘HieDb’
    • In the first argument of ‘AtPoint.gotoDefinition’, namely ‘hiedb’
      In the second argument of ‘(<$>)’, namely
        ‘AtPoint.gotoDefinition
           hiedb (lookupMod dbWriter) opts imports hf pos'’
      In a stmt of a 'do' block:
        toCurrentLocations mapping
          <$>
            AtPoint.gotoDefinition
              hiedb (lookupMod dbWriter) opts imports hf pos'
   |
95 |     toCurrentLocations mapping <$> AtPoint.gotoDefinition hiedb (lookupMod dbWriter) opts imports hf pos'
   |                                                           ^^^^^

src/Development/IDE/Core/Actions.hs:95:91: error:
    • Couldn't match expected type ‘Data.Map.Internal.Map
                                      ModuleName NormalizedFilePath’
                  with actual type ‘Data.Map.Internal.Map
                                      ModuleName NormalizedFilePath’
    • In the fourth argument of ‘AtPoint.gotoDefinition’, namely
        ‘imports’
      In the second argument of ‘(<$>)’, namely
        ‘AtPoint.gotoDefinition
           hiedb (lookupMod dbWriter) opts imports hf pos'’
      In a stmt of a 'do' block:
        toCurrentLocations mapping
          <$>
            AtPoint.gotoDefinition
              hiedb (lookupMod dbWriter) opts imports hf pos'
   |
95 |     toCurrentLocations mapping <$> AtPoint.gotoDefinition hiedb (lookupMod dbWriter) opts imports hf pos'
   |                                                                                           ^^^^^^^

src/Development/IDE/Core/Actions.hs:95:99: error:
    • Couldn't match expected type ‘HieASTs a0’
                  with actual type ‘HieASTs a’
    • In the fifth argument of ‘AtPoint.gotoDefinition’, namely ‘hf’
      In the second argument of ‘(<$>)’, namely
        ‘AtPoint.gotoDefinition
           hiedb (lookupMod dbWriter) opts imports hf pos'’
      In a stmt of a 'do' block:
        toCurrentLocations mapping
          <$>
            AtPoint.gotoDefinition
              hiedb (lookupMod dbWriter) opts imports hf pos'
    • Relevant bindings include
        hf :: HieASTs a
          (bound at src/Development/IDE/Core/Actions.hs:90:12)
   |
95 |     toCurrentLocations mapping <$> AtPoint.gotoDefinition hiedb (lookupMod dbWriter) opts imports hf pos'
   |                                                                                                   ^^

src/Development/IDE/Core/Actions.hs:95:102: error:
    • Couldn't match expected type ‘Position’
                  with actual type ‘Position’
    • In the sixth argument of ‘AtPoint.gotoDefinition’, namely ‘pos'’
      In the second argument of ‘(<$>)’, namely
        ‘AtPoint.gotoDefinition
           hiedb (lookupMod dbWriter) opts imports hf pos'’
      In a stmt of a 'do' block:
        toCurrentLocations mapping
          <$>
            AtPoint.gotoDefinition
              hiedb (lookupMod dbWriter) opts imports hf pos'
   |
95 |     toCurrentLocations mapping <$> AtPoint.gotoDefinition hiedb (lookupMod dbWriter) opts imports hf pos'
   |                                                                                                      ^^^^
cabal: Failed to build ghcide-1.1.0.0 (which is required by
```

**Comment by wz1000** [comment]
The "could not match "Position" with "Position"` style errors seem very suspicious. Do you know why they happen? Is there a GHC bug report?

**Comment by pepeiborra** [comment]
I have no idea. I have filled ApplicativeDo bugs in the past. Didn't work out.

**Review by wz1000 — APPROVED** [review]

**Pull request merged**
