### PR TITLE
Prepare hls hlint plugin 0.2.0

### PR DESCRIPTION
**Pull request by jneira**
* Rebased onto #1289
* Progress towards #1287

### CODE REVIEW

**Comment by jneira** [comment]
The build is failing for ghc-8.6 with

```
Failed to build mmorph-1.1.4.
Build log (
/home/runner/.cabal/logs/ghc-8.6.4/mmorph-1.1.4-15531b2150bdb70455c97dbadcc62c6adb5af02d44a217c6b4d71a41948a0134.log
):
Configuring library for mmorph-1.1.4..
cabal: Failed to build mmorph-1.1.4 (which is required by test:func-test from
hls-0.9.0.0 and test:wrapper-test from hls-0.9.0.0). See the build log above
for details.

Preprocessing library for mmorph-1.1.4..
Building library for mmorph-1.1.4..
[1 of 2] Compiling Control.Monad.Morph ( src/Control/Monad/Morph.hs, dist/build/Control/Monad/Morph.o )

src/Control/Monad/Trans/Compose.hs:60:7: error:
    Not in scope: type constructor or class ‘MonadFail’
   |
60 |     , MonadFail
   |       ^^^^^^^^^
```

No  sure if due the new hackage index or ghc-exactprint, investigating :worried:

**Comment by jneira** [comment]
The package mmorph has a recent suspicious revision: https://hackage.haskell.org/package/mmorph-1.1.4/revisions/ bumping out the base lower bound

**Comment by jneira** [comment]
@Ailrun @pepeiborra we need some approval to continue with the release :slightly_smiling_face:

**Review by Ailrun — APPROVED** [review]
Oops, sorry, I thought I approved this.

**Pull request merged**
