### PR TITLE
Add hlint tests over cpp, extensions and ignore hints 

### PR DESCRIPTION
**Pull request by jneira**
* As a previous step to #635, to compare behaviour with master and let clear what will be fixed (or broken)

### CODE REVIEW

**Comment by jneira** [comment]
stack build in circleci is ignoring the `expectFailBecause` and reports tests as failed, but cabal does not, weird

**Comment by jneira** [comment]
@bubba maybe you could help me with that :slightly_smiling_face: 
I want to "force" that a session timeout produces an assertion error, for that i would need to catch the `Timeout a` exception and call `assertFailure` in that case

But... `Session a` has no instance for MonadError (nor other suitable error handling class) so i have to implement:

```
instance MonadError LSPTest.SessionException LSPTest.Session
```

Would be any way to avoid that orphan instance?
In lsp test the catchError is done over the underlying Conduit type.

**Comment by jneira** [comment]
@bubba never mind, i finally i am gonna catch the exception at `runSession` level, that is `IO a` so i can use `Control.Exception` directly something like (not tested):

```haskell
failIfSessionTimeout :: IO a -> IO a
failIfSessionTimeout action = action `catch` errorHandler
    where errorHandler :: Test.SessionException -> IO a
          errorHandler e@(Test.Timeout _) = assertFailure $ show e
          errorHandler e = throwIO e
```

let's see if it works... :thinking:

**Comment by jneira** [comment]
It made work stack tests in circleci, but why does it work in cabal without handling explicitly `SessionException`? :thinking:

**Review by alanz — APPROVED** [review]
I don't see anything obviously a problem

**Comment by bubba** [comment]
@jneira yeah that code snippet is what I would do, catch on the specific `Timeout` exception. I bet you though the failure is to do with parallelism though/the jobs `-j` flag. The circleCI jobs might not be telling hspec to run the tests sequentially?

**Comment by jneira** [comment]
@bubba `-j1` is passed to the test suite:

https://github.com/haskell/haskell-language-server/blob/bf8ce830710bd49f6dcdbd30e944553e85ccdb97/.circleci/config.yml#L67-L73

However, being able to catch the exception in `Session` monad would be nice, as we could add it in the `waitForDiagnostics` itself, and all tests would have that behaviour at once.
Could we add a MonadError instance in lsp-test? I guess it could be done delegating `tryError` and `catchError` to the undelying `ConduitParser` data type.

**Pull request merged**
