### PR TITLE
Bump to 2.4.0.1

### PR DESCRIPTION
**Pull request by hasufell**
## Release checklist

- [x] check ghcup supports new GHC releases if any
- [x] set the supported GHCs in workflow file `.github/workflows/release.yaml`
  - There is currently a list of GHC versions for each major platform. Search for `ghc: [` to find all lists.
  - Look for `TODO:` to find locations that require extra care for GHC versions.
- [ ] check all plugins still work if release includes code changes
- [x] bump package versions in all `*.cabal` files (same version as hls)
  - HLS uses lockstep versioning. The core packages and all plugins use the same version number, and only support exactly this version.
    - Exceptions:
      - `hie-compat` requires no automatic version bump.
      - `shake-bench` is an internal testing tool, not exposed to the outside world. Thus, no version bump required for releases.
  - For updating cabal files, the following script can be used:
    - ```sh
      # Update all `version:` fields
      sed -ri "s/^version:( +)2.2.0.0/version:\12.3.0.0/" **/*.cabal
      # Update all constraints expected to be in the form `== <version>`.
      # We usually don't force an exact version, so this is relatively unambiguous.
      # We could introduce some more ad-hoc parsing, if there is still ambiguity.
      sed -ri "s/== 2.2.0.0/== 2.3.0.0/" **/*.cabal
      ```
    - It still requires manual verification and review
- [x] generate and update changelog
  - Generate a ChangeLog via `./GenChangelogs.hs <api-key> <tag>`
    - `<tag>` is the git tag you want to generate the ChangeLog from.
    - `<api-key>` is a github access key: https://github.com/settings/tokens
- [x] create release branch as `wip/<version>`
  - `git switch -c wip/<version>`
- [x] create release tag as `<version>`
  - `git tag <version>`
- [x] trigger release pipeline by pushing the tag
  - this creates a draft release
  - `git push <remote> <version>`
- [ ] run `sh scripts/release/download-gh-artifacts.sh <version> <your-gpg-email>`
  - downloads artifacts to `gh-release-artifacts/haskell-language-server-<version>/`
  - also downloads FreeBSD bindist from circle CI
  - adds signatures
- [ ] upload artifacts to downloads.haskell.org from `gh-release-artifacts/haskell-language-server-<version>/`
  - You require sftp access, contact wz1000, bgamari or chreekat
  - `cd gh-release-artifacts/haskell-language-server-<version>`
  - `SIGNING_KEY=... ../../release/upload.sh upload`
    - Your SIGNING_KEY can be obtained with `gpg --list-secret-keys --keyid-format=long`
  - Afterwards, the artifacts are available at: `https://downloads.haskell.org/~hls/haskell-language-server-<version>/`
  - Run `SIGNING_KEY=... ../../release/upload.sh purge_all` to remove CDN caches
- [ ] create PR to [ghcup-metadata](https://github.com/haskell/ghcup-metadata)
  - [ ] update `ghcup-0.0.7.yaml` and `ghcup-vanilla-0.0.7.yaml`
    - can use `sh scripts/release/create-yaml-snippet.sh <version>` to generate a snippet that can be manually inserted into the yaml files
  - [ ] update `hls-metadata-0.0.1.json`
    - utilize `cabal run ghcup-gen -- generate-hls-ghcs -f ghcup-0.0.7.yaml --format json --stdout` in the root of ghcup-metadata repository
  - Be sure to mark the correct latest version and add the 'recommended' tag to the latest release.
- [ ] get sign-off on release
  - from wz1000, michealpj, maerwald and fendor
- [ ] publish release on github
- [ ] upload hackage packages
  - requires credentials
- [ ] update https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html#current-ghc-version-support-status
- [ ] Supported tools table needs to be updated:
  - https://www.haskell.org/ghcup/install/#supported-platforms
  - https://github.com/haskell/ghcup-hs/blob/master/docs/install.md#supported-platforms
  - https://github.com/haskell/ghcup-metadata/blob/44c6e2b5d0fcae15abeffff03e87544edf76dd7a/ghcup-gen/Main.hs#L67
- [ ] post release on discourse and reddit
- [ ] merge release PR to master or forward port relevant changes

### CODE REVIEW

**Comment by hasufell** [comment]
https://github.com/haskell/haskell-language-server/actions/runs/6833184583

**Comment by hasufell** [comment]
It seems the head.hackage hack is busted and 9.8.x fails to build on all platforms.

**Comment by michaelpj** [comment]
Same issue as [this](https://github.com/haskell/haskell-language-server/issues/3861), I guess? head.hackage doesn't work with index-state?

What's the reason for doing a release btw? Haven't seen any discussion?

**Comment by fendor** [comment]
This is a binary release for the fresh release of GHC `9.4.8`.

**Comment by hasufell** [comment]
> This is a binary release for the fresh release of GHC `9.4.8`.

Yes, but someone added support for 9.8.1 through head.hackage. I'm not sure that's really a good idea overall. Those are partially unapproved patches.

**Comment by hasufell** [comment]
It was @wz1000

https://github.com/haskell/haskell-language-server/commit/5580ffce19b469a7104ac1702536f43ee8718f47#diff-b8ed06757045fac949c89f2139a862498ad2b6d1f82c61a31e7c91d6cf0eaa70

**Comment by wz1000** [comment]
Please don't drop 9.8.1 support, head.hackage should be working now.

**Comment by benz0li** [comment]
> Please don't drop 9.8.1 support, head.hackage should be working now.

Running `cabal update` works, but building HLS 2.4.0.0 fails. Cross reference: https://gitlab.haskell.org/ghc/head.hackage/-/issues/94#note_535255

---

Unless there is a **proper** fix for head.hackage, building HLS 2.4.0.0 with GHC 9.8 will no longer work.

**Comment by wz1000** [comment]
We don't depend on head.hackage anymore, so if you rebase the build should work for 9.8.1

**Comment by wz1000** [comment]
I think this should be a major bump now

**Comment by hasufell** [comment]
> I think this should be a major bump now

Can we avoid that?

**Comment by wz1000** [comment]
No, the lsp version we depend on had breaking changes.

**Comment by hasufell** [comment]
> No, the lsp version we depend on had breaking changes.

I'm not sure I understand. Why can't we rebase on the previous release and just backport the removal of head.hackage without any further changes?

**Comment by benz0li** [comment]
> Why can't we rebase on the previous release and just backport the removal of head.hackage without any further changes?

It will not build with GHC 9.8.

**Comment by hasufell** [comment]
> > Why can't we rebase on the previous release and just backport the removal of head.hackage without any further changes?
> 
> It will not build with GHC 9.8.

So the lsp version didn't backport the GHC 9.8 compatibility patch to the older branch?

**Comment by benz0li** [comment]
> > > Why can't we rebase on the previous release and just backport the removal of head.hackage without any further changes?
> > 
> > 
> > It will not build with GHC 9.8.
> 
> So the lsp version didn't backport the GHC 9.8 compatibility patch to the older branch?

I never said that.

See https://github.com/haskell/haskell-language-server/issues/3861#issue-1983492217 for instructions on how to reproduce.  
👉 Execute including `&& export ARTIFACT`, soley patch `cabal.project`, `cabal update` and try `emake hls-ghc`.

If I remember correctly, `th-abstraction-0.5.0.0` does not build.

**Comment by hasufell** [comment]
I don't have time at the moment to pursue this release.

**Pull request closed without merging**
