### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by Deltaspace0**
Fixed spelling errors in comments, strings and variables.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3325"></a>

### CODE REVIEW

**Review by kokobd — APPROVED** [review]
LGTM for code-range and haddock-comments. Brilliant!

**Review by July541 — APPROVED** [review]
Many thanks!

**Comment by July541** [comment]
I think we should keep the changelog as is.

**Review by isovector — APPROVED** [review]

**Review by konn — APPROVED** [review]
Thank you for correcting my typo in Splice Plugin! 👍

**Pull request merged**
