### PR TITLE
Remove ghcide-test-utils as a separate package

### PR DESCRIPTION
**Pull request by michaelpj**
Even stack now supports public sub-library dependencies, let's have one fewer weird package.

### CODE REVIEW

**Comment by michaelpj** [comment]
You know what, I'm going to do `hls-test-utils` too while I'm at it.

**Comment by michaelpj** [comment]
Oh, it looks like there hasn't actually been a release of stack with the new feature. Boo.

**Comment by michaelpj** [comment]
Looks like it's coming, but let's park this until then: https://github.com/commercialhaskell/stack/issues/6397

**Comment by michaelpj** [comment]
Okay, ready to review. I didn't do `hls-test-utils` as @fendor thought it was a good idea to keep it separate so `ghcide` can potentially depend on it.

**Review by soulomoon — APPROVED** [review]
LGTM

**Pull request merged**
