### PR TITLE
Wingman: Fix subsequent tactics

### LINKED ISSUE #2448: Wingman: TODO(sandy) error pops up after the first tactic
### Your environment

Which OS do you use:
Ubuntu 20.04.3 LTS

Which lsp-client do you use:
VS Code

Describe your project (alternative: link to the project):
It is a regular `stack` project which can be found [here](https://github.com/lsmor/advent-of-code-2021). Nothing really wierd, just a normal advent of code project with one executable per day.

stack snapshot: 18.6 -> GHC 8.10.7
HLS version: 1.5.1

### Steps to reproduce

write the following file and positionate the cursor on the underscore, then trigger the code action "Wingman: case split on d"

```haskell
module Main where

data Input = Input

example :: Input -> Input
example d = _


main :: IO ()
main = print "hello hls"
```

### Expected behaviour
It should complete the line `example d  = _` introducing `Input` constructor like `example Input = _d`. Some times, It works fine when I re-start `hls` but 8 out of 10 times it keeps failing.

### Actual behaviour
And error pops up `TODO(sandy)`

### Include debug information
This is the output when I set VS code extension setting to debug. (I've been unable to run `haskell-language-server-wrapper`)

<details>
<summary>
Debug output:
</summary>

```
2021-12-07 12:01:51.274203053 [ThreadId 4442] INFO hls:	finish: Wingman.getIdeDynflags.GetModSummaryWithoutTimestamps (took 0.00s)
2021-12-07 12:01:51.274730682 [ThreadId 4443] INFO hls:	finish: Wingman.judgementForHole.GetHieAst (took 0.00s)
2021-12-07 12:01:51.275544442 [ThreadId 4444] INFO hls:	finish: Wingman.judgementForHole.GetBindings (took 0.00s)
2021-12-07 12:01:51.275816949 [ThreadId 4445] INFO hls:	finish: Wingman.judgementForHole.TypeCheck (took 0.00s)
[Error - 12:01:51] Request workspace/executeCommand failed.
  Message: TODO(sandy)
  Code: -32603 
2021-12-07 12:01:51.276098968 [ThreadId 4446] INFO hls:	finish: Wingman.judgementForHole.GhcSessionDeps (took 0.00s)
2021-12-07 12:01:51.350012789 [ThreadId 4464] INFO hls:	finish: Pragmas.GetParsedModule (took 0.00s)
2021-12-07 12:01:51.350191098 [ThreadId 4467] INFO hls:	finish: retrie (took 0.00s)
2021-12-07 12:01:51.350225369 [ThreadId 4465] INFO hls:	finish: Wingman.getIdeDynflags.GetModSummaryWithoutTimestamps (took 0.00s)
```
</details>

### PR DESCRIPTION
**Pull request by isovector**
Fixes #2448 

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2479"></a>

### CODE REVIEW

**Comment by isovector** [comment]
This new test should pass if the bug is fixed.

@pepeiborra I added the changes you suggested in https://github.com/haskell/haskell-language-server/issues/2448#issuecomment-992233786, but they don't seem to fix the problem. How did you test it?

**Comment by pepeiborra** [comment]
Maybe I just got lucky :( - using the repro, the fix worked once. But I didn't double check, and it seems the problem is non deterministic.

**Comment by pepeiborra** [comment]
One super useful tool to debug this is Shake profiling. Enable it using the flag `--shake-profiling=/tmp/hls` or the env var `GHCIDE_BUILD_PROFILING=/tmp/hls` and you will get one html report for every build, telling you:

1. Which keys were marked as dirty before the build
2. Which keys were actually built
3. Which keys were visited *but not built* because the build system thought they were clean (no dependencies changed)

**Comment by pepeiborra** [comment]
FYI your test cannot pass, I just found a bug in `lsp-test` handling of commands that apply edits: it sends the `TextDocumentDidChange` notification before updating the version number in the VFS, which means that the IDE doesn't "see" the edit at all:

https://github.com/pepeiborra/lsp/blob/4df0a86e813a267add82a28f4a0c41b5aaacc85b/lsp-test/src/Language/LSP/Test/Session.hs#L373-L385

**Comment by pepeiborra** [comment]
The test passes for me locally after fixing the bug in lsp-test (https://github.com/haskell/lsp/pull/376) which suggests that it doesn't quite capture the bug identified in #2448 

My rebase: #2509

**Comment by pepeiborra** [comment]
I have been looking at this and I believe the issue is in this code:

https://github.com/haskell/haskell-language-server/blob/d7a745e9b5ae76a4bf4ee79a9fdf41cf6f1662bf/plugins/hls-tactics-plugin/src/Wingman/AbstractLSP/Types.hs#L122-L135

Embedding `NormalizedFilePath` values in LSP messages is unsupported and leads to unspecified behaviour due to the embedded hash. I don't remember the details, but see e.g. https://github.com/haskell/haskell-language-server/pull/1202 

Prior to https://github.com/haskell/haskell-language-server/commit/682386d1c97ff98463f2cac260a8fe7aab099ebd this unspecified behaviour caused no other observable issues than probably space leaks. Now it additionally creates stale values than never get refreshed.

**Comment by isovector** [comment]
Very odd. Thanks for continuing to dig in here, @pepeiborra.

**Comment by isovector** [comment]
Subsumed by #2580

**Pull request closed without merging**
