### PR TITLE
Update to new hls

### PR DESCRIPTION
**Pull request by alanz**
Based on https://github.com/wz1000/ghcide/tree/hls-2

### CODE REVIEW

**Comment by alanz** [comment]
ping @wz1000

**Comment by korayal** [comment]
I got excited and wanted to try this out on my nix build without waiting for the merge, but ended up with this error:

```
[20 of 48] Compiling Development.IDE.GHC.Orphans ( src/Development/IDE/GHC/Orphans.hs, dist/build/Development/IDE/GHC/Orphans.o )

src/Development/IDE/GHC/Orphans.hs:74:30: error:
    Not in scope: type constructor or class ‘IdentifierDetails’
   |
74 | instance NFData a => NFData (IdentifierDetails a) where
   |                              ^^^^^^^^^^^^^^^^^

src/Development/IDE/GHC/Orphans.hs:75:10: error:
    Not in scope: data constructor ‘IdentifierDetails’
   |
75 |     rnf (IdentifierDetails a b) = rnf a `seq` rnf (length b)
   |          ^^^^^^^^^^^^^^^^^
[27 of 48] Compiling Development.IDE.Types.Logger ( src/Development/IDE/Types/Logger.hs, dist/build/Development/IDE/Types/Logger.o )
```

**Comment by alanz** [comment]
@pepeiborra 

It seems @wz1000 introduced that NFData instance recently, in https://github.com/wz1000/ghcide/commit/7cee3422adb2b7f5fd96e3683c2952f5f59951be

I presume this would have been as a result of a compiler warning that the instance did not exist.

So the forward-compatible fix may be to simply remove the orphan instance.

**Comment by alanz** [comment]
Except I just did the experiment and do get 

```
src/Development/IDE/Core/RuleTypes.hs:89:36: error:
    • No instance for (NFData
                         (HieTypes.IdentifierDetails HieTypes.TypeIndex))
        arising from a use of ‘rnf’
    • In the second argument of ‘seq’, namely ‘rnf rm’
      In the expression: rnf hf `seq` rnf rm
      In an equation for ‘rnf’: rnf (HFR hf rm) = rnf hf `seq` rnf rm
   |
89 |     rnf (HFR hf rm) = rnf hf `seq` rnf rm
   |                                    ^^^^^^
cabal: Failed to build ghcide-0.2.0 (which is required by test:func-test from
```
The weird thing is that this built and installed for me yesterday.  Will investigate further.

**Comment by wz1000** [comment]
The orphans are defined here: https://github.com/wz1000/ghcide/commit/7cee3422adb2b7f5fd96e3683c2952f5f59951be#diff-f66e454f20222807df8695df1a79c8c6R74

I am in the middle of a complicated rebase, I will investigate once I'm done with that.

**Comment by alanz** [comment]
> Which GHC version is this?

8.8.3

**Comment by jneira** [comment]
The test suite is:
```
18 out of 253 tests failed (569.52s)
```
Full log [here](https://gist.github.com/jneira/51740f0b7510c3aa33f8889ba4aa9587)
Nothing too strange in failing tests so LGTM

**Pull request merged**
