### PR TITLE
ghcide: Update dependency on `hls-plugin-api`

### PR DESCRIPTION
**Pull request by hololeap**
2204a16bfbbdd3f0887cdfdab4b86cbd63ab051a broke backward compatibility between `ghcide` and `hls-plugin-api`

In addition to this PR, the following will need to be revised on hackage:

Versions `1.4.1.0` `1.4.2.0` `1.4.2.1` `1.4.2.2` `1.4.2.3` will need
`hls-plugin-api ^>= 1.2.0.0`
changed to
`hls-plugin-api >= 1.2.0.0 && < 1.2.0.2`

Version `1.5.0` will need
`hls-plugin-api ^>= 1.2.0.0`
changed to
`hls-plugin-api ^>= 1.2.0.2`

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2382"></a>

### CODE REVIEW

**Comment by hololeap** [comment]
When building `ghcide-1.4.2.2` on top of `hls-plugin-api-1.2.0.2`:

```
src/Development/IDE/Types/Options.hs:140:29: error:
    Data constructor not in scope: CheckOnSaveAndClose :: CheckParents
    |
140 |     ,optCheckParents = pure CheckOnSaveAndClose
    |                             ^^^^^^^^^^^^^^^^^^^
```

Building `ghcide-1.4.2.2` on top of `hls-plugin-api-1.2.0.1` works correctly

**Review by jneira — APPROVED** [review]
lgtm, will need hackage revision

**Comment by jneira** [comment]
> Versions 1.4.1.0 1.4.2.0 1.4.2.1 1.4.2.2 1.4.2.3 will need
> hls-plugin-api ^>= 1.2.0.0
> changed to
> hls-plugin-api >= 1.2.0.0 && < 1.2.0.2

* [ ] 1.4.1.0
* [ ] 1.4.2.0
* [ ] 1.4.2.1
* [ ] 1.4.2.2
* [ ] 1.4.2.3

> Version 1.5.0 will need
> hls-plugin-api ^>= 1.2.0.0

* [X] 1.5.0 https://hackage.haskell.org/package/ghcide-1.5.0/revisions/

**Comment by jneira** [comment]
@hololeap all revisions done //cc @pepeiborra

**Pull request merged**
