### PR TITLE
Turn off tasty-rerun

### PR DESCRIPTION
**Pull request by michaelpj**

### CODE REVIEW

**Review by fendor — APPROVED** [review]

**Comment by Bodigrim** [comment]
I think `tasty-rerun` is doing what it's asked for, no? It's just that `cabal test ghcide --test-options="$TEST_OPTS" || cabal test ghcide --test-options="$TEST_OPTS"` is a very strange pattern, especially given that rerun logs are cached.

**Comment by jhrcek** [comment]
I was surprised by this too.
Given that caching is involved, my expectation would be to do
`--rerun-update only` is used in the first run (so that all tests are executed no matter what other branches have chached)
`--rerun-filter filters,exceptions` is used in the second run.

**Comment by michaelpj** [comment]
Yes, this certainly interacts with our slightly idiosyncractic approach to re-running tests. For now I'm just trying to clear the deck so we can get everything green again!

**Comment by michaelpj** [comment]
Somehow, inexplicably, that seems to have got us back to a better place. Could it be that somehow those ghcide tests only pass when run by themselves, which accidentally happens if they fail and then get rerun?

**Comment by michaelpj** [comment]
I don't fully understand, but I think I've restored us to the old state, so I'm going to try and merge this to keep us green.

**Pull request merged**
