### PR TITLE
Add test for multi-component goto def and make runLanguageServer responsible for hiedb

### PR DESCRIPTION
**Pull request by wz1000**
Test for https://github.com/haskell/haskell-language-server/pull/1357

Involved re-jigging 'runWithDb' to be within the callback to 'runLanguageServer' so that the database location
is derived from the 'rootPath' of the LSP session, and not the starting CWD of the ghcide process.

I have verified that the test fails without the mentioned commit.

### CODE REVIEW

**Review by pepeiborra — CHANGES_REQUESTED** [review]
Much cleaner, thanks. I have but one request, can we make the location of the hiedb file configurable? 

I don't have any strong opinions on how to expose it, but in case it helps the SessionLoadingOptions already allow to override the location of the cache dirs, so maybe the easiest thing to do would be to add another field in that record for the hiedb.

**Comment by wz1000** [comment]
> can we make the location of the hiedb file configurable?

@pepeiborra can I do that in another PR tomorrow?

**Comment by pepeiborra** [comment]
> > can we make the location of the hiedb file configurable?
> 
> @pepeiborra can I do that in another PR tomorrow?

Are you keen on landing this PR today?

**Comment by wz1000** [comment]
No, its just that the other changes in this PR are necessary for making the test run.

**Comment by wz1000** [comment]
@pepeiborra OK, I've made it configurable.

**Review by pepeiborra — APPROVED** [review]
awesome, thanks!

**Pull request merged**
