### PR TITLE
Extract a Brittany package

### PR DESCRIPTION
**Pull request by pepeiborra**
I plan to do the same for ormolu and fourmolu

### CODE REVIEW

**Review by Ailrun — COMMENTED** [review]
Could you add this to stack package lists too?

**Comment by pepeiborra** [comment]
> Could you add this to stack package lists too?

the stack situation is disgraceful, we really need to automate some of this

**Review by jneira — APPROVED** [review]
thanks, this needed to be done for quite time ago

**Comment by pepeiborra** [comment]
This will need some more work to drop the AGPL flag, which will require extracting the tests as well. Closing this PR until I have time to do it

**Pull request closed without merging**
