### PR TITLE
Duplicate pragma warnings fixed

### LINKED ISSUE #798: Record quick fixes based on fields should be deduped
image

Not sure what version of ghcide I'm on...

### PR DESCRIPTION
**Pull request by ishmum123**
Closes #798

### CODE REVIEW

**Comment by jneira** [comment]
Thanks for opening it even if we merge #1334 although i feel a little bit sad for your somewhat wasted work if finally that is the case. 
Maybe an initial draft pr would have make easier leverage your work even sharing the authoring with other collaborators.

**Comment by ishmum123** [comment]
@jneira thanks for being so considerate. Don't worry about it. I think of this fix as a way of dipping into the codebase. Also, yes I understand the mistake I made. Would learn from it hopefully. :D

**Comment by jneira** [comment]
Closed in favor of #1334

**Comment by jneira** [comment]
> Don't worry about it. I think of this fix as a way of dipping into the codebase. Also, yes I understand the mistake I made. Would learn from it hopefully

Yeah, i hope you can contribute to the repo in some other way. Open a draft pr doesnt ensure it will not be closed as the alternative can be so different that it does not worth to change the existing one. But sometimes the discussion itself over existing code helps to readjust it.

**Comment by berberman** [comment]
@ishmum123 There is [another issue](https://github.com/haskell/haskell-language-server/issues/555) about pragmas you may have an interest in :)

I think you can refer to `endOfModuleHeader` introduced by #1235

**Pull request closed without merging**
