### PR TITLE
Fix the nix build

### PR DESCRIPTION
**Pull request by michaelpj**
Bumped nixpkgs, removed some unnecessary overrides, added a few newly needed ones.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2452"></a>

### CODE REVIEW

**Review by jneira — APPROVED** [review]
LGTM, thanks for fix the build and the general clean up

**Review by fendor — APPROVED** [review]
LGTM, thank you!

**Comment by jneira** [comment]
and [skip circleci]

**Comment by jneira** [comment]
The build is failing 
```
ghcide> Setup: Encountered missing or private dependencies:
ghcide> hiedb ==0.4.1.*, implicit-hie-cradle >=0.3.0.5 && <0.4
error: builder for '/nix/store/jvclis9nvqxg20fs9gykhk4mijkq0kqa-ghcide-1.5.0.1.drv' failed with exit code 1;
       last 10 log lines:
       >   $, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1024:20 in Cabal-3.2.1.0:Distribution.Simple.Configure
       >   configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:477:12 in Cabal-3.2.1.0:Distribution.Simple.Configure
       >   configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.2.1.0:Distribution.Simple
       >   confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.2.1.0:Distribution.Simple.UserHooks
       >   configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.2.1.0:Distribution.Simple
       >   defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.2.1.0:Distribution.Simple
       >   defaultMain, called at /nix/store/4mdp8nhyfd
dh7bllbi7xszz7k9955n79-Setup.hs:2:8 in main:Main
       > Setup: Encountered missing or private dependencies:
       > hiedb ==0.4.1.*, implicit-hie-cradle >=0.3.0.5 && <0.4
       >
       For full logs, run 'nix log /nix/store/jvclis9nvqxg20fs9gykhk4mijkq0kqa-ghcide-1.5.0.1.drv'.
error: 1 dependencies of derivation '/nix/store/fi9c3v9ycww1m4h26zna9gvzh0m9b1m6-haskell-language-server-1.5.1.0.drv' failed to build
Error: Process completed with exit code 1.
```

**Comment by berberman** [comment]
Also, implicit-hie-cradle in nixpkgs is `0.5.0.0`, but ghcide is using `>= 0.3.0.5 && < 0.4`. Is there a chance to update the bound?

**Comment by fendor** [comment]
@berberman `implicit-hie-cradle == 0.4.*` are all broken (or at least untested). I think we may upgrade to `0.5` as it is just the last version of `0.3.*`, but feels a bit pointless.

**Comment by michaelpj** [comment]
Hmm, guess I was working off an old master.

**Comment by michaelpj** [comment]
@jneira the circleci builds aren't going and I can't merge without them?

**Comment by jneira** [comment]
I changed recently the way circleci interacts with GitHub, will take a look asap

**Comment by jneira** [comment]
it should be fixed, the circleci build have a check per workflow now, instead per job, I think it is  more maintainable now

**Pull request merged**
