### PR TITLE
Bump ghcide

### PR DESCRIPTION
**Pull request by alanz**
To
commit 326e3e32f8b5e46088257f8df5cb5b42d1a3cd59 wz1000/hls-2

### CODE REVIEW

**Comment by jneira** [comment]
ghc-8.8 builds are failing for ghcide tests with lot of:

```
Progress 0/4            ghcide                 > /root/build/ghcide/bench/lib/Experiments.hs:327:21: error:
Progress 0/4            ghcide                 >     • Couldn't match type ‘IO’ with ‘Session’
Progress 0/4            ghcide                 >       Expected type: Session (Seconds, ())
Progress 0/4            ghcide                 >         Actual type: IO (Seconds, ())
Progress 0/4            ghcide                 >     • In a stmt of a 'do' block:
Progress 0/4            ghcide                 >         (startup, _) <- duration
Progress 0/4            ghcide                 >                           $ do waitForProgressDone
Progress 0/4            ghcide                 >                                changeDoc doc [hygienicEdit]
Progress 0/4            ghcide                 >                                waitForProgressDone
Progress 0/4            ghcide                 >       In the second argument of ‘($)’, namely
Progress 0/4            ghcide                 >         ‘do doc <- openDoc exampleModulePath "haskell"
Progress 0/4            ghcide                 >             (startup, _) <- duration
Progress 0/4            ghcide                 >                               $ do waitForProgressDone
Progress 0/4            ghcide                 >                                    changeDoc doc [...]
Progress 0/4            ghcide                 >                                    ....
Progress 0/4            ghcide                 >             liftIO $ output $ "Running " <> name <> " benchmark"
Progress 0/4            ghcide                 >             (runSetup, userState) <- duration $ benchSetup doc
Progress 0/4            ghcide                 >             ....’
Progress 0/4            ghcide                 >       In the second argument of ‘($)’, namely
Progress 0/4            ghcide                 >         ‘runSess dir
Progress 0/4            ghcide                 >            $ do doc <- openDoc exampleModulePath "haskell"
Progress 0/4            ghcide                 >                 (startup, _) <- duration
Progress 0/4            ghcide                 >                                   $ do waitForProgressDone
Progress 0/4            ghcide                 >                                        changeDoc doc [...]
Progress 0/4            ghcide                 >                                        ....
Progress 0/4            ghcide                 >                 liftIO $ output $ "Running " <> name <> " benchmark"
Progress 0/4            ghcide                 >                 (runSetup, userState) <- duration $ benchSetup doc
Progress 0/4            ghcide                 >                 ....’
Progress 0/4            ghcide                 >     |
Progress 0/4            ghcide                 > 327 |     (startup, _) <- duration $ do
Progress 0/4            ghcide                 >     |                     ^^^^^^^^^^^^^...
Progress 0/4            ghcide                 > 
```

**Comment by alanz** [comment]
@jneira yes, I saw that. And when I tried to build locally with stack it bombed out because only the mainline has been updated, none of the tests.  So the benchmark stuff in the tests fails compilation, `Session` instead of `IO` or something.

I decided to pause for a bit.  To me this just indicates I would rather run ghcide master, we only need to line things up when actually needed, not try out unfinished branches.

**Comment by wz1000** [comment]
I am confused, benchmark builds fine for me locally.

**Comment by wz1000** [comment]
Tried the exact command line with stack and it built successfully:

``
❯ stack --stack-yaml=stack88.yaml build --test --no-run-tests
Registering library for ghcide-0.2.0..
ghcide                           > Test running disabled by --no-run-tests flag.
Completed 180 action(s).
```

**Comment by alanz** [comment]
At hls level, using stack to build and test, gives

```
stack --stack-yaml=stack-8.8.3.yaml test
ghcide                 > configure (lib + exe + test)
ghcide                 > build (lib + exe + test)
Log files have been written to: /home/alanz/mysrc/github/alanz/haskell-language-server/.stack-work/logs/

--  While building package ghcide-0.2.0 using:
      /home/alanz/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0 build lib:ghcide exe:ghcide exe:ghcide-test-preprocessor test:ghcide-tests --ghc-options ""
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/alanz/mysrc/github/alanz/haskell-language-server/.stack-work/logs/ghcide-0.2.0.log

    Configuring ghcide-0.2.0...
    Preprocessing executable 'ghcide-test-preprocessor' for ghcide-0.2.0..
    Building executable 'ghcide-test-preprocessor' for ghcide-0.2.0..
    Preprocessing library for ghcide-0.2.0..
    Building library for ghcide-0.2.0..
    Preprocessing executable 'ghcide' for ghcide-0.2.0..
    Building executable 'ghcide' for ghcide-0.2.0..
    Preprocessing test suite 'ghcide-tests' for ghcide-0.2.0..
    Building test suite 'ghcide-tests' for ghcide-0.2.0..
    [3 of 4] Compiling Experiments
    
    /home/alanz/mysrc/github/alanz/haskell-language-server/ghcide/bench/lib/Experiments.hs:327:21: error:
        • Couldn't match type ‘IO’ with ‘Session’
          Expected type: Session (Seconds, ())
            Actual type: IO (Seconds, ())
        • In a stmt of a 'do' block:
            (startup, _) <- duration
                              $ do waitForProgressDone
                                   changeDoc doc [hygienicEdit]
                                   waitForProgressDone
          In the second argument of ‘($)’, namely
            ‘do doc <- openDoc exampleModulePath "haskell"
                (startup, _) <- duration
                                  $ do waitForProgressDone
                                       changeDoc doc [...]
                                       ....
                liftIO $ output $ "Running " <> name <> " benchmark"
                (runSetup, userState) <- duration $ benchSetup doc
                ....’
          In the second argument of ‘($)’, namely
            ‘runSess dir
               $ do doc <- openDoc exampleModulePath "haskell"
                    (startup, _) <- duration
                                      $ do waitForProgressDone
                                           changeDoc doc [...]
                                           ....
                    liftIO $ output $ "Running " <> name <> " benchmark"
                    (runSetup, userState) <- duration $ benchSetup doc
                    ....’
        |
    327 |     (startup, _) <- duration $ do
        |                     ^^^^^^^^^^^^^...
...
```

**Comment by alanz** [comment]
It also looks like there is some leftover merge artifacts in `Development.IDE.GHC.Compat`, which show up when I try to build with GHC 8.6.5

**Pull request merged**
