### PR TITLE
hls-graph.cabal: link to actual readme

### PR DESCRIPTION
**Pull request by juhp**
(Though why not include the README in the package too?)

[skip ci]

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2404"></a>

### CODE REVIEW

**Review by pepeiborra — APPROVED** [review]
Thanks! Would you mind including the readme in the package too?

**Comment by jneira** [comment]
@juhp would you have he chance of oncluding the readme in the package? thanks!

**Comment by jneira** [comment]
> @juhp would you have he chance of including the readme in the package? thanks!

done!

**Comment by juhp** [comment]
Thank you @jneira

**Pull request merged**
