### PR TITLE
Use ghcide master and prepare hls-plugin-api-0.4.1.0

### LINKED ISSUE #173: ghcide master?
A lot has happened since Bristol, and we have made a lot of progress, in `ghcide` and `hls`.

In the `hls` world, there was a time when `ghcide` did not have multi-cradle support, and had some performance issues, so we used a separate fork.  This had some major differences, driven primarily by the alternate build process put forward by @mpickering.

My understanding is that the issues in `ghcide` have largely been resolved, and it is settling in as the primary development point for "vanilla GHC" features. This makes sense.

But hls is still running a fork of ghcide that is a long way from ghcide master.

Is there still any reason to do this?  I would personally prefer the gap to be as small as possible, so we can proceed as two parts of one project, each addressing a different constituency.

### PR DESCRIPTION
**Pull request by jneira**
* Closes #173
* One step forward for #1

### CODE REVIEW

**Review by alanz — APPROVED** [review]
LGTM, Especially as it brings in the file watcher change.

Happy for merge when CI passes

**Comment by wz1000** [comment]
The failing test should be removed. I think it is not very useful to destruct globals, since they will clutter up every single destruct action.

/cc @isovector

**Comment by jneira** [comment]
For completeness the failing test is:
```
tactic
    Can destruct globals:                            FAIL (43.84s)
      test/functional\Tactic.hs:101:
      Expected code action with title Case split on global, not found in []
```

**Comment by isovector** [comment]
It was passing when I wrote it :) but feel free to remove it. @wz1000 's analysis is right!

**Comment by jneira** [comment]
other option is mark it as knownBroken with a comment,; will do if you agree

**Comment by wz1000** [comment]
I broke it on purpose, I don't think this should ever be fixed.

**Pull request merged**
