### PR TITLE
Minimal fix for eval regression

### PR DESCRIPTION
**Pull request by pepeiborra**
Minimal fix for the regression raised in #483 and #485 
This is a serious regression which would justify a minor release.

### CODE REVIEW

**Review by jneira — APPROVED** [review]

**Comment by jneira** [comment]
Thanks for the quick fix

**Comment by mpickering** [comment]
I suppose this was the issue which was causing the plugin to fail when I tried it. Thanks Pepe.

**Comment by bubba** [comment]
@pepeiborra shall I prepare 0.5.1 once this is merged?

**Comment by pepeiborra** [comment]
> @pepeiborra shall I prepare 0.5.1 once this is merged?

I guess it depends on how much work is required. If it's non trivial then it would make sense to wait and collect any other fixes needed.

**Comment by bubba** [comment]
@pepeiborra should just be a matter of bumping the .cabal file, tagging and making a GitHub release, so not much effort at all. We can wait a couple days to see if there's any other bug fix PRs coming in

**Comment by pepeiborra** [comment]
> @pepeiborra should just be a matter of bumping the .cabal file, tagging and making a GitHub release, so not much effort at all. We can wait a couple days to see if there's any other bug fix PRs coming in

If it's that easy, do go for it! I'll get this merged today.

**Pull request merged**
