### PR TITLE
Flake ghc 92

### PR DESCRIPTION
**Pull request by guibou**
This is (partial) flake support for GHC 9.2.

This is in a limited state, especially:

- I have not repaired the support for a few plugins.
- `nix develop .#....-dev` target is not working, it pulls a few dependencies which are not overiden. I'll give another pass soon.

But the cool thing is that it allows to build `haskell-language-server` from flake in another project. I've just updated my work project to GHC 9.2 and I'm enjoying HLS thank to this flake.

Tell me if you prefer to merge "partial" support or if I need to work on the currently broken tasks. I cannot guarantee that I'll allocate time to this soon.

However, users can find this MR and point their flake to this commit and immediately get HLS in their project.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2621"></a>

### CODE REVIEW

**Comment by guibou** [comment]
For reference, here is the command I used in my project to upgrade HLS, where `hls` is the name of my flake input:

```
nix flake lock --override-input hls github:guibou/haskell-language-server/flake_ghc_92
```

**Review by michaelpj — APPROVED** [review]
Are you interested in maintaining these going forwards?

**Comment by teto** [comment]
that may be the problem you are referring to but putting i there just in case since it's an area that under active development in nix so we not have the same results. With nix 2.6.0pre20211217_6e6e998
```
nix develop .#haskell-language-server-921-dev          
AWS error 'RequestTimeTooSkewed' (The difference between the request time and the current time is too large.), will retry in 0 ms
error: cannot fetch input 'path:./flake_hackage?narHash=sha256-gVzFEW0y%2fuPHJaGJ6w7VZc3QDhH6latvmYHJuzaXDa0=' because it uses a relative path
(use '--show-trace' to show detailed location information)
```

Cool work o/

**Comment by michaelpj** [comment]
Ah, that's a good point. Do flakes at relative paths work reliably? I remember there being issues with that.

**Comment by guibou** [comment]
> Ah, that's a good point. Do flakes at relative paths work reliably? I remember there being issues with that.

Initially I moved everything to a relative path flake because I wanted to have a flake only for the hackage dependencies and remove boilerplate, I tried that;

image

Unfortunately, it does not work, because flake does not "evaluate" nix language in the `input` section.

So actually, we can move everything back in the main `flake.nix` file. Let me do that tomorrow.

> Are you interested in maintaining these going forwards?

Yes sure.

**Comment by michaelpj** [comment]
I added you to the CODEOWNERS in https://github.com/haskell/haskell-language-server/pull/2619.

**Comment by smunix** [comment]
@guibou - I'm seeing this issue with the flake use at a relative path; is it possibly related to this fix?

```sh
/e/nixos (main ± u+4) ∫ sudo nixos-rebuild test --cores 10 --max-jobs 5                                             [21:08:41] 
building the system configuration...
warning: Git tree '/etc/nixos' is dirty
error: cannot fetch input 'path:./flake_hackage?narHash=sha256-%2fF3itZJSZDnaxRGpkTffHDkxC7PloYqxVTW%2f%2fbP3i20=' because it uses a relative path
(use '--show-trace' to show detailed location information)
```
I use flake with home-manager and [that used to work before](https://github.com/smunix/dratrion.nixos/blob/059c92ad8a2faddb3c6e4b10b5fab0e059f8bb1f/smunix.home.nix#L57), but it no longer does.

**Comment by guibou** [comment]
@smunix yes, that's unfortunately an issue. I'm working on a fix right now. Sorry for the inconvenience.

**Pull request merged**
