### PR TITLE
Correct issues with pre-commit hook

### PR DESCRIPTION
**Pull request by bradrn**
Following the [Contributing guidelines](https://haskell-language-server.readthedocs.io/en/latest/contributing/contributing.html), I added the specified pre-commit hook when I cloned HLS. However testing it revealed several issues, which are fixed in this PR.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2597"></a>

### CODE REVIEW

**Comment by jneira** [comment]
Hi, thanks for fixing the precommit hook. This include the formatting of some files inside ghcide and i am not sure if it is on purpose.

**Comment by bradrn** [comment]
> This include the formatting of some files inside ghcide and i am not sure if it is on purpose.

 Yes, https://github.com/haskell/haskell-language-server/pull/2597/commits/800c16547403884b98aba4d59265b3764f848d31 was on purpose. My goal was to ensure that the pre-commit hook would be a no-op for freshly pulled code — only modified code would be reformatted.

**Comment by jneira** [comment]
I am ok with the reformat code and there is no pr touching them now afaics, but would like to know @pepeiborra thoughts

**Comment by pepeiborra** [comment]
What were the issues with the hook?

**Comment by bradrn** [comment]
> What were the issues with the hook?

It had a syntax error (fixed in https://github.com/haskell/haskell-language-server/pull/2597/commits/26c5821cf5c088762fbbe306d407730206405e7c), it wasn’t the identity on freshly pulled source code (fixed in https://github.com/haskell/haskell-language-server/pull/2597/commits/800c16547403884b98aba4d59265b3764f848d31), and it failed when running on certain files (fixed in https://github.com/haskell/haskell-language-server/pull/2597/commits/86de39c6713ae6b580ff2fa7fe94274d699022d1).

**Comment by pepeiborra** [comment]
> > What were the issues with the hook?
> 
> It had a syntax error (fixed in [26c5821](https://github.com/haskell/haskell-language-server/commit/26c5821cf5c088762fbbe306d407730206405e7c)), it wasn’t the identity on freshly pulled source code (fixed in [800c165](https://github.com/haskell/haskell-language-server/commit/800c16547403884b98aba4d59265b3764f848d31)), and it failed when running on certain files (fixed in [86de39c](https://github.com/haskell/haskell-language-server/commit/86de39c6713ae6b580ff2fa7fe94274d699022d1)).

Thanks! 

Could you update the Nix version of the hook with the newly excluded files?

https://github.com/haskell/haskell-language-server/blob/ff0ccd6ef0017268bbe7106680dc1505a4a232e3/flake.nix#L171-L175

**Comment by bradrn** [comment]
> Could you also update the Nix version of the hook with the newly excluded files?

Done! (I don’t use Nix regularly, so didn’t even notice there was a Nix version…)

**Review by pepeiborra — APPROVED** [review]
Thank you!

**Review by Ailrun — APPROVED** [review]
LGTM too. Could you resolve the conflict?

**Pull request merged**
