### PR TITLE
Try using haskell/lsp:master

### PR DESCRIPTION
**Pull request by anka-213**
This PR is testing/demonstrating the test failures caused by: https://github.com/haskell/lsp/pull/326
Issue #1895 is for fixing them.

See also https://github.com/haskell/haskell-language-server/pull/1649#issuecomment-855247288

### CODE REVIEW

**Comment by anka-213** [comment]
Huh, apparently those tests succeeded here. I was sure the failed locally. I wonder what changed.

**Comment by anka-213** [comment]
This is the `ghcide` test failure:

```
Starting LSP server...
If you are seeing this in a terminal, you probably should have run WITHOUT the --lsp option!
Started LSP server in 0.00s
setInitialDynFlags cradle: Cradle {cradleRootDir = "/home/runner/work/haskell-language-server/haskell-language-server/ghcide", cradleOptsProg = CradleAction: Cabal}
    notification handlers run sequentially: FAIL
      Exception: Timed out waiting to receive a message from the server.
```

@pepeiborra Do you know if this is related? I can't reproduce it on my local (MacOS) machine.

**Comment by pepeiborra** [comment]
I cannot repro either but it could be related as there are two usages of `getCurrentDirectory` in the ghcide codebase.
I'll prepare a PR with fixes and then you can rebase this one on top to test with lsp HEAD.

**Comment by anka-213** [comment]
It looks like #1897 did indeed fix the test failures!

**Comment by jneira** [comment]
@anka-213 could be this marked as ready for review?

**Comment by anka-213** [comment]
Oh, this was never intended to be merged, it was just intended as a demonstration of #1895.
I believe we can just close this now.

**Pull request closed without merging**
