### PR TITLE
Explicit imports lens (as seen on Twitter)

### PR DESCRIPTION
**Pull request by pepeiborra**
This adds a new code lens for displaying explicit import lists on import declarations. There is hopefully an animated gif that illustrates it.

### CODE REVIEW

**Comment by bubba** [comment]
Could this be exposed via a `source.organizeImports` code action instead? This is really handy but I can imagine for modules with a lot of imports you're going to have to be scrolling through a lot of code lenses

**Comment by pepeiborra** [comment]
> Could this be exposed via a `source.organizeImports` code action instead? This is really handy but I can imagine for modules with a lot of imports you're going to have to be scrolling through a lot of code lenses

That would be a completely different feature, a refactoring to rewrite your imports.

**Comment by ndmitchell** [comment]
If you click on the code lens, does it replace your import? Seems like that would be an expected feature, and thus starts to make the two features increasingly similar.

**Comment by bubba** [comment]
> > Could this be exposed via a `source.organizeImports` code action instead? This is really handy but I can imagine for modules with a lot of imports you're going to have to be scrolling through a lot of code lenses
> 
> That would be a completely different feature, a refactoring to rewrite your imports. This plugin is firmly a code lens. Maybe we need to support a way to toggle plugins on/off ?

Maybe `source.organizeImports` is the wrong code action kind, I was thinking more along the lines of a refactoring code action that appears under imports and offers to "Make import list explicit". This was just a thought though, a code lens is also just fine for me

**Comment by 1Computer1** [comment]
I would much prefer a button I can click over code lenses. Rust Analyzer uses code lenses everywhere which gets annoying quick, but they offer a way to disable them while still being able to do the same actions by just hovering over the item which displays actions you can take on it.

**Comment by pepeiborra** [comment]
> If you click on the code lens, does it replace your import? Seems like that would be an expected feature, and thus starts to make the two features increasingly similar.

Yes, it does

**Comment by pepeiborra** [comment]
> I would much prefer a button I can click over code lenses. Rust Analyzer uses code lenses everywhere which gets annoying quick, but they offer a way to disable them while still being able to do the same actions by just hovering over the item which displays actions you can take on it.

This is a personal preference, I'd rather have a code lens. This is solved with a toggle that you can turn on/off, but currently HLS doesn't provide anything in that regard.

**Comment by 1Computer1** [comment]
Yeah, a toggle would be the best option.

**Comment by expipiplus1** [comment]
It might also be nice to disable this for qualified imports.

**Comment by pepeiborra** [comment]
> It might also be nice to disable this for qualified imports.

Agreed. Please send a PR if you have the chance!

**Comment by expipiplus1** [comment]
see https://github.com/haskell/haskell-language-server/pull/354

**Pull request merged**
