### PR TITLE
Generate custom source tarball 

### LINKED ISSUE #2216: Create proper source tarballs in CI/on releases
Implementing https://gitlab.haskell.org/haskell/ghcup-hs/-/merge_requests/180 I need proper source tarballs.

The default ones are:

1. autogenerated and would depend on github not messing with the tarball layout (they did so at least twice) for the hash to be stable
2. depend on the tag (yeah, if you force push, the hash changes too)
3. have bad tarball names like `1.4.0.tar.gz`, causing trouble for ghcup

Something like:

```sh
git archive --prefix=haskell-language-server-${version}/ --format=tar.gz -o haskell-language-server-${version}.tar.gz HEAD
```

in CI should do the trick.

### PR DESCRIPTION
**Pull request by jneira**
* In addition to artifacts automatically generated by github
* Motivation from #2216

 > * autogenerated and would depend on github not messing with the tarball layout (they did so at least twice) for the hash to be stable
 > * depend on the tag (yeah, if you force push, the hash changes too)
 > * have bad tarball names like 1.4.0.tar.gz, causing trouble for ghcup

* Moreover it could include submodules if we return to use them
* Closes #2216

//cc @hasufell 

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2248"></a>

### CODE REVIEW

**Comment by jneira** [comment]
* The build has been succesful in my repo: https://github.com/jneira/haskell-language-server/releases/tag/1.4.1
* Link to the new source tarball: https://github.com/jneira/haskell-language-server/releases/download/1.4.1/haskell-language-server-1.4.1-src.tar.gz
* It is included in the [sha256sums](https://github.com/jneira/haskell-language-server/releases/download/1.4.1/SHA256SUMS) as `SHA256 (haskell-language-server-1.4.1-src.tar.gz) = f6eda0b17f6e3ad17b9f4407f9b4b4d20a7030cd98a980655ea8bb9d29312bc3`

would be the tarball suitable to be used in ghcup, @hasufell?

**Comment by hasufell** [comment]
> would be the tarball suitable to be used in ghcup, @hasufell?

yes

**Comment by jneira** [comment]
@pepeiborra i've used `j1` for cabal in this one to see it alliviates the failing test suites (eval and tactics plugin)

**Comment by jneira** [comment]
it seems `cabal -j1` is doing its job :sweat_smile:

**Comment by jneira** [comment]
Now circleci is being unreliable :cry: random errors like

```
Starting container alanz/haskell-hie-ci
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image cache not found on this host, downloading alanz/haskell-hie-ci
latest: Pulling from alanz/haskell-hie-ci

5667fdb72017: Pulling fs layer 
d83811f270d5: Pulling fs layer 
ee671aafb583: Pulling fs layer 
7fc152dfb3a6: Pulling fs layer 
a7fd29ca5a80: Pulling fs layer 
4259c72c0fea: Pulling fs layer 
49b7b3b4087d: Pulling fs layer 
3b6f3e77d5df: Pulling fs layer 
bd1cdac5be8f: Pulling fs layer 
e73abc6cb19b: Pulling fs layer 
7b07edcbba2f: Pulling fs layer 
357c6aebab42: Pulling fs layer 
510dee417fa0: Pulling fs layer 
6c84755500bd: Pulling fs layer 
510dee417fa0: Extracting [>                                                  ]  1.671MB/97.59MBB
  Error pulling image alanz/haskell-hie-ci: context deadline exceeded... retrying
  image cache not found on this host, downloading alanz/haskell-hie-ci
latest: Pulling from alanz/haskell-hie-ci

5667fdb72017: Pulling fs layer 
d83811f270d5: Pulling fs layer 
ee671aafb583: Pulling fs layer 
7fc152dfb3a6: Pulling fs layer 
a7fd29ca5a80: Pulling fs layer 
4259c72c0fea: Pulling fs layer 
49b7b3b4087d: Pulling fs layer 
3b6f3e77d5df: Pulling fs layer 
bd1cdac5be8f: Pulling fs layer 
e73abc6cb19b: Pulling fs layer 
7b07edcbba2f: Pulling fs layer 
357c6aebab42: Pulling fs layer 
510dee417fa0: Pulling fs layer 
6c84755500bd: Pulling fs layer 
4c919008f6f2: Extracting [================>                                  ]  27.85MB/83.46MBB

context deadline exceeded
```

**Comment by jneira** [comment]
@pepeiborra could you stamp the pr to merge the ci fix in master and unblock olther ones? thanks!

**Comment by jneira** [comment]
i was too optimistic :cry: 

```
 9 out of 39 tests failed (109.22s)
```

for tactics

**Comment by jneira** [comment]
I still want to believe the `-j1` is alliviating somewhat the issue

**Comment by jneira** [comment]
8.10.7 still resists:

```
 1 out of 8 tests failed (27.39s)
Test suite tests: FAIL
```

**Comment by jneira** [comment]
last fails for tactics:

```
2021-10-01T17:29:13.3775674Z [0mFAIL (3.07s)
2021-10-01T17:29:13.3776143Z         uncaught exception: ErrorCall
2021-10-01T17:29:13.3776582Z         []
2021-10-01T17:29:13.3777036Z         CallStack (from HasCallStack):
2021-10-01T17:29:13.3777642Z           error, called at test\Utils.hs:128:14 in main:Utils
2021-10-01T17:29:13.3778371Z         Use -p '/GoldenListFmap (golden)/' to rerun this test only.
............
2021-10-01T17:29:17.9419793Z [0mFAIL (2.37s)
2021-10-01T17:29:17.9420304Z         uncaught exception: ErrorCall
2021-10-01T17:29:17.9420789Z         []
2021-10-01T17:29:17.9421265Z         CallStack (from HasCallStack):
2021-10-01T17:29:17.9421929Z           error, called at test\Utils.hs:128:14 in main:Utils
2021-10-01T17:29:17.9422610Z         Use -p '/AutoZip (golden)/' to rerun this test only.
```

**Comment by jneira** [comment]
some stamp for this one @Ailrun @pepeiborra @michaelpj? thanks!

**Review by michaelpj — APPROVED** [review]
Looks reasonable.

**Pull request merged**
