### PR TITLE
Add build to ghc-8.10.2 and windows

### PR DESCRIPTION
**Pull request by jneira**
* [leveraging @mistuke work in chocolatey](https://github.com/Mistuke/GhcChoco/issues/10#issuecomment-727654070) (thanks again)
* follow up of #617 
* testing build in my repo: https://github.com/jneira/haskell-language-server/actions/runs/380677453
* it lets us to not have to build locally this version #276

### CODE REVIEW

**Review by ndmitchell — APPROVED** [review]
Instead of including this via exclude, why not use include: {os: windows, ghc: 8.10.2.2} and not put it in the matrix of GHC versions. That's what I'm doing in my projects.

**Comment by jneira** [comment]
* build: https://github.com/jneira/haskell-language-server/actions/runs/380662388

**Comment by jneira** [comment]
We could take ride of other exclusions and use only inclusions but i somewhat like add explicitly why cant use those versions for windows

**Comment by ndmitchell** [comment]
The other exclusions have information, so happy to have them around. The inclusion of a version that doesn't really exist is a bit different though, so I think include of 8.10.2.2 but exclude of others makes sense. But I'm not overly fussed.

**Pull request merged**
