### PR TITLE
Run gh actions on master pushes

### PR DESCRIPTION
**Pull request by jneira**
There exist the possibility of merge two or more pr's with the ci green separately and break master after meging them (and it happened in the repo)

### CODE REVIEW

**Comment by pepeiborra** [comment]
This will not prevent two conflicting PRs from landing and breaking master, only provide confirmation that master is broken.

1. Will this trigger one run for every commit in a non squashed merge?
2. What is the motivation to include the bench and nix actions?

**Comment by jneira** [comment]
> This will not prevent two conflicting PRs from landing and breaking master, only provide confirmation that master is broken.

yeah, but i would say information instead confirmation. And a very valuable one.

> 1. Will this trigger one run for every commit in a non squashed merge?

ugh, that would be ugly, even for every commit of a pr... we can check it for the all pr's prior to ghcide merge

> 2. What is the motivation to include the bench and nix actions?

maybe bench is not useful (I was not checking it tbh), nix builds couldn't be broken in that situation? no problem in remove them though

**Comment by jneira** [comment]
>  we can check it for the all pr's prior to ghcide merge

Only the merge commit is built.

**Comment by pepeiborra** [comment]
The right way to fix this is to ensure that PRs are always tested against the current master. 
I have changed the HLS repo settings to enforce this, see below. Previously the "require status checks" and "require branches to be up to date before merging" were not enabled

image

**Comment by jneira** [comment]
@pepeiborra cool! Prevention could be better than cure. 
Then, pr's must be rebased against master even if they can be merged cleanly, only to run the test suite with latest code?

**Comment by pepeiborra** [comment]
> @pepeiborra cool! Prevention could be better than cure.
> Then, pr's must be rebased against master even if they can be merged cleanly, only to run the test suite with latest code?

In my understanding there's no user action needed.

**Comment by Ailrun** [comment]
AFAIK, a user should rebase the PR or we should add a merge commit to the PR branch.

**Comment by pepeiborra** [comment]
Yeah, there is an "Update branch" button showing:

image

Seems like a reasonable price to pay, I think

**Comment by jneira** [comment]
agree, merging pr's will be less agile but safer in exchange
we can change it later (and add the test on master pushes) if we think merging pr's are too rigid

**Comment by jneira** [comment]
I have to say that the actual state of ci makes it loopy less agile 😟

**Pull request closed without merging**
