### PR TITLE
Add benchmarks for hole fits

### PR DESCRIPTION
**Pull request by pepeiborra**
Let's find out how expensive hole fits are across GHC versions and benchmark examples

### CODE REVIEW

**Comment by pepeiborra** [comment]
The results for 8.10.4 are really quite bad. For the `lsp-types` examples, we have 10s total time for normal edits, vs 186s for edits with 2 holes. Roughly 18X slower.

```
version    name                             success   samples   startup              setup                userTime             delayedTime             totalTime            maxResidency   allocatedBytes
upstream   edit                             True      50        1.734907637          0.0                  0.60276508           10.115454337999992      10.724588409         200MB          9359MB
upstream   hole fit suggestions             True      50        1.6322459790000001   0.0                  186.34176163599994   2.3826531999999997e-2   186.37326197500002   280MB          199205MB
```

**Comment by pepeiborra** [comment]
Once this has landed, I'll open a new draft PR to disable refinement hole fits so that we can measure the impact and discuss.

**Review by jneira — APPROVED** [review]
Great work, that is really bad numbers

**Review by Ailrun — APPROVED** [review]
LGTM

**Pull request merged**
