### PR TITLE
Fix GenChangelog script format

### PR DESCRIPTION
**Pull request by Ailrun**
Before this PR, the script creates `([PR number)](link)`, which makes `)` after the PR number also clickable. This PR fixes so that only the PR number is treated as a link.

### CODE REVIEW

**Comment by Ailrun** [comment]
BTW: do we even need to check CI for PR like this?

**Comment by berberman** [comment]
For github actions, we could use [`paths or paths-ignore`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths) to configure files we don't want to trigger CI on update.

**Comment by jneira** [comment]
yeah I want to add it and maybe honour the tag `ci skip` since some time ago 😅

**Review by jneira — APPROVED** [review]
thanks for the fix, maybe we should correct existing entries? (maybe in the next release)

**Comment by Ailrun** [comment]
@jneira Actually this PR also updated the exisiting log too. (see https://github.com/haskell/haskell-language-server/pull/1387/files#diff-874f33563125619a7a5cb567ebe523c59258662d69858d78d24d947b275f9c6c)

**Comment by jneira** [comment]
oh sorry I missed it in the mobile app UI

**Pull request merged**
