### PR TITLE
Add ubuntu builds to gitlab CI

### LINKED ISSUE #3169: Add ubuntu flavoured release pipelines
* https://github.com/haskell/haskell-language-server/issues/3160
* https://github.com/haskell/ghcup-metadata/commit/c5d3930c8ff809a23fe2337e61656fe429b4d37d

### PR DESCRIPTION
**Pull request by hasufell**
Fixes #3169

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3191"></a>

### CODE REVIEW

**Comment by hasufell** [comment]
https://gitlab.haskell.org/maerwald/haskell-language-server/-/pipelines/56839

**Review by pepeiborra — APPROVED** [review]
### Moar builds!

**Comment by hasufell** [comment]
Still issues with the tar job

**Comment by hasufell** [comment]
https://gitlab.haskell.org/maerwald/haskell-language-server/-/pipelines/56845

**Review by wz1000 — APPROVED** [review]

**Comment by hasufell** [comment]
https://gitlab.haskell.org/maerwald/haskell-language-server/-/pipelines/57272

**Comment by wz1000** [comment]
I've fixed the build, along with a fix for #3162: https://gitlab.haskell.org/haskell/haskell-language-server/-/pipelines/57254

**Comment by hasufell** [comment]
https://gitlab.haskell.org/maerwald/haskell-language-server/-/pipelines/57532

**Comment by hasufell** [comment]
gitlab pipeline succeeded: https://gitlab.haskell.org/maerwald/haskell-language-server/-/pipelines/57533

**Comment by michaelpj** [comment]
This is for the old gitlab CI

**Pull request closed without merging**
