### PR TITLE
Make Wingman generate numbered holes

### PR DESCRIPTION
**Pull request by isovector**
Some of the upcoming changes for refinery v4 necessitate giving unique identifiers to each hole generated by Wingman. This PR makes that happen in anticipation.

### CODE REVIEW

**Review by jneira — APPROVED** [review]

**Comment by isovector** [comment]
Accidentally closed this

**Comment by Ailrun** [comment]
Does this work when there exists a numbered hole already? Like
```
f :: Bool -> Bool -> Int
f True _ = _0
f False _ = _ {- can we split the second argument here? -}
```

**Comment by isovector** [comment]
Good catch. That particular case works, but if the hole exists in the same expression it might cause some naughtiness.

**Comment by Ailrun** [comment]
Then it's might be better to add some test cases for those

**Pull request closed without merging**
