### PR TITLE
Update nix flake

### PR DESCRIPTION
**Pull request by lf-**
Doing a nixpkgs update gains ghc 8.10.6 support.

lsp-types needed updating to satisfy bounds so I did that.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2159"></a>

### CODE REVIEW

**Comment by lf-** [comment]
Bleh. This seems to be unfixable without dropping fourmolu I think, since it depends on ghc-lib-parser 8.10.x. Also seems to explode stylish-haskell. Pain.

**Comment by lf-** [comment]
It seems to build on both ghc8106 and ghc901 on my machine.

**Comment by fendor** [comment]
#2128 would benefit from this (e.g. make it mergable)

**Comment by lf-** [comment]
aaaa it looks like the Mac build is broken on tracy but I have no idea what's wrong with it because it didn't emit the entire log to standard output (???!). I guess I get to be the lucky one to have some ~pain~ trying to use a Mac VM.

**Comment by berberman** [comment]
It seems that `tracy-0.7.8` is broken on macOS:
```
error: builder for '/nix/store/9fkiihfp9rfdfckrkgqlk36hag4r67s7-tracy-0.7.8.drv' failed with exit code 2;
```

**Comment by lf-** [comment]
> It seems that `tracy-0.7.8` is broken on macOS:
> 
> ```
> error: builder for '/nix/store/9fkiihfp9rfdfckrkgqlk36hag4r67s7-tracy-0.7.8.drv' failed with exit code 2;
> ```

Yup, the main question is if it can be fixed easily.

**Comment by lf-** [comment]
https://gist.github.com/45a30561f669649fc97a8aa352483964 build logs for tracy

**Comment by lf-** [comment]
https://github.com/NixOS/nixpkgs/pull/136818

which I have written into our overlay for the minute. Tracy should build now.

**Review by fendor — APPROVED** [review]
LGTM, thanks!

**Review by berberman — APPROVED** [review]
Thank you for the fix!

**Comment by jneira** [comment]
I merged this manually hoping it will fiix the nix builds in master but they failed :worried: 

```
hls-plugin-api> ghc-api-compat ==8.10.7
error: builder for '/nix/store/lm9qas2nb80q93csxjfyq67wz8p8h7dm-hls-plugin-api-1.2.0.1.drv' failed with exit code 1;
       last 10 log lines:
       >   $, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1024:20 in Cabal-3.2.1.0:Distribution.Simple.Configure
       >   configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:477:12 in Cabal-3.2.1.0:Distribution.Simple.Configure
       >   configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.2.1.0:Distribution.Simple
       >   confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.2.1.0:Distribution.Simple.UserHooks
       >   configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.2.1.0:Distribution.Simple
       >   defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.2.1.0:Distribution.Simple
       >   defaultMain, called at /nix/store/4mdp8nhyfddh7bllbi7xszz7k9955n79-Setup.hs:2:8 in main:Main
       > Setup: Encountered missing or private dependencies:
       > ghc-api-compat ==8.10.7
       >
       For full logs, run 'nix log /nix/store/lm9qas2nb80q93csxjfyq67wz8p8h7dm-hls-plugin-api-1.2.0.1.drv'.
error: 1 dependencies of derivation '/nix/store/j7q6g5lzrr3mvvygd632dc6qhm48whmf-haskell-language-server-1.3.0.0.drv' failed to build
```

**Comment by jneira** [comment]
It seems the nix build is not taking in account last ghc-api-compat hackage releases

**Comment by lf-** [comment]
> It seems the nix build is not taking in account last ghc-api-compat hackage releases

Try my branch (`lf-`) `update-flake-ii`, I just updated it to the relevant hackage release. Have not tested it besides it evaluating. If it works, I guess that can become a PR. Going to bed now.

https://github.com/haskell/haskell-language-server/compare/master...lf-:update-flake-ii

**Comment by jneira** [comment]
>  I guess that can become a PR

please do!

**Pull request merged**
