### PR TITLE
Use last with-utf8 to fix #1372

### LINKED ISSUE #1372: Build Error for 8.10.4 (maybe only under Windows)
### Your environment

please note: that is *after* I fixed the issue with the workaround I added bellow

```
haskell-language-server version: 0.9.0.0 (GHC: 8.10.4) (PATH: C:\Users\cakoeni1\AppData\Roaming\local\bin\haskell-language-server.exe) (GIT hash: 4d431e9a7c51ab1b817476c1fec45c6cbaa676e8)
Tool versions found on the $PATH
cabal:          Not found
stack:          2.5.1
ghc:            Not found
```

only stack should matter here though - it's a windows OS

### Steps to reproduce

    git clone https://github.com/haskell/haskell-language-server --recurse-submodules
    cd haskell-language-server
    stack ./install.hs hls-8.10.4

### Expected behaviour
haskell-language-server.exe and haskell-language-server-wrapper.exe is build and installed

### Actual behaviour
error

    with-utf8 > app\utf8-troubleshoot\Main.hs:23:31: error:
    with-utf8 >     Module `GHC.IO.Encoding.Iconv' does not export `localeEncodingName'
    with-utf8 >    |
    with-utf8 > 23 | import GHC.IO.Encoding.Iconv (localeEncodingName)

see https://github.com/serokell/haskell-with-utf8/issues/9

### work around

add this to `extra-deps` in `stack-8.10.4.yaml`:

      - github: f-f/haskell-with-utf8
        commit: 8ae743ac6503a4c494ea3bd52f1fe7d72f9f125d

### PR DESCRIPTION
**Pull request by jneira**
* Closes #1372

### CODE REVIEW

**Review by Ailrun — APPROVED** [review]

**Review by Ailrun — CHANGES_REQUESTED** [review]
Wait, sorry for changing the review. We need to update stack.yaml too.

**Comment by jneira** [comment]
thanks for noting it, i had to remove duplicate entriesin 8.6 too 🤦

**Review by Ailrun — APPROVED** [review]
Thanks

**Comment by jneira** [comment]
silly changes, silly mistakes :worried:

**Pull request merged**
