### PR TITLE
Cancel prev runs for bench and nix

### PR DESCRIPTION
**Pull request by jneira**
* It is working really well to the test workflow

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2335"></a>

### CODE REVIEW

**Comment by pepeiborra** [comment]
If I understand correctly this is a new feature of Github CI providing built-in support to deal with duplicate actions. 
So far we have been using a third-party action to do this (`fkirc/skip-duplicate-actions`).

> It is working really well to the test workflow

It looks like the test workflow now has both mechanisms enabled, is that what we want?

https://github.com/haskell/haskell-language-server/blob/9fa6abe2cb910bd07a3eeb8a751974d96dadea5e/.github/workflows/test.yml#L24-L28

https://github.com/haskell/haskell-language-server/blob/9fa6abe2cb910bd07a3eeb8a751974d96dadea5e/.github/workflows/test.yml#L8-L10

**Comment by jneira** [comment]
> It looks like the test workflow now has both mechanisms enabled, is that what we want?

Oh i forgot to set it to false as i did for the test workflow, thanks. However we are using other features of skip-duplicate-actions so i would keep it around (like in test workflow)

**Comment by pepeiborra** [comment]
> > It looks like the test workflow now has both mechanisms enabled, is that what we want?
> 
> 
> 
> Oh i forgot to set it to false as i did for the test workflow, thanks. However we are using other features of skip-duplicate-actions so i would keep it around (like in test workflow)

Can you elaborate on why we need both?

**Comment by jneira** [comment]
> Can you elaborate on why we need both?

Cause we are using skip-duplicate-actions for skipping tests in the current workflow by file paths changed by the pr. It is interesting enough to keep it until we find an alternative.

**Comment by pepeiborra** [comment]
So if we are keeping it, why not keep using it to cancel duplicate runs as it already does? In other words, what's the motivation for this PR?

**Comment by jneira** [comment]
> 
> 
> So if we are keeping it, why not keep using it to cancel duplicate runs as it already does? In other words, what's the motivation for this PR?

Oh sorry, i should had linked the fisrt pr adding it to the test workflow: https://github.com/haskell/haskell-language-server/pull/2310

**Comment by jneira** [comment]
uh oh funct-tests are hanging in windows 9.0.1 here :facepalm:

will disable it again

**Review by pepeiborra — APPROVED** [review]

**Review by michaelpj — APPROVED** [review]

**Pull request merged**
