### PR TITLE
List all available plugins

### PR DESCRIPTION
**Pull request by July541**
This pr add an option to list all available plugins as #2132 described.

It looks like 
```
$ /home/treee/Code/haskell-language-server/dist-newstyle/build/x86_64-linux/ghc-8.10.4/haskell-language-server-1.3.0.0/x/haskell-language-server/build/haskell-language-server/haskell-language-server --list-plugins
brittany
callHierarchy
class
eval
floskell
fourmolu
ghcide-code-actions-bindings
ghcide-code-actions-fill-holes
ghcide-code-actions-imports-exports
ghcide-code-actions-type-signatures
ghcide-completions
ghcide-core
ghcide-hover-and-symbols
ghcide-type-lenses
haddockComments
hlint
importLens
moduleName
ormolu
pragmas
refineImports
retrie
splice
stylish-haskell
tactics
```

I think that simultaneously to list if this plugin is enabled default is better, but I don't find anything to capture that:(

### CODE REVIEW

**Review by jneira — APPROVED** [review]
Wow many thanks, it looks great as is

> I think that simultaneously to list if this plugin is enabled default is better, but I don't find anything to capture that:(

Well i think for now all plugins are enabled in the config by default so it is not urgent

**Comment by July541** [comment]
Test works well on my branch https://github.com/July541/haskell-language-server/pull/2, not sure why this was broken.

**Comment by July541** [comment]
Looks like https://github.com/haskell/haskell-language-server/issues/2115

**Comment by jneira** [comment]
> 
> 
> Looks like #2115

rerunning jobs

**Comment by jneira** [comment]
> 
> 
> Wow many thanks, it looks great as is
> 
> > I think that simultaneously to list if this plugin is enabled default is better, but I don't find anything to capture that:(
> 
> Well i think for now all plugins are enabled in the config by default so it is not urgent

In any case you can get the default configuration, where you could find if a included plugin is enabled by default or does not

**Pull request merged**
