### PR TITLE
Pr 658 fix completion tests

### PR DESCRIPTION
**Pull request by peterwicksstringfield**
This PR is based on #658 . See the discussion there. It is an attempt to fix the code completion tests which are failing after the upgrade to ghcide 0.6.0.

This is a WIP, these tests are not reliable. I think they weren't reliable even before ghcide 0.6.0 ... but it seems like they are less reliable now. Not enough time to debug it all today, so I'm dumping what I have here.

There are three problems:

1. ghcide 0.6.0 reports fewer diagnostics by default that ghcide 0.5.0. This was causing some tests to fail because they expected certain files to produce diagnostics, and those files no longer produced diagnostics. Such failures manifest as timeouts but they aren't really about time. Fixed.

2. ghcide 0.6.0 has code completion snippets, so the code completion tests need to be updated to account for that. Fixed.

3. There's a third issue that is making the tests randomly fail. I think it was pre-existing but rare and I've only just now noticed. I might know what's happening but I don't have time to really figure it out right now. (We load a file, make a change to it, request code completions, and then check that the completions we get are the ones we expect. But maybe the code completions are based on the contents of the file from before we made the change, because we aren't doing whatever it is we need to do to get the freshest possible results. I thought the way we were doing it was okay but clearly I'm wrong about something. Or maybe that's not the problem at all and its something totally different.)

### CODE REVIEW

**Comment by jneira** [comment]
@peterwicksstringfield many thanks for fix again the tests against ghcide-0.6.0. I am gonna include this one in #658 to make progress towards fix ci. We can tackle the third point afterwards.

**Comment by peterwicksstringfield** [comment]
Opps. There are several other testfiles that are no longer producing diagnostics by default and they require fixing as well. Will push soon.

**Comment by jneira** [comment]
@peterwicksstringfield mmm, and what about remove waitForDiagnostics after opening the file? have you tried it? i started to remove them in Completion and i think it fixed the timeout

**Comment by jneira** [comment]
I think we were using diagnostics for waiting to the server to be ready to produce completions. Removing diagnostics from testdata files and replacing waitForDiagnostics with sleep's makes the work too.

**Comment by jneira** [comment]
Want to note that i dont like to use `sleep` but i dont think use `waitForDiganostics` is better, cause it seems it would be neccesary to get completions and it is not true. So wait for the server explicitly is slightly better imo.
The real solution should wait for some server message telling the client is has ended to load the file and all features are available.
Maybe the messages i added in ghcide (in debug mode) for signal the end of the session loading could be used for that:
https://github.com/haskell/ghcide/blob/9d0fc445a48dcbbf436471a64d2e3f894831994e/src/Development/IDE/Core/Shake.hs#L611

**Comment by jneira** [comment]
Fully included in #658

**Comment by peterwicksstringfield** [comment]
Sorry, I was suddenly much busier than I expected to be and stopped responding. (The good kind of busy, but still.) Thanks for keeping up the momentum.

I agree with closing this PR. It has served its purpose now that 658 is merged.

I also agree that waitForDiagnostic is not an ideal approach.

**Pull request closed without merging**
