### PR TITLE
Add installation instructions for FreeBSD.

### PR DESCRIPTION
**Pull request by arrowd**

### CODE REVIEW

**Review by jneira — APPROVED** [review]
Many thanks for add support for freebsd and include it here!

**Comment by hasufell** [comment]
The docs might need adjustment after https://github.com/haskell/haskell-language-server/pull/2200

**Comment by arrowd** [comment]
From what I can tell, FreeBSD binaries are being produced for FreeBSD 13. They should be produced on FreeBSD 12.2 to be compatible with both 12 and 13.

I also prefer our Ports for producing packages, but if this works out - sure, why not.

**Comment by hasufell** [comment]
@arrowd https://gitlab.haskell.org/ghc/ghc/-/issues/20390

**Pull request merged**
