### PR TITLE
feat(git): Add install/hie.yaml to gitignore

### LINKED ISSUE #326: Add install/hie.yaml to .gitignore
For some reason `install/hie.yaml` is not in `.gitignore`.

I'll probably fix this today if nobody does it first 😄

### PR DESCRIPTION
**Pull request by Sir4ur0n**
Closes #326

### CODE REVIEW

**Comment by Sir4ur0n** [comment]
I think build failed for an unrelated reason, if anyone can restart it?

**Comment by jneira** [comment]
Maybe we could ignore ll possible hie.yaml's in the code base with:
```
**/hie.yaml
```
?

**Comment by Sir4ur0n** [comment]
> 
> 
> Maybe we could ignore all possible hie.yaml's in the code base with:
> 
> ```
> **/hie.yaml
> ```
> 
> ?

I thought about it but then thought "What if in the future some (integration?) tests want to test `hie.yaml` integration?".

If you prefer though, I can switch to wildcard `hie.yaml` rather than absolute paths, let me know!

**Comment by jneira** [comment]
> I thought about it but then thought "What if in the future some (integration?) tests want to test hie.yaml integration?".

good point, better being cautious

**Pull request merged**
