### PR TITLE
Prepare 1.10.0.0

### PR DESCRIPTION
**Pull request by wz1000**

### CODE REVIEW

**Review by fendor — APPROVED** [review]
Changes to cabal plugins look good to me.

**Review by konn — APPROVED** [review]
LGTM as for the Splice Plugin :+1:

**Review by isovector — APPROVED** [review]

**Review by July541 — APPROVED** [review]
call hierarchy and gadt plugins look good to me. Thanks for your work!

**Comment by maralorn** [comment]
Really don’t want to hurry you, but I would like to know whether there is a timeline on this and if there are any obstacles that need to be resolved.
Our nixpkgs update is currently stuck on the half release.
We can work around this, but that doesn’t make sense if you finish the release in the next few days anyway.

**Pull request merged**
