### PR TITLE
Delete duplicate cabal clause for applyrefact2

### PR DESCRIPTION
**Pull request by peterwicksstringfield**
The other copy of this clause is a few lines above the one I deleted.

### CODE REVIEW

**Comment by jneira** [comment]
wow, i didnt notice ApplyRefact was listed her, thanks for catching up
In fact i think we could remove all ocurrences, as[ hlint tests are using a direct hie.yaml](https://github.com/haskell/haskell-language-server/blob/master/test/testdata/hlint/hie.yaml) and hls does not look in parent dirs.

**Comment by peterwicksstringfield** [comment]
I think you are right. Also apparently ApplyRefact.hs doesn't exist anymore so we can lose that clause too. 

test/testdata/HlintPragma.hs and test/testdata/FileWithWarning.hs are currently unused in the tests, so I guess those clauses are sort of useless too. All the HaRe stuff too.

**Comment by jneira** [comment]
> test/testdata/HlintPragma.hs and test/testdata/FileWithWarning.hs are currently unused in the tests, so I guess those clauses are sort of useless too. All the HaRe stuff too.

yeah, please, clean them too if you dont mind make the pr larger

**Comment by jneira** [comment]
Well, let's move this forward, the full clean could be in another pr

**Review by jneira — APPROVED** [review]

**Pull request merged**
