### PR TITLE
CI: linting

### PR DESCRIPTION
**Pull request by Anton-Latukha**

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
[skip circleci]

**Review by jneira — APPROVED** [review]
Looks much cleaner this way, thanks!

**Comment by Anton-Latukha** [comment]
I mainly do this for paths blocks, as they have advanced logic & so being able to read & parse them is useful.

**Comment by Anton-Latukha** [comment]
Oh. CI can not merge. It is me.

I pushed & then dropped the last commits, & seems CI got puzzled, some workflows appeared twice.

**Comment by Anton-Latukha** [comment]
Hmm...

**Comment by Anton-Latukha** [comment]
@jneira maybe you know what this means:
Screenshot-2021-12-26-00:39:45

HLint workflow passes, but there is a branch protection check, maybe it does not catch the HLint (or HLint workflow needs something) or something?

**Comment by Anton-Latukha** [comment]
I had to add hlint_post_job or something?

**Comment by Anton-Latukha** [comment]
The same is in: https://github.com/haskell/haskell-language-server/pull/2527

**Comment by Ailrun** [comment]
The branch protection rule is global so the same rule applies to all PRs. It should work without any extra "post" jobs, so it seems strange that CI doesn't check the passed job... Let's disable the requirement for now.

**Comment by jneira** [comment]
I think it is working now, will enable again

**Comment by jneira** [comment]
> I think it is working now, will enable again

nope there are 2 checks, and GH does not know they are the same

**Comment by Anton-Latukha** [comment]
@Ailrun 

Thanks.

I did workflows the default way & not familiar with what's happening there & those processes.

**Pull request merged**
