### PR TITLE
Record Snippets Completion

### PR DESCRIPTION
**Pull request by gdevanla**
This PR is to address the feature #333 

Tasks
- [x]  Local completions
- [x]  Non Local completions
- [x] Add rules and cache results
- [ ]  Add tests
- [ ]  Add snippets to multiple lines, if it exceeds the 80 char limit. (Need to decide if we should leave this to other formatting tools)

### CODE REVIEW

**Comment by gdevanla** [comment]
Here is a working demo of what I have so far.

record_snippet_demo

**Comment by pepeiborra** [comment]
This looks awesome, thanks! 

You will find that the approach used to get completions, namely traversing the parsed AST, doesn't scale to non local completions. 

But not to worry, GHC already provides what you need!  The `TypeEnv` obtained by typechecking a module contains a map of `TyThing`, from which you can extract all the data constructors and their fields. 

You can see how this is used by grepping for `lookupTypeEnv` in the  Development.IDE.Plugin.Completions.Logic module in ghcide. 

Finally, to avoid repeating all the work on every completion request (potentially on every keystroke) you will want to add a rule provider to your plugin, creating a new rule to cache the completions.

**Comment by gdevanla** [comment]
Thanks, for the thumb's up.

I do have a prototype for non-local completions. I have it here.https://github.com/gdevanla/ghc-scratch/blob/1f7c7bd31bdb4f10ef818a3c5630d8fb72fcd23d/app/Main.hs#L328.   I am yet to integrate it into this PR.

Do you think, this approach would be too slow for non-local completions?

**Comment by gdevanla** [comment]
Thanks. Just so that I understand the term correctly, when you mean `package imports`, do you mean `import` statement refer to modules in other packages?

The approach I tested at least seem to work for module in the same package. 

Either ways, I will consider the approach used in `Logic.hs`, since I have been borrowing my current code from there as well!

**Comment by gdevanla** [comment]
Demo of records from non-local modules


record-snippet-demo2-1

**Comment by gdevanla** [comment]
@pepeiborra I was able to use lot of code you pointed to to get the record completions for non-local declarations working.

But, I had to make one big assumption. I had to use some of the methods from `import qualified Development.IDE.Core.Compile as Compile`,  which is not exposed by `ghcide`.  I was wondering if it made sense to expose that module. I feel there is lot of useful stuff in there that plugins could reuse.

The methods I am currently using out of the module are  :     `parseHeader`, `typecheckModule`, `lookupName`.

I think this was the easiest path for me. Do you have other suggestions.

**Comment by wz1000** [comment]
Instead of duplicating so much code, either these changes should directly be made to completions in ghcide, or completions from ghcide should be moved entirely into `hls`.

**Comment by gdevanla** [comment]
Actually, I have another branch which I have not shared, where I have done part of it.  

That said, there is some overlap, but I would not say, we are duplicating code from `Completions`.  We just need functions exposed from `Compile` module.

**Comment by googleson78** [comment]
This is only done on completions right now, right? Would it be easy/possible to also add a code action for this?

**Comment by gdevanla** [comment]
@googleson78 I was not planning to. But, once I have this task complete, and I can look into that.

**Comment by googleson78** [comment]
Sorry if it sounded like a demand! I was intending it to be more of a "is this possible with current architecture?" question

**Comment by wz1000** [comment]
You define three new rules which almost exactly mirror the rules used to generate completions in ghcide. I think it would be much better if you move this functionality into the ghcide completion code.

**Comment by gdevanla** [comment]
@googleson78 It did not sound demanding at all!  Once this design stabilizes I will work on that! Thanks for the feedback and the suggestion.

**Comment by gdevanla** [comment]
@wz1000 Thanks for the observations and your suggestion. 

Please let me clarify my thoughts below.  I see the code in have in the PR in 3 parts. Please feel free to correct my thoughts on this!

1.  The general definition of Rules -  this is general boiler plate code that is present in all plugins. 
[here](https://github.com/haskell/haskell-language-server/blob/2ae9d0736efd13e6bf45c4ebe1fab4e00964fcc6/plugins/default/src/Ide/Plugin/RecordSnippets.hs#L66-L103)


2.  Then we have the  LSP plugin function `getSnippets` which again is mostly boiler plate code with each plugin calling plug-in specific `Rules` and processing them and integrate with the IDE. [here](https://github.com/haskell/haskell-language-server/blob/2ae9d0736efd13e6bf45c4ebe1fab4e00964fcc6/plugins/default/src/Ide/Plugin/RecordSnippets.hs#L197-L223)

3.  Now, we have the **actual** code, that need to do 2 sets of values.
     a) Production of Rules for `Local ` ->  This just uses the already available `GetParsedModule` rule. [here](https://github.com/haskell/haskell-language-server/blob/2ae9d0736efd13e6bf45c4ebe1fab4e00964fcc6/plugins/default/src/Ide/Plugin/RecordSnippets.hs#L228-L248)

     b)  Production of Rules for Non-Local completions
            -  This is the part where we have some **duplicated code**.  Most of the duplicated code is in  `getNonLocalSnippets`. [here](https://github.com/haskell/haskell-language-server/blob/2ae9d0736efd13e6bf45c4ebe1fab4e00964fcc6/plugins/default/src/Ide/Plugin/RecordSnippets.hs#L105-L143) 
                This function essentially is trying to get hold of the `typechecked` module before we can discover the definitions.  Notice how this function just calls `cachedSnippetsProducer` after it gets hold of the `typechecked` module.  The `cacheSnippetsProducer` does a lot less than the `cachedCompletion` functions in `ghcide` and I would to consider it duplicated.

So, notice that the only duplicated piece of code (discounting for required bolier plate), is just the `getNonLocalSnippets`.

-----------------------

Now,  I see two approaches based on your observation, in terms of how we can move forward:

### Approach 1.  

Make the functionality available in `getNonLocalSnippets` available as a function in `ghcide`, so that we can get hold of a `typechecked` module.  Then, both `Completions` and this plugin could use the same function.

I would, with the limited knowledge I have on this project, prefer that path. I am happy to submit a PR for this in the `ghcide` project. This can also be its own cached-rule if that works.

### Approach 2. 

 As you suggest, move  the code I have in terms of discovery of Records into `Completions`.  I feel this path complicates the already complicated code that is powering the `Completion`. We loose separation of concerns at the risk of packing lot of functionality into one piece.  

----------------------------


Approach (1) addresses the sharing of the `typechecked` module generation and removes the most complicated login in both this plugin and the `Completion` plugin.  This could also help other plugins in the future and I think that is a plus.

That said, I am open to taking either approaches based on how you / @pepeiborra or other more experienced members in this code base suggest.  I have enjoyed learning so much from this code base already!

**Comment by wz1000** [comment]
See https://github.com/haskell/ghcide/pull/882

> We loose separation of concerns at the risk of packing lot of functionality into one piece.

There is already a lot of complicated logic in completions, I don't think this would significantly increase the complexity. It is also good to have all the logic in once place for ease of understanding.

The parts you want to expose seem to be very dubious hacks which I don't think anyone should be using without a lot of careful thought. The PR linked above tries to remove some of them from ghcide.

**Comment by pepeiborra** [comment]
I support the following courses of action: 

1. Moving this PR to ghcide entirely
2. To preserve separation of concerns, extend the `RuleResult` of the `NonLocalCompletions` rule in ghcide with the artefacts needed by this plugin to compute the record completions. But this needs to be done carefully to avoid using too much memory

**Comment by gdevanla** [comment]
@wz1000 Thanks for the suggestion and sharing your latest PR on the changes to Completions. I look forward to understanding the changes.

@pepeiborra / @wz1000 I will move my changes to ghcide and submit a PR there. I will wait for https://github.com/haskell/ghcide/pull/882 to be merged and work off those changes.

**Comment by gdevanla** [comment]
Addressed here  https://github.com/haskell/ghcide/pull/900

**Pull request closed without merging**
