### PR TITLE
Add support for ghc-8.10.2

### LINKED ISSUE #298: Support for GHC-8.10.2
GHC-8.10.2 was just released. 

Hopefully, the differences between it and GHC-8.10.1 from the HLS point of view are minor enough to make adding the support easy?

### PR DESCRIPTION
**Pull request by jneira**
* Although it seems 8.10.3 will be released soon
* I've updated the stack-8.10.1.yaml resolver before using it as base for stack-8.10.2.yaml
* Tested locally with cabal
* Fixes #298

### CODE REVIEW

**Comment by bubba** [comment]
Does anything need to be changed in the install script?

**Comment by jneira** [comment]
No, if you have a `stack-${ghcVersion}.yaml` you can build hls for that ghc version wih stack and *cabal* (in fact, for the latter an empty file named  `stack-${ghcVersion}.yaml` would suffice)

**Comment by mouse07410** [comment]
> Although it seems 8.10.3 will be released soon

Wha...?!  First, a new release doesn't come for ages, and then they spit out a new compiler every week?

@jneira do you happen to know what 8.10.3 is about? Are there some "insurmountable difficulties" or huge bugs is 8.10.2 that force 8.10.3 out?

Along the same line, how difficult would it be to add 8.10.3 support? If 8.10.3 gets released to fix problems with 8.10.2, it's probably important to start supporting it ASAP?

**Comment by jneira** [comment]
It is not usual to release versions so quick, the main reason is https://gitlab.haskell.org/ghc/ghc/-/issues/1855.
I expect supporting 8.10.3 will be trivial, as there will be not big changes.

**Comment by mouse07410** [comment]
> ...  the main reason is https://gitlab.haskell.org/ghc/ghc/-/issues/1855. ...

Darn... That's a very old issue - one digit must've been lost...

I see two high-priority issues with 8.10.2:
https://gitlab.haskell.org/ghc/ghc/-/issues/18550
https://gitlab.haskell.org/ghc/ghc/-/issues/18549

It's one of these?

**Comment by jneira** [comment]
@mouse07410 ooops, yeah,  i missed a digit in the copy paste, it is https://gitlab.haskell.org/ghc/ghc/-/issues/18550

**Pull request merged**
