### PR TITLE
Make Wingman produce user-facing error messages

### PR DESCRIPTION
**Pull request by isovector**
Wingman now sends `WindowShowMessage` notifications in the case of errors, significantly clearing up the confusion around "why didn't that code action do anything?"

### CODE REVIEW

**Comment by michaelpj** [comment]
I think there's the ability for most requests to return an error with a code and message in case something went wrong during the request (e.g. see at the bottom of the executeCommand docs: https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand).

It seems like this would be a better way to signal failure? And I think it lets you give a message too. Not sure how to do this in our library, though.

**Comment by isovector** [comment]
> result: `any | null`

what a type smh.

However, I'm currently returning the error as the response to the codeaction:

https://github.com/haskell/haskell-language-server/blob/19207ef2cfa260d7b7e0086aad76ded185a27a00/plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic.hs#L103

but it doesn't show any messages in either vscode or vim/coc.

**Comment by isovector** [comment]
@wz1000 chimes in from IRC:

```
│07:16:39    isovector | are there any LSP wizards? what's the right way to report a failing code action to the user?
│07:17:26       wz1000 | do you want the user to actually see the error?
│07:17:30    isovector | yes
│07:17:44       wz1000 | then 'showMessage'
```

**Review by wz1000 — APPROVED** [review]

**Comment by michaelpj** [comment]
Boo, that seems like a missed opportunity on the client side.

**Comment by michaelpj** [comment]
Y do people not think about the non-happy path??

**Pull request merged**
