### PR TITLE
Add license for hls-tactics-plugin

### PR DESCRIPTION
**Pull request by isovector**

### CODE REVIEW

**Review by Ailrun — COMMENTED** [review]
Thanks, could you also add the homepage and bug tracker?

**Comment by isovector** [comment]
TBH this is not currently a high priority to me. This PR was simply necessary to upload the package and it seemed a shame to have the two be out of sync.

**Review by Ailrun — APPROVED** [review]
OK, let's merge this then.

**Review by jneira — APPROVED** [review]
Thanks for the pr and for uploading the package to hackage: https://hackage.haskell.org/package/hls-tactics-plugin
The rest of fields could be added in a follow up if you consider (and edit the package metadata with a revision)
Btw, have you think in adding some other maintainer to agilize the process of uploads and changes in the future?

**Pull request merged**
