### PR TITLE
Remove an allow-newer

### PR DESCRIPTION
**Pull request by michaelpj**

### CODE REVIEW

**Comment by michaelpj** [comment]
Hmm, I bumped nixpkgs and now it needs too new a glibc for the GHA runners or something?

**Comment by fendor** [comment]
Now we don't test the nix environment any more? That's not ideal, I think the nix environments are useful and we should maintain them.

The GHA runners are quite annoying at times :sweat_smile:

**Comment by michaelpj** [comment]
It still tests that the nix environment _builds_. I don't know. GLIBC issues really suck and I'm not sure there's an easy solution. This is AFAIK the only way to get a dev shell setup with 9.8, for example :shrug:

**Review by fendor — APPROVED** [review]
Change itself looks good.

Let's hope someone who cares about the nix setup will eventually fix it.

**Pull request merged**
