### PR TITLE
Make the AGPL flag manual in cabal

### PR DESCRIPTION
**Pull request by fendor**
I honestly don't know what this entails and the documentation is hard to find but I think it fixes the problem described in https://github.com/haskell/vscode-haskell/issues/255

### CODE REVIEW

**Comment by pepeiborra** [comment]
Cabal automatically tries all the possible combinations of non-manual flags when solving, leaving manual flags at their default value. I think we really want this flag to be non-manual, otherwise the Cabal build will fail in 8.10.1 where Brittany is not available

**Comment by jneira** [comment]
yeah, auto makes cabal trying enable it to get a build plan so it must be manual

**Comment by fendor** [comment]
@pepeiborra Brittany wasn't included for me for ghc 8.8.3 either, which is weird, since the default is `true` and the build succeeds with Brittany on 8.8.3.

Also, if Brittany does not exist for 8.10.1 yet, we should, as suggested in https://github.com/haskell/vscode-haskell/issues/255, use a different default formatter, in my opinion.

**Comment by pepeiborra** [comment]
> yeah, auto makes cabal trying enable it to get a build plan so it must be manual

Really? I thought that cabal would use the default value first, and then if solving fails, try again with the negated default value if the flag is non manual.

**Comment by ndmitchell** [comment]
I have a lint check for my projects that all flags are set to Manual. I think of it was manual = for user. Otherwise = random hacks to encourage Cabal to find a build plan.

**Comment by pepeiborra** [comment]
> @pepeiborra Brittany wasn't included for me for ghc 8.8.3 either, which is weird, since the default is `true` and the build succeeds with Brittany on 8.8.3. Do you know why?
> 
> Also, if Brittany does not exist for 8.10.1 yet, we should, as suggested in [haskell/vscode-haskell#255](https://github.com/haskell/vscode-haskell/issues/255), use a different default formatter, in my opinion.

I have no idea why, but you can ask cabal. I agree that Brittany is not a good default in 8.10.1 !!

**Comment by jneira** [comment]
@pepeiborra the mysteries of the cabal plan algorithm are unfathomable 😝
Sometimes it choose a path with the flag enabled although there could be another one without cause the latter needs more steps.
In any case I would not let a tool activate agpl automatically (with little info to the user) cause it could suppose a serious problem in some contexts, gplphobics.
If we need to disable Brittany for other causes (mainly non buildable deps) we should use another dedicated flag, imo.

**Comment by Ailrun** [comment]
> Also, if Brittany does not exist for 8.10.1 yet, we should, as suggested in haskell/vscode-haskell#255, use a different default formatter, in my opinion.

I thought our default formatter is `ormolu`, as written here
https://github.com/haskell/haskell-language-server/blob/4fe0f7dfc1cac850a1a1a201fff41cdecc0fb7cf/src/Ide/Plugin/Config.hs#L66
Am I missing something?

**Comment by fendor** [comment]
@Ailrun the vscode plugin overrides this configuration

**Comment by Ailrun** [comment]
That's... surprising :open_mouth: Thank you for the answer :)

**Comment by bubba** [comment]
It is surprising indeed, I've opened up a PR on vscode-haskell to change the default to ormolu to match up. Unless anyone has a stronger preference for another default?

**Comment by ndmitchell** [comment]
I think avoiding AGPL/GPL for default things is wise - it isn't a typical Haskell license.

**Comment by fendor** [comment]
@bubba Should be merge this before or after #288 ?

**Comment by bubba** [comment]
@fendor Hm not sure, depends if we think we should actually include Brittany in the binaries in the first place. #288 also builds Brittany on 8.10.1 so some of the CPP flags will need changed

**Comment by fendor** [comment]
Exactly, we should coordinate. Whatever you decide in this is fine by me, but I would like to make this flag manual.

**Comment by bubba** [comment]
Ok we should merge this first then, this PR makes sense to me

**Pull request merged**
