### PR TITLE
Revert all changes to hie-compat since 11b5c2e

### PR DESCRIPTION
**Pull request by wz1000**

### CODE REVIEW

**Review by jneira — APPROVED** [review]
ok, I see this lib more similar to hls-plugin-api than ghc-exactprint but as you consider
only note that the change (specially the ghcide one) should be backported to 1.0.0-hackage

**Comment by Ailrun** [comment]
@Mergifybot backport 1.0.0-hackage

**Comment by Ailrun** [comment]
@Mergifyio backport 1.0.0-hackage

**Comment by jneira** [comment]
wow didnt know about that trick, sweet

**Pull request merged**
