### PR TITLE
nix: add support for ghc 9.0.1

### PR DESCRIPTION
**Pull request by berberman**
As discussed in https://github.com/haskell/haskell-language-server/issues/1871#issuecomment-859990650, this PR attempts to maintain a nix configuration that works for ghc 9.0.1. It's still work in progress, see the CI for results.

### CODE REVIEW

**Comment by anka-213** [comment]
It looks like it is trying to build `ghc-lib-parser-8.10.5` when compiling for ghc-9. I'm guessing that is the default version in nixpkgs. Maybe overriding with something like
```
ghc-lib-parser = hsuper.ghc-lib-parser_9_0_1_20210324;
```
would work?

**Comment by maralorn** [comment]
> (Or `hself` instead of `hsuper`? I never learned when to use which.)

My rule of thumb is this: Always use `hself` when you can, only use `hsuper` to break recursion cycles.

That mostly means use `foo = f hsuper.foo` but `bar = f hself.foo`.

Reasoning is that when you do `bar = f hself.foo`, there could be other overrides for `foo` in this or a subsequent overlay and you most likely want those overrides to apply to your new `bar`. You wouldn‘t get them from `hsuper.foo`.

**Comment by berberman** [comment]
Now both `nix build .#haskell-language-server-901` and `nix develop .#haskell-language-server-901-dev` work; I'm able to use HLS binary created by nix build to load HLS project in nix develop shell!

**Review by jneira — APPROVED** [review]
I am not a nix user but lgtm

**Pull request merged**
