### PR TITLE
Move Linux & Mac OS tests into the Nix GitHub action

### PR DESCRIPTION
**Pull request by pepeiborra**
Merge the Test Github Action into the Nix one, leaving the Windows tests on their own Github action.

Reasons:

- Avoid redundant work, saving 6 jobs. The CI is very heavily overloaded right now and every bit helps.
- The Nix caching seems much more reliable, taking only ~10m to build everything whereas the Test action takes >30m since Cabal rebuilds all the dependencies
- https://github.com/cachix/pre-commit-hooks.nix can be useful in the future

### CODE REVIEW

**Comment by jneira** [comment]
jumm not sure about this, in the past nix and Linux/macos had failed independently for different causes and afaik most Linux/macos users don't use nix for building but raw cabal/stack
I would investigate instead why cabal is rebuilding continuously deps, it should not do it (due precisely to the nix-style cache of v2 builds!)

**Comment by jneira** [comment]
and where are macos tests?

**Comment by pepeiborra** [comment]
@jneira the Nix job uses cabal install to build the project, just like the Test job definition does. 
The Nix job exists to validate that the Nix derivations are kept up to date when the project layout changes. The goal of this PR is to combine that check with the other checks in the Test job. This is a union, not an intersection, i.e. there is no loss of information involved.

**Comment by pepeiborra** [comment]
Actually, the Nix shell script does not offer caching for ghc versions other than the default one (ghc 8.10.1) and cannot do so, since the Nix haskell snapshot builds on the Stackage nightly snapshot, so it's not compatible with earlier ghc versions.

This means that the Nix action is not a good replacement (in terms of caching) for the Test action, so I'm dropping this PR

**Pull request closed without merging**
