### PR TITLE
Use bash shell to allow its idioms

### PR DESCRIPTION
**Pull request by jneira**
* The last test invocation fails otherwise

### CODE REVIEW

**Review by ndmitchell — APPROVED** [review]
No harm in requiring Bash on CI

**Comment by ndmitchell** [comment]
In fact, what requires bash? Is this going to impact end users?

**Comment by jneira** [comment]
@ndmitchell no effect on end users it is only for github actions:
if you dont set the default shell in the `run` step it is gonna use powershell in windows so if you use bash syntax like the actual one `LSP_TEST_LOG_COLOR=0 LSP_TEST_LOG_MESSAGES=true LSP_TEST_LOG_STDERR=true cabal test --test-options="-j1 --rerun"` is gonna fail.

**Comment by ndmitchell** [comment]
Ah, burn power shell to the ground - its error semantics are totally broken!

**Pull request merged**
