### PR TITLE
Remove .stack-work from circleci cache

### PR DESCRIPTION
**Pull request by jneira**
* From #2038
* Build times are close to having `.stack-work` and we avoid issues with conflicts in the linker phase 
  * https://app.circleci.com/pipelines/github/jneira/haskell-language-server/644/workflows/ba2d76ab-341b-4bb0-a2df-109a677878e2

### CODE REVIEW

**Review by isovector — APPROVED** [review]

**Comment by isovector** [comment]
Thanks for tackling this, @jneira !

**Comment by jneira** [comment]
hmm there are linker errors restoring only `.stack`

```
ghcide                           > Linking .stack-work/dist/x86_64-linux/Cabal-3.2.0.0/build/ghcide/ghcide ...
ghcide                           > /root/.stack/snapshots/x86_64-linux/a1bc97aaff04ad107ea7a2a7b8f35c0c3cf087643f08a1b7863fdd6cef371722/8.10.2/lib/x86_64-linux-ghc-8.10.2/libHSlsp-1.2.0.0-88sEO7ydde42BWhpz8ymRj-ghc8.10.2.so: error: undefined reference to 'lspzmtypeszm1zi2zi0zi0zm7swkqKT17rYKP1vpk3U7ry_LanguageziLSPziTypesziCallHierarchy_zdfFromJSONCallHierarchyOutgoingCallsParams_closure'
ghcide                           > /root/.stack/snapshots/x86_64-linux/a1bc97aaff04ad107ea7a2a7b8f35c0c3cf087643f08a1b7863fdd6cef371722/8.10.2/lib/x86_64-linux-ghc-8.10.2/libHSlsp-1.2.0.0-88sEO7ydde42BWhpz8ymRj-ghc8.10.2.so: error: undefined reference to 'lspzmtypeszm1zi2zi0zi0zm7swkqKT17rYKP1vpk3U7ry_LanguageziLSPziTypesziCallHierarchy_zdfFromJSONCallHierarchyIncomingCallsParams_closure'
ghcide                           > /root/.stack/snapshots/x86_64-linux/a1bc97aaff04ad107ea7a2a7b8f35c0c3cf087643f08a1b7863fdd6cef371722/8.10.2/lib/x86_64-linux-ghc-8.10.2/libHSlsp-1.2.0.0-88sEO7ydde42BWhpz8ymRj-ghc8.10.2.so: error: undefined reference to 'lspzmtypeszm1zi2zi0zi0zm7swkqKT17rYKP1vpk3U7ry_LanguageziLSPziTypesziCallHierarchy_zdfFromJSONCallHierarchyPrepareParams_closure'
ghcide                           > /root/.stack/snapshots/x86_64-linux/a1bc97aaff04ad107ea7a2a7b8f35c0c3cf087643f08a1b7863fdd6cef371722/8.10.2/lib/x86_64-linux-ghc-8.10.2/libHSlsp-1.2.0.0-88sEO7ydde42BWhpz8ymRj-ghc8.10.2.so: error: undefined reference to 'lspzmtypeszm1zi2zi0zi0zm7swkqKT17rYKP1vpk3U7ry_LanguageziLSPziTypesziMethod_zdfFromJSONSMethod54_closure'
ghcide                           > /root/.stack/snapshots/x86_64-linux/a1bc97aaff04ad107ea7a2a7b8f35c0c3cf087643f08a1b7863fdd6cef371722/8.10.2/lib/x86_64-linux-ghc-8.10.2/libHSlsp-1.2.0.0-88sEO7ydde42BWhpz8ymRj-ghc8.10.2.so: error: undefined reference to 'lspzmtypeszm1zi2zi0zi0zm7swkqKT17rYKP1vpk3U7ry_LanguageziLSPziTypesziMethod_zdfFromJSONSMethod55_closure'
ghcide                           > /root/.stack/snapshots/x86_64-linux/a1bc97aaff04ad107ea7a2a7b8f35c0c3cf087643f08a1b7863fdd6cef371722/8.10.2/lib/x86_64-linux-ghc-8.10.2/libHSlsp-1.2.0.0-88sEO7ydde42BWhpz8ymRj-ghc8.10.2.so: error: undefined reference to 'lspzmtypeszm1zi2zi0zi0zm7swkqKT17rYKP1vpk3U7ry_LanguageziLSPziTypesziMethod_STextDocumentPrepareCallHierarchy_con_info'
ghcide                           > /root/build/ghcide/.stack-work/dist/x86_64-linux/Cabal-3.2.0.0/build/libHSghcide-1.4.0.3-JawsZpB8LjFDgYoyr637bu-ghc8.10.2.so: error: undefined reference to 'lspzmtypeszm1zi2zi0zi0zm7swkqKT17rYKP1vpk3U7ry_LanguageziLSPziTypesziMethod_zdfShowSMethod114_closure'
ghcide                           > /root/build/ghcide/.stack-work/dist/x86_64-linux/Cabal-3.2.0.0/build/libHSghcide-1.4.0.3-JawsZpB8LjFDgYoyr637bu-ghc8.10.2.so: error: undefined reference to 'lspzmtypeszm1zi2zi0zi0zm7swkqKT17rYKP1vpk3U7ry_LanguageziLSPziTypesziMethod_zdfShowSMethod112_closure'
ghcide                           > /root/build/ghcide/.stack-work/dist/x86_64-linux/Cabal-3.2.0.0/build/libHSghcide-1.4.0.3-JawsZpB8LjFDgYoyr637bu-ghc8.10.2.so: error: undefined reference to 'lspzmtypeszm1zi2zi0zi0zm7swkqKT17rYKP1vpk3U7ry_LanguageziLSPziTypesziMethod_zdfShowSMethod116_closure'
ghcide                           > collect2: error: ld returned 1 exit status
ghcide                           > `gcc' failed in phase `Linker'. (Exit code: 1
```

maybe we would need to switch to static linking again

**Comment by jneira** [comment]
And.... memory exhustion returned again

```
hls-floskell-plugin        > collect2: fatal error: ld terminated with signal 9 [Killed]
hls-floskell-plugin        > compilation terminated.
hls-floskell-plugin        > `gcc' failed in phase `Linker'. (Exit code: 1)
```

**Comment by jneira** [comment]
errr... we are bulding tests twice!!!???

stack test is a `Shortcut for 'build --test'` and we are doing `stack -j1 --stack-yaml=${STACK_FILE} build --test --no-run-tests --no-terminal` and then `stack --stack-yaml=${STACK_FILE} test --no-run-tests --no-terminal`, but without `-j1`!!! omg :facepalm:

**Comment by Ailrun** [comment]
What happened to GitHub Actions? It is stuck for a while, and those "pending" jobs show
> Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'windows-latest'
Waiting for a self-hosted or a hosted runner to pickup this job...

**Comment by jneira** [comment]
don't know and don't know if I want to know it 😂

hope it is transient and we will not have to worry about. I ve rerun the test job, let's see how is going

**Comment by Ailrun** [comment]
Seems like rerun makes it work... Hm :/

**Pull request merged**
