### PR TITLE
Bump to hiedb 0.5.0.0 to fix #3542

### LINKED ISSUE #3542: SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed: defs.hieFile, defs.occ
### Your environment

* Which OS do you use?
Fedora 37

* Which version of GHC do you use and how did you install it?
GHC 9.4.4 via ghcup

* How is your project built (alternative: link to the project)?
cabal

* Which LSP client (editor/plugin) do you use?
Neovim + nvim_lsp

* Which version of HLS do you use and how did you install it?
1.9.1.0 via ghcup

### Expected behaviour

I get this message:

```
LSP[hls] Error condition, please check your setup and/or the [issue tracker](https://github.com/haskell/haskell-language-server/issues): 
HieDb writer thread SQLite error:
  SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed: defs.hieFile, defs.occ
```

### PR DESCRIPTION
**Pull request by wz1000**

### CODE REVIEW

**Review by michaelpj — APPROVED** [review]

**Comment by michaelpj** [comment]
Looks like genuine build failures though.

**Comment by michaelpj** [comment]
Stuff seems quite broken.

**Comment by peterbecich** [comment]
closes: #3542 #3945

**Comment by peterbecich** [comment]
I see this requires `hiedb` 0.5.0.1

NixPkgs `haskell-updates` is still on 0.5.0.0
```
$ nix search nixpkgs/haskell-updates#haskellPackages hiedb
* legacyPackages.x86_64-linux.haskellPackages.hiedb (0.5.0.0)
  Generates a references DB from .hie files
```
is that an issue?

**Comment by michaelpj** [comment]
HLS master is often on the bleeding edge of hackage, so yeah, we're going to be ahead.

**Comment by michaelpj** [comment]
Index state bump was maybe not enough? Cabal isn't finding the new version

**Comment by wz1000** [comment]
I think some jobs just started too early to pick up the hackage update.

**Pull request merged**
