### PR TITLE
Test hls-pragmas-plugin in ci

### PR DESCRIPTION
**Pull request by jneira**
Dont know why it is not here :facepalm:

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2530"></a>

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
This probably needs to be documented in the plugin cycle.

(checked - it is there).

**Review by Anton-Latukha — APPROVED** [review]

**Comment by jneira** [comment]
yeah, it seems it was not added in https://github.com/haskell/haskell-language-server/pull/1833

another thing to document in the contributing guide :sweat_smile:

**Comment by Anton-Latukha** [comment]
Yes, it is there. But may be made more memorable.

Also this probably can be automatically checked in the CI.

For example - is there is a new folder in the `plugins` - the `test` workflow also is required to be changed.

**Comment by Anton-Latukha** [comment]
Opened #2531 for this.

**Comment by Anton-Latukha** [comment]
[skip circleci]

**Comment by jneira** [comment]
wow, tests passed, i was afraid they were bitrotten :sweat_smile:

**Pull request merged**
