### PR TITLE
Add ghc-8.10.3 support after merging ghcide repo

### PR DESCRIPTION
**Pull request by jneira**
* Let's see how is going

### CODE REVIEW

**Comment by jneira** [comment]
ci behaves like the previous pr so i would release this one

**Comment by alanz** [comment]
> ci behaves like the previous pr so i would release this one

Sounds good to me.

**Comment by pepeiborra** [comment]
I'm very reluctant to add more GitHub Actions, the CI is already completely overwhelmed. Is there anything we can drop in exchange?

**Review by Ailrun — APPROVED** [review]
Looks good.
BTW, I also agree with @pepeiborra in that CI is already overwhelmed. It might be better to find some optimizable parts in CI.

**Comment by alanz** [comment]
FYI, there was a chat on IRC with @bgamari about hosting CI on the GHC infrastructure.  Something we should explore.

**Comment by jneira** [comment]
> I'm very reluctant to add more GitHub Actions, the CI is already completely overwhelmed. Is there anything we can drop in exchange?

only tests last minor version in gh f.e.

**Comment by bgamari** [comment]
The CI issue is being discussed in #780 .

**Comment by jneira** [comment]
ci is green! we will use master with this for the next release if nobody disagree

**Pull request merged**
