### PR TITLE
Add custom code action kinds for import related code actions

### LINKED ISSUE #1556: Add LSP kinds to "import" code actions
The current "import" code actions are pretty overwhelming, especially for commonly used names. We get the cartesian product of `matches` x `styles`.

I'd like to suggest we export `import Foo.Blah` under the kind `quickfix.import.module` and `import Foo.Blah (what)` under `quickfix.import.definition`. Users can then opt-in to their preferred style, and users/clients who don't care will still see today's behavior.

### PR DESCRIPTION
**Pull request by berberman**
Closes #1556

Suggestions are welcome! /cc @isovector 

Several examples:

| Code Action Title                                | Before                    | After                                       | Code Action Kind                          |
| ------------------------------------------------ | ------------------------- | ------------------------------------------- | ----------------------------------------- |
| Add stuffA to the import list of ModuleA         | `import ModuleA (stuffB)` | `import ModuleA (stuffB, stuffA)`           | `quickfix.import.extend.thing.topLevel`   |
| Add A to the import list of ModuleA              | `import ModuleA ()`       | `import ModuleA (A)`                        | `quickfix.import.extend.thing.topLevel`   |
| Add A(Constructor) to the import list of ModuleA | `import ModuleA (A)`      | `import ModuleA (A (Constructor))`          | `quickfix.import.extend.thing.withParent` |
| import Bar (Bar)                                 |                           | `import Bar (Bar)`                          | `quickfix.import.new.thing.topLevel`      |
| import Bar (Bar(Bar))                            |                           | `import Bar (Bar(Bar))`                     | `quickfix.import.new.thing.withParent`    |
| import Numeric.Natural                           |                           | `import Numeric.Natural`                    | `quickfix.import.new.all`                 |
| import qualified Data.List.NonEmpty as NE        |                           | `import qualified Data.List.NonEmpty as NE` | `quickfix.import.new.qualified`           |

### CODE REVIEW

**Comment by pepeiborra** [comment]
Just a minor nitpick, I would prefer `list` instead of `thing` for the imports that extend or create an import list, eg. `quickfix.import.extend.list.topLevel` and `quickfix.import.new.list.toplevel`

**Review by pepeiborra — APPROVED** [review]

**Comment by isovector** [comment]
This is marvelous, thanks so much!

**Review by isovector — APPROVED** [review]

**Comment by pepeiborra** [comment]
@berberman we should document these names in the read me and add instructions on how to use them

**Comment by berberman** [comment]
Yeah, and I think we should document all ghcide code actions in some place

**Comment by michaelpj** [comment]
:+1: for documenting all these as they come up.

One thing that occurs to me with the naming: it would be nice if the kind and the message sort of had the same structure and terminology? Let me show what I mean:

| kind | current | suggestion |
|-|-|-|
| quickfix.import.extend.list.topLevel | Add stuffA to the import list of ModuleA | Import: extend the import list of ModuleA with the top-level entity stuffA |
| quickfix.import.extend.list.withParent | Add A(Constructor) to the import list of ModuleA | Import: extend the import list of ModuleA with the entity Constructor and its parent A |
| quickfix.import.new.thing.topLevel | import Bar (Bar) | Import: add a new import importing the top-level entity Bar |

etc.

At the moment there's a sort of implicit translation of terminology that users have to do: "add to import list" -> "extend"; "<description of import statement>" -> "create a new import"; "top-level" and "withParent" aren't used in those ways.

**Comment by pepeiborra** [comment]
@berberman we are very close to having full import management on save, the main thing missing is "remove redundant import", which did not get a custom kind in this PR.

**Pull request merged**
