### PR TITLE
flake: remove the 'follows' directive

### PR DESCRIPTION
**Pull request by teto**
nixFlake suffers from a bug when using "follows" keyword:
https://github.com/NixOS/nix/issues/3602

I think the (possibly) extra-downloads is worth having the peace of mind that it always works.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2218"></a>

### CODE REVIEW

**Review by berberman — CHANGES_REQUESTED** [review]
We have to make sure that formatters in pre-commit hooks are consistent (#1408), so I think the follow of nixpkgs is required. For flake-utils, I agree with removing that follow.

**Comment by teto** [comment]
the "follow" is broken in nix which means I can't use the flake without a fork. 

Alternatively, could we :
- fork pre-commit-hook so that we can manually make sure  they use the same nixpkgs version as hls ?
- override stylish-haskell in the pre-commit flake with the one from hls' overlay ?

**Comment by berberman** [comment]
> fork pre-commit-hook so that we can manually make sure they use the same nixpkgs version as hls

I don't think that's a good idea, since it causes extra maintenance

> override stylish-haskell in the pre-commit flake with the one from hls' overlay

Actually we already do this: https://github.com/haskell/haskell-language-server/blob/48221c7ed1db4dd992391a0b4ba1e304e05da5d9/flake.nix#L137

So maybe we don't need "follow" nixpkgs at all, and this PR may work. Could you try executing the pre-commit hook?

**Comment by teto** [comment]
`stylish-haskell --version`  gives me `stylish-haskell 0.12.2.0`.
If I trigger the hook. It works correctly but not sure how to check it uses the same version.

**Review by berberman — APPROVED** [review]
Thanks for confirming, then we are good to go

**Pull request merged**
