### PR TITLE
Extract stylish-haskell plugin into a standalone package

### PR DESCRIPTION
**Pull request by berberman**
Following #1422

### CODE REVIEW

**Review by pepeiborra — APPROVED** [review]
Nice, thank you!

**Comment by prikhi** [comment]
This commit broke formatting w/ stylish-haskell for me(via coc.nvim). 

On this commit, launching HLS w/ `-d` doesn't show `PluginId "stylish-haskell"` in `LspArguments` plugin list. On the commit before this one, it does.

**Comment by berberman** [comment]
Hi, thanks for the bug report! I just realized that `cpp-options: -D` was removed accidently from common stanza, so the plugin was not actually wired in HLS. I'm afraid brittany plugin had the same problem. /cc @pepeiborra

**Comment by prikhi** [comment]
hehe, I just submitted a PR w/ the same fix :stuck_out_tongue: 
https://github.com/haskell/haskell-language-server/pull/1620

**Pull request merged**
