### PR TITLE
CI: cabal 3.6 use & clean-up 8.10.5 builds

### PR DESCRIPTION
**Pull request by Anton-Latukha**
Gradually submitting #2427

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2443"></a>

### CODE REVIEW

**Review by jneira — APPROVED** [review]
great, thanks for the update and cleaning up

**Comment by Anton-Latukha** [comment]
That is basically the first merge.

Then - the standardization of the bootstrapping.
Then caching.

**Comment by jneira** [comment]
> That is basically the first merge.
> 
> Then - the standardization of the bootstrapping. Then caching.

The plan sounds good, is this one ready to merge?

**Comment by Anton-Latukha** [comment]
I was waiting for CI to pass before marking it as ready. To not distract you.

**Comment by jneira** [comment]
I just was preparing the pr to drop support for 8.10.5 and 8.8.3 but dont worry at all, will merge this and rebase mine: #2444

**Comment by Anton-Latukha** [comment]
Ok.

Doc is understandable.

Would fix doc wording in the next PR.

**Pull request merged**
