### PR TITLE
Miscellaneous fixes

### PR DESCRIPTION
**Pull request by berberman**
Retrie plugin is missing in hie.yaml.cbl, and tactics plugin's cabal file contains some invalid links.
BTW, I don't think `.cbl` is a good filename extension, since github would consider it as a COBOL source file :P

### CODE REVIEW

**Comment by jneira** [comment]
> BTW, I don't think .cbl is a good filename extension, since github would consider it as a COBOL source file :P

agree, maybe `.cabal` would be better, but it is used for cabal package config so :shrug:

**Review by jneira — APPROVED** [review]
thanks for the fixes, i'll wait for @isovector review for tactic plugin changes

**Comment by berberman** [comment]
And tactics plugin needs a LICENSE file :)

**Comment by jneira** [comment]
what about `stack.hie.yaml` and `cabal.hie.yaml` (or something alike)?

**Comment by berberman** [comment]
Agree, editors would treat these files as yaml properly.

**Comment by jneira** [comment]
@berberman nice, do you mind include that file renaming in this pr or do you think is better to left it for a new one?

**Comment by jneira** [comment]
The readme should be updatet too (if we change file names):

https://github.com/haskell/haskell-language-server/blob/3717653f293b5789de7f8056d0f147b85ba2d58d/README.md#L688

**Comment by berberman** [comment]
> @berberman nice, do you mind include that file renaming in this pr or do you think is better to left it for a new one?

I prefer to including it in this PR, just as the title said XD

**Comment by berberman** [comment]
We shoud do the same thing to ghcide :)

**Comment by jneira** [comment]
I think tactic plugin cabal config values was set thinking it would be in a separate repo so i think we could remove it until that move is actually done.
So i am gonna merge it to include in the next release, we always could revert bab10e8 
//cc @isovector

**Review by jneira — APPROVED** [review]
thanks (again :slightly_smiling_face: )!

**Review by Ailrun — APPROVED** [review]
LGTM!

**Review by jneira — APPROVED** [review]

**Review by isovector — APPROVED** [review]

**Pull request merged**
