### PR TITLE
Remove unused config in hls-class-plugin

### PR DESCRIPTION
**Pull request by July541**
While looking on #3105, I found type lens itself has a config filed, see `haskell-language-server generate-default-config`

Remove a duplicate one, although I don't know where is the another one from now.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3107"></a>

### CODE REVIEW

**Comment by michaelpj** [comment]
I'm slightly confused, I think we probably *do* want a config field for the lenses? Or are there currently two or something?

**Comment by July541** [comment]
Currently we have two config fields for lens,  `haskell-language-server generate-default-config` shows
```
"class": {
                "codeActionsOn": true,
                "codeLensOn": true,
                "config": {
                    "typelensOn": true
                }
            },
```

Turns out `codeLensOn` and `typelensOn` are the same one.

**Comment by michaelpj** [comment]
Huh, do we generate a generic config option for any plugin that provides code lenses? That's pretty cool.

**Comment by July541** [comment]
> Huh, do we generate a generic config option for any plugin that provides code lenses? That's pretty cool.

Obviously, it does! Although I don't know where the code is due to time limitation.

**Comment by michaelpj** [comment]
@berberman ?

**Comment by michaelpj** [comment]
Dumb question: does the other config option work? Can we keep the test and use the generic config option? Or maybe we can trust it, I'm just suspicious.

**Comment by July541** [comment]
Both `codeLensOn` and `typelensOn` are available.

>  Can we keep the test and use the generic config option?

It's better if we can. I tried to find how to write the config, but failed as I said.

> Or maybe we can trust it

It's ok I think, all of our plugins don't have tests for main ability.

**Comment by berberman** [comment]
> @berberman ?

Yes: https://github.com/haskell/haskell-language-server/blob/e55004a0cc9b727423a16cec4f5103a4df685eb6/hls-plugin-api/src/Ide/Plugin/ConfigUtils.hs#L84-L94

So I think we no longer need the `typelensOn` in this case.

**Comment by michaelpj** [comment]
We really need to document how this stuff works...

**Review by michaelpj — APPROVED** [review]

**Comment by July541** [comment]
We should have a tech doc to land our tech details while developing hls, but not sure what should be included yet.

**Pull request merged**
