### PR TITLE
ghc-check 0.4 for hls

### PR DESCRIPTION
**Pull request by kakkun61**
Use newer version of ghc-check.

### CODE REVIEW

**Comment by pepeiborra** [comment]
See also https://github.com/digital-asset/ghcide/pull/568

**Comment by jneira** [comment]
Thanks for the pr! Some comments

*  ci stack builds are failing with:
```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: ghcide-0.1.0 (user goal)
[__1] trying: ghcide:-ghc-lib
[__2] next goal: ghc-check (dependency of ghcide -ghc-lib)
[__2] rejecting: ghc-check-0.4.0.0 (conflict: ghcide -ghc-lib =>
ghc-check>=0.3.0.1 && <0.4)
[__2] trying: ghc-check-0.3.0.1
[__3] next goal: haskell-language-server (user goal)
[__3] rejecting: haskell-language-server-0.1.0.0 (conflict:
ghc-check==0.3.0.1, haskell-language-server => ghc-check>=0.4)
[__3] fail (backjumping, conflict set: ghc-check, haskell-language-server)
```
`stack-*.yaml` files should be updated to use the new version

* As pointed out by @pepeiborra the ghcide changes should be merged/rebased to leverage the new ghc-check version
** Not sure if actual changes improve the actual check, if it is so we could integrate those changes thereafter

**Comment by kakkun61** [comment]
OK, I'll wait for the merging/rebasing of ghcide.

**Comment by fendor** [comment]
This would be nice to do now.
There has been already a release of ghc-check 0.5.0.1

**Comment by kakkun61** [comment]
ghc-check 0.5.0.1 is already supported on master.

**Pull request closed without merging**
