### PR TITLE
Prefer Data.HashSet.member to Data.Foldable.elem

### PR DESCRIPTION
**Pull request by sergv**

### CODE REVIEW

**Review by fendor — APPROVED** [review]
LGTM, thanks!

**Comment by pepeiborra** [comment]
What is the motivation to prefer `HashSet.member` over `Data.Foldable.elem`?

**Comment by jhrcek** [comment]
`HashSet.member` is `O(log n)` wherease `Data.Foldable.elem` needs to traverse the whole structure (at best linear in number of elements). For example relude even uses type errors to warn you about using elem with sets: https://hackage.haskell.org/package/relude-1.0.0.1/docs/Relude-Foldable-Fold.html#v:elem

**Comment by pepeiborra** [comment]
> I suspect it's because `HashSet.member` is `O(log n)` whereas `Data.Foldable.elem` needs to traverse the whole structure (at best linear in number of elements). For example relude even uses type errors to warn you about using elem with sets: https://hackage.haskell.org/package/relude-1.0.0.1/docs/Relude-Foldable-Fold.html#v:elem

Fair enough, `elem` lacks `Hashable` powers so it cannot do anything smart

**Comment by sergv** [comment]
Indeed, `elem` is linear since it must work with only `Eq` constraint.

**Pull request merged**
