### PR TITLE
Join nested IO actions of the form `IO (IO ())`

### PR DESCRIPTION
**Pull request by fendor**
I think these are some accidental remnants of #2434. 

Nothing broke for me, I just reviewed code and noticed the type of `invalidateShakeCache` was inferred to `IO (IO ())`.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2459"></a>

### CODE REVIEW

**Review by jneira — APPROVED** [review]
thanks for the clean up

**Comment by pepeiborra** [comment]
Are there any warnings that could have prevented this?

**Comment by michaelpj** [comment]
Isn't there a warning saying a do-block expression is discarding a result? I'd have expected that to fire here.

**Comment by fendor** [comment]
> Isn't there a warning saying a do-block expression is discarding a result? I'd have expected that to fire here.

Yeah, same, but it didn't. No idea why not.

**Comment by fendor** [comment]
We can use `-Wunused-do-bind`, will try it out.

**Comment by jneira** [comment]
> I thought we are already using `-Wunused-do-bind`, but maybe we aren't, I'll give it a try.

In this pr? or could we merge it?

**Comment by fendor** [comment]
Really weird, no usage of `-Wunused-do-bind` works on ghcide, but it works in my example project... 

image

This is interesting. I don't know what is going on.

**Comment by fendor** [comment]
Let's look into some more details before merging, imo.

**Comment by fendor** [comment]
Very interesting: 
image

**Comment by fendor** [comment]
I don't understand, copying that code to another project highlights correctly both occurrences. Even deleting everything except these two functions doesnt work for me, i.e. still shows only one warning.

**Comment by pepeiborra** [comment]
I found it: it's `ApplicativeDo`, which is enabled in `ghcide.cabal`. Please disable it @fendor since it doesn't make any difference with hls-graph anymore.

**Review by pepeiborra — APPROVED** [review]
Thanks for catching this!

**Pull request merged**
