### PR TITLE
Preserve the last empty comment line after eval plugin

### PR DESCRIPTION
**Pull request by expipiplus1**
```haskell
-- >>> foo
--
-- >>> bar
```

After running the plugin on both prompts we end up with this:

```haskell
-- >>> foo
-- foo_output
--
-- >>> bar
-- bar_output
```

instead of

```haskell
-- >>> foo
-- foo_output
-- >>> bar
-- bar_output
```

### CODE REVIEW

**Review by Ailrun — COMMENTED** [review]
Could you please provide some rationals for this change?

**Comment by expipiplus1** [comment]
> Could you please provide some rationals for this change?

Sure, I often have code of the form

```haskell
-- >>> doctest1
-- result
--
-- >>> doctest2
-- result2
myFunction :: _
```

When I use the eval plugin the pleasing space between the doctests is removed.

**Review by pepeiborra — APPROVED** [review]
lgtm

**Comment by pepeiborra** [comment]
Thanks Joe!

**Pull request merged**
