### PR TITLE
Give plugins descriptions, include versions of key dependencies 

### PR DESCRIPTION
**Pull request by michaelpj**
Some steps towards https://github.com/haskell/haskell-language-server/issues/3660

Output of `--list-plugins` now looks like this:
```
LSPRecorderCallback:                                                                                                                                                                                                                                                                                                       
    Internal plugin                                                                                                                                                                                                                                                                                                        
alternateNumberFormat:                                                                                                                                                                                                                                                                                                     
    Provides code actions to convert numeric literals to different formats                                                                                                                                                                                                                                                 
cabal:                                                                                                                                                                                                                                                                                                                     
    Provides a variety of IDE features in cabal files                                                                                                                                                                                                                                                                      
cabal-fmt:                                                                                                                                                                                                                                                                                                                 
    Provides formatting of cabal files with cabal-fmt                                                                                                                                                                                                                                                                      
callHierarchy:                                                                                                                                                                                                                                                                                                             
    Provides call-hierarchy support in Haskell                                                                                                                                                                                                                                                                             
changeTypeSignature:                                                                                                                                                                                                                                                                                                       
    Provides a code action to change the type signature of a binding if it is wrong                                                                                                                                                                                                                                        
class:                                                                                                                                                                                                                                                                                                                     
    Provides code actions and lenses for working with typeclasses                                                                                                                                                                                                                                                          
codeRange:                                                                                                                                                                                                                                                                                                                 
    Provides selection and folding ranges for Haskell                                                                                                                                                                                                                                                                      
eval:                                                                                                                                                                                                                                                                                                                      
    Provies a code lens to evaluate expressions in doctest comments                                                                                                                                                                                                                                                        
explicit-fields:                                                                                                                                                                                                                                                                                                           
    Provides a code action to make record wildcards explicit                                                                                                                                                                                                                                                               
explicit-fixity:                                                                                                                                                                                                                                                                                                           
    Provides fixity information in hovers                                                                                                                                                                                                                                                                                  
floskell:                                                                                                                                                                                                                                                                                                                  
    Provides formatting of Haskell files via floskell. Built with floskell-0.10.8                                                                                                                                                                                                                                          
fourmolu:                                                                                                                                                                                                                                                                                                                  
    Provides formatting of Haskell files via fourmolu. Built with fourmolu-0.14.0.0                                                                                                                                                                                                                                        
gadt:                                                                                                                                                                                                                                                                                                                      
    Provides a code action to convert datatypes to GADT syntax                                                                                                                                                                                                                                                             
ghcide-code-actions-bindings:
    Provides various quick fixes for bindings
ghcide-code-actions-fill-holes:
    Provides a code action to fill a hole
ghcide-code-actions-imports-exports:
    Provides various quick fixes
ghcide-code-actions-type-signatures:
    Provides various quick fixes for type signatures
ghcide-completions:
    Provides Haskell completions
ghcide-core:
    Handles basic notifications for ghcide
ghcide-extend-import-action:
    Provides a command to extend the import list
ghcide-hover-and-symbols:
    Provides core IDE features for Haskell
ghcide-type-lenses:
    Provides code lenses type signatures
hlint:
    Provides HLint diagnostics and code actions. Built with hlint-3.6.1
importLens:
    Provides a code action to make imports explicit
moduleName:
    Provides a code action to alter the module name if it is wrong
ormolu:
    Provides formatting of Haskell files via ormolu. Built with ormolu-0.7.2.0 
overloaded-record-dot:
    Provides a code action to convert record selector usage to use overloaded record dot syntax
pragmas-completion:
    Provides completion of LANGAUGE pragmas
pragmas-disable:
    Provides a code action to disable warnings
pragmas-suggest:
    Provides a code action to add missing LANGUAGE pragmas
qualifyImportedNames:
    Provides a code action to qualify imported names
rename:
    Provides renaming of Haskell identifiers
retrie:
    Provides code actions to inline Haskell definitions
splice:
    Provides a code action to evaluate a TemplateHaskell splice
stan:
    Provides stan diagnostics. Built with stan-0.1.1.0
stylish-haskell:
    Provides formatting of Haskell files via stylish-haskell. Built with stylish-haskell-0.14.5.0
```

### CODE REVIEW

**Review by joyfulmantis — APPROVED** [review]
LGTM

**Review by konn — APPROVED** [review]
LGTM as for Splice Plugin!

**Review by fendor — APPROVED** [review]
Nice improvement, LGTM!

**Comment by michaelpj** [comment]
Okay, let's give this a try. I'm going to take a stab at the disabled status thing too, so hopefully we'll be able to tell people to run `--list-plugins` to get a summary of what they've got!

**Pull request merged**
