### PR TITLE
Use exact print to extend import lists

### PR DESCRIPTION
**Pull request by berberman**
Rework https://github.com/haskell/ghcide/pull/942

Things to do:
* [x] Replace `mkVarName`  and `mkTcClsName`  with `parseIdentifier`
* [x] Compatible with multiple GHC versions
* [x] Apply changes to CodeAction.hs
* [x] Make tests pass

### CODE REVIEW

**Comment by berberman** [comment]
Parsed source returned by `GetAnnotatedParsedSource` does not preserve comments, so rewriting may cause stripping of inline comments. 

@pepeiborra Can I change the following  `GetParsedModule` to `GetParsedModuleWithComments` ?  https://github.com/haskell/haskell-language-server/blob/fdb8e5d6b9291b73e6e4038ffa59c65dbae792d4/ghcide/src/Development/IDE/GHC/ExactPrint.hs#L80

**Review by pepeiborra — APPROVED** [review]
Fantastic work, thank you so much!

**Comment by berberman** [comment]
Hmm, the test suite of eval plugin failed again and again...

**Comment by pepeiborra** [comment]
@berberman with this change and a bit more work I think we can restore the work that @gdevanla did to automatically extend imports on completions. Do you or @gdevanla already plan to do it?

**Comment by gdevanla** [comment]
I have been busy and have not caught up with many things that have happened since last month. I know @pepeiborra had to disable extending imports.  I can take a look at it if @berberman has not already done any work on that.

**Comment by berberman** [comment]
@pepeiborra I'm not familiar with code responsible for completions, and have not investigated yet. So please let @gdevanla to do that.

**Comment by pepeiborra** [comment]
@gdevanla @berberman I was actually planning to look at it today, was just checking that no one else was already working on it.

**Pull request merged**
