### PR TITLE
Rebase on ghcide HEAD

### PR DESCRIPTION
**Pull request by pepeiborra**
To improve the ergonomics of HLS plugin development. 

I also picked the -Werror and Open imports PRs

### CODE REVIEW

**Comment by pepeiborra** [comment]
I'm not sure what's the best way to upgrade the ghcide submodule, so let me know if there is a better way.

**Comment by wz1000** [comment]
I rebased hls-3 on ghcide master a few days ago, that should include these commits.

**Comment by wz1000** [comment]
Rebased once again. Alternatively, we can just move to ghcide HEAD now, and I will prepare a PR with the remaining changes there.

/cc @alanz

**Comment by pepeiborra** [comment]
Can you push hls-3 to haskell/ghcide and I'll repoint this PR there?

**Comment by wz1000** [comment]
Done.

**Pull request merged**
