### PR TITLE
Merge ghcide repository (replacing the submodule)

### PR DESCRIPTION
**Pull request by pepeiborra**
The merge was performed using the command:

     git merge ghcide/merge --allow-unrelated-histories

I have extended the Github CI to run the ghcide fmt, test and benchmark scripts. 

The next step will be to transfer all the GitHub Issues

### CODE REVIEW

**Comment by jneira** [comment]
wow, 68 total jobs (and dropping azure ones from ghcide), i think ci times will be worse, but we could try to cut some jobs afterwards

**Review by ndmitchell — APPROVED** [review]
Reviewed the concept, impossible to review the details. Good luck!

**Comment by jneira** [comment]
I am afraid all issues and prs with `#` referenced in ghcide commits are being linked to hls ones. It is a minor caveat and rewrite those commits would be cumbersome, though.

**Review by jneira — APPROVED** [review]
Thanks for going forward with this.
Do you prefer to merge it asap or maybe we could wait to make a hls release with support for ghc-8.10.3?

**Comment by wz1000** [comment]
How difficult will it be to rebase ghcide PRs against this? There are two big ones that are still open.

**Comment by pepeiborra** [comment]
> How difficult will it be to rebase ghcide PRs against this? There are two big ones that are still open.

You can find out right now by rebasing on top of the merge branch in the ghcide repo and then cherry picking from the hls repo

**Comment by pepeiborra** [comment]
> Thanks for going forward with this.
> 
> Do you prefer to merge it asap or maybe we could wait to make a hls release with support for ghc-8.10.3?

Do the 8.10.3 release. It will take a few days to get this PR merged anyway.

**Comment by pepeiborra** [comment]
@jneira this is going to be ready tonight. What's the status of the 8.10.3 release?

**Comment by pepeiborra** [comment]
@jneira this is ready to merge. Is there any reason not to do the 8.10.3 release from a branch?

**Comment by jneira** [comment]
mmm really no, I would prefer to release from master, to not have to keep the branch forever (if you want the exact history of the release, to bisect or whatever)
maybe it is possible without keeping the branch, my git foo is not great.

but I think the save of time for this "little maneavour" could worth it

**Comment by jneira** [comment]
we can try to make the release on top of this and fallback to the branch if there are problems

**Comment by pepeiborra** [comment]
@jneira it is standard practice to make point releases from release branches. I don't think that keeping the branch forever has any real downsides. 

If the 8.10.3 release is made from master it will include the changes in this PR (a ghcide version bump) as well as all the other changes in master: the reworked Eval plugin, the new Class plugin, etc.

**Comment by mpickering** [comment]
Is the plan to still keep `ghcide` usable as a light-weight tool? I still prefer using it over hls which is too bloated for my tastes.

**Comment by jneira** [comment]
Well, create release branches usually is related with a workflow where you are willing to create bug fix releases on them, and that is not our workflow for now.

And consistency matters, if you can trace all releases on master you will be surprised by that one.

But I am not strongly against, let's merge it and I will link in the release the branch used one

**Comment by jneira** [comment]
@mpickering you can now get a slimmed down version of hls, with no plugins or formatters:
```
cabal install -f-all-plugins -f-all-formatters
```
and you can add plugins one by one with
```
cabal install -f-all-plugins -f-all-formatters -f+eval ...
```
as described in https://github.com/haskell/haskell-language-server/issues/164#issuecomment-747428986

**Comment by pepeiborra** [comment]
> Is the plan to still keep `ghcide` usable as a light-weight tool? I still prefer using it over hls which is too bloated for my tastes.

`ghcide` stays around, yes. The goal here is to merge the git repos, not to retire ghcide.

But you know that HLS now has cabal flags to select which plugins get linked, so why not use that?

**Pull request merged**
