### PR TITLE
Bump ghcide to wz1000/hls-2 latest

### PR DESCRIPTION
**Pull request by alanz**
At commit cc09b6d4cf03efa645c682347c62850c2291be25

### CODE REVIEW

**Comment by jneira** [comment]
Not sure if it is related with this bump, but i get this error when opening hls itself:
```
[client] run command: "haskell-language-server-wrapper --lsp"
[client] debug command: "haskell-language-server-wrapper --lsp -d -l C:\TEMP\hls.log"
[client] server cwd: undefined
ghcide version: 0.1.0.0 (GHC: 8.8.3) (PATH: D:\bin\haskell-language-server-wrapper.exe)
ghcide version: 0.1.0.0 (GHC: 8.8.3) (PATH: D:\bin\haskell-language-server-8.8.3.exe)
Starting (haskell-language-server)LSP server...
  with arguments: Arguments {argLSP = True, argsCwd = Nothing, argFiles = [], argsVersion = False, argsShakeProfiling = Nothing, argsTesting = False, argsExamplePlugin = False, argsDebugOn = True, argsLogFile = Just "C:\\TEMP\\hls.log", argsThreads = 0}
  with plugins: [PluginId "brittany",PluginId "floskell",PluginId "ghcide",PluginId "ormolu",PluginId "pragmas",PluginId "stylish-haskell"]
If you are seeing this in a terminal, you probably should have run ghcide WITHOUT the --lsp option!
 Started LSP server in 0.08s
Data.HashMap.Base.(!): key not found
CallStack (from HasCallStack):
  error, called at .\\Data\\HashMap\\Base.hs:733:16 in unordered-con_-0.2.11.0-09d3bcadcbbc35431f4f2b870445379868b957e4:Data.HashMap.Base
  !, called at src\Development\IDE\Import\DependencyInformation.hs:107:40 in ghcide-0.2.0-f48ca2d7a046601fa7ce760c0ae0c1852d7fc5e2:Development.IDE.Import.DependencyInformation
> Build profile: -w ghc-8.8.3 -O1
> In order, the following will be built (use -v for more details):
>  - ghcide-0.2.0 (lib) (file src\Development\IDE\Core\Rules.hs changed)
> Preprocessing library for ghcide-0.2.0..
```
The server responds to client request, including hover, though
Otoh files are loaded amazingly fast 😮

**Comment by 1Computer1** [comment]
@jneira I've gotten that same error since 26892d6d8fa411803f58ca87b463c8a434df33e2 at least.

**Comment by alanz** [comment]
I am going to merge this, @jneira can you create a fresh issue for your reported problem?

**Comment by wz1000** [comment]
I know about that error. It should happen much less with this bump.

I am looking into ways of fixing it. Meanwhile, it should be pretty harmless with these changes.

**Pull request merged**
