### PR TITLE
Use operational master commit to fix build for ghc-9.0.1

### LINKED ISSUE #2016: CI for 9.0.1 is broken due to missing upstream commit
It appears CI for 9.0.1 is broken. At least four PRs currently in the queue are broken in 9.0.1 with the following error:

```
Cloning into '/home/runner/work/haskell-language-server/haskell-language-server/dist-newstyle/src/operation_-2cf41f8926150174'...
fatal: reference is not a tree: 0e062895678f49fd673ae493371262cfb8c5ab56
```

Digging in, that commit appears to be referenced here:

https://github.com/haskell/haskell-language-server/blob/a0f6f5fe9a610a11aeda9567873da5e970cf42b2/stack-9.0.1.yaml#L98-L100

and comes with a helpful PR reference:

https://github.com/HeinrichApfelmus/operational/pull/26

which is now merged. Looking at the commit in question:

https://github.com/berberman/operational/commit/0e062895678f49fd673ae493371262cfb8c5ab56

github responds with 

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

which sounds scary and I'd bet is why CI is failing.

@berberman your name is attached to the commit in question, mind investigating?

### PR DESCRIPTION
**Pull request by jneira**
* To fix ci for ghc-9.0.1
* Fixes #2016

### CODE REVIEW

**Review by isovector — APPROVED** [review]
thanks!

**Review by Ailrun — COMMENTED** [review]
Thank you. BTW, cabal-ghc901.project should also be fixed to make CI work.

**Comment by jneira** [comment]
> 
> 
> Thank you. BTW, cabal-ghc901.project should also be fixed to make CI work.

thanks! i was just about to commit the change

**Comment by isovector** [comment]
This fixes it, but CI is flaky af. I've restarted CI and maybe one day we'll be able to get code merged again :)

**Review by berberman — APPROVED** [review]
Many thanks, I also updated the nix config for ghc 9.0.1 here

**Comment by jneira** [comment]
> This fixes it, but CI is flaky af. I've restarted CI and maybe one day we'll be able to get code merged again :)

yeah, I am gonna disable tests for Windows and 9.0.1 😟

**Pull request merged**
