### PR TITLE
Create hls-plugin-api and move plugins to exe

### PR DESCRIPTION
**Pull request by jneira**
* This is a initial step to acomplish #164. There @alanz proposed:

> I propose the we split hls up
> * a slimmed-down core, that basically corresponds to the plugins built into ghcide.
> * an API package that can be used by plugin authors to write plugins for use in hls. The corresponds to the hie-plugin-api as originally envisaged.
> * a fat package that depends on the core, the api, and all known plugins at this time, and provides an exe depending on them.

The second one would be the hls-plugin-api and the second one the exe component in this pr.

Not sure about:
* the place of actual plugins: maybe the folder could be named `builtin` instead `default`?
* should ghcide be in the api or with the rest of plugins?

### CODE REVIEW

**Comment by pepeiborra** [comment]
Maybe add a `defaultMain` function to hls-plugin-api with the type below, and redefine `exe/Main.hs` with it?

```
defaultMain :: [PluginDescriptor] -> IO ()
```

**Review by pepeiborra — APPROVED** [review]
This is great! Definitely a step in the right direction. Eventually we can move the current plugins into separate packages too, as needed.

**Comment by jneira** [comment]
> 
> 
> Maybe add a `defaultMain` function to hls-plugin-api with the type below, and redefine `exe/Main.hs` with it?
> 
> ```
> defaultMain :: [PluginDescriptor] -> IO ()
> ```

Mmm i like to put the main logic in the library like f.e. [dhall](https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/src/Dhall/Main.hs), if it does not introduce extraneous dependencies. I'll give it a shot.

**Comment by jneira** [comment]
ci nix build failed with:
```
plugins/default/src/Ide/Plugin/Fourmolu.hs:75:11: error:
    Not in scope: `cfgPrinterOpts'
   |
75 |         , cfgPrinterOpts = printerOpts
   |           ^^^^^^^^^^^^^^
cabal: Failed to build exe:haskell-language-server from
haskell-language-server-0.4.0.0 (which is required by test:func-test from
haskell-language-server-0.4.0.0).
```
🤔

**Comment by pepeiborra** [comment]
> ci nix build failed with:
> 
> ```
> plugins/default/src/Ide/Plugin/Fourmolu.hs:75:11: error:
>     Not in scope: `cfgPrinterOpts'
>    |
> 75 |         , cfgPrinterOpts = printerOpts
>    |           ^^^^^^^^^^^^^^
> cabal: Failed to build exe:haskell-language-server from
> haskell-language-server-0.4.0.0 (which is required by test:func-test from
> haskell-language-server-0.4.0.0).
> ```
> 
> 🤔

Nix uses `cabal build`, so that error is probably incorrect version bounds for fourmulu. Not sure why it came up on this change, maybe it's broken in master too?

**Review by Ailrun — APPROVED** [review]
Great! I had planned to do this but couldn't find an enough time slot...
Thank you for extracting plugin API!

**Comment by jneira** [comment]
@alanz @pepeiborra i dont feel `hls-plugin-api` is the best place to put the `defaultMain`, what do you think in keep the package main lib and put it (with `Ide.Version` and `Arguments`) there? We have to maintain one more component (although already existing in master) but it would have a better separation of concerns.

**Comment by pepeiborra** [comment]
> @alanz @pepeiborra i dont feel `hls-plugin-api` is the best place to put the `defaultMain`, what do you think in keep the package main lib and put it (with `Ide.Version` and `Arguments`) there? We have to maintain one more component (although already existing in master) but it would have a better separation of concerns.

That sounds fine to me!

**Comment by alanz** [comment]
I agree. The `hls-plugin-api` should be the thing that tool writers use to create a plugin that is compatible with hls, and has nothing to do with running it.

So in future I would imagine a person writing say a formatter and including a plugin descriptor directly, and the formatter depends on `hls-plugin-api`.

**Comment by georgefst** [comment]
> Nix uses `cabal build`, so that error is probably incorrect version bounds for fourmulu. Not sure why it came up on this change, maybe it's broken in master too?

The log says it's building `fourmolu-0.0.6.0`. The `> 0.1` bound is in `haskell-language-server.cabal` for a reason, and this PR appears to have accidentally removed it. This looks to be the case for several other libs as well.

**Comment by jneira** [comment]
> The log says it's building `fourmolu-0.0.6.0`. The `^>= 0.1` bound is in `haskell-language-server.cabal` for a reason, and this PR appears to have accidentally removed it. This looks to be the case for several other libs as well.

Oops, i forgot to puth them when moving the deps around, thanks!

**Comment by jneira** [comment]
Ok, the executable modules are in the lib now and ci is happy (thanks again @georgefst)

**Comment by jneira** [comment]
Rebased, i hope this could be merged asap, cause it will likely be in conflict with any other commit, as it shuffles almost all modules in the project

**Review by alanz — APPROVED** [review]
LGTM

**Pull request merged**
