### PR TITLE
Prepare 0.8.0 release

### PR DESCRIPTION
**Pull request by jneira**
* I've changed the formatting, to fix markdownlint warnings

### CODE REVIEW

**Comment by pepeiborra** [comment]
Because of the ghcide merge, this release also includes a bunch of ghcide fixes and improvements. I think it's probably worth listing those too. The relevant part of the git log is: 

```
$ git log --pretty="* %s - (%an)" ghcide

* Fix extend imports regression (#769) - (Pepe Iborra)
* Perform memory measurement on SIGUSR1 (#761) - (Pepe Iborra)
* Tests for cradle retry - (Pepe Iborra)
* Make a test more reliable - (Pepe Iborra)
* On cradle failure, register the hie.yaml file as a dependency - (Pepe Iborra)
* Invert the dependency between hls-plugin-api and ghcide (#701) - (Pepe Iborra)
* Launch ghcide/HLS for tests with -j2 to limit amount of memory used - (Pepe Iborra)
* Move ghcide artifacts under /ghcide - (Pepe Iborra)
* Temporarily disable the upstream branch for benchmarks - (Pepe Iborra)
* Combine test and nix CI scripts - (Pepe Iborra)
* Add ghcide bench CI action - (Pepe Iborra)
* Delete redundant descriptors and scripts - (Pepe Iborra)
* Move under /ghcide folder - (Pepe Iborra)
* Prepare release 0.6.0.2 (haskell/ghcide#958) - (Pepe Iborra)
* Fix diagnostics update bug (haskell/ghcide#959) - (Pepe Iborra)
* Use qualified module name from diagnostics in suggestNewImport (haskell/ghcide#945) - (Potato Hatsue)
* Rescue stack windows build (haskell/ghcide#954) - (Pepe Iborra)
* Expose Documentation module (haskell/ghcide#956) - (Guru Devanla)
* Rename hie.yaml.* to hie-*.yaml (haskell/ghcide#953) - (Potato Hatsue)
* Deduplicate module not found diagnostics (haskell/ghcide#952) - (Pepe Iborra)
* Remove language extension completions. (haskell/ghcide#948) - (Guru Devanla)
```

**Review by pepeiborra — APPROVED** [review]

**Comment by jneira** [comment]
@pepeiborra hi, thanks for the suggestion. However, some of those pr's are already included in the ghcide [Changelog](https://github.com/haskell/haskell-language-server/blob/master/ghcide/CHANGELOG.md) or in the actual list of merged pr's. 
The unique i miss from both lists is `haskell/ghcide#952`, that was merged before ghcide-0.6.0.2 but no listed in the changelog for some reason. It seems its place would be the ghcide Changelog.

My idea was list all pr's without mention the subpackage (ghcide, hls-plugin-api, plugins), cause it would make generate the Changelog a little bit more laborious. Now it is simply matter of run `cabal run GenChangeLog.hs` and paste the output in `ChangeLog.md`

**Comment by jneira** [comment]
btw, we should replace the links to pr's in the ghcide changelog using `#` shorthand with full links to the ghcide repo (in another pr if you dont mind)

**Comment by jneira** [comment]
A release of hls-plugin-api is needed, will do asap

**Comment by pepeiborra** [comment]
> @pepeiborra hi, thanks for the suggestion. However, some of those pr's are already included in the ghcide [Changelog](https://github.com/haskell/haskell-language-server/blob/master/ghcide/CHANGELOG.md) or in the actual list of merged pr's. 
> 
> The unique i miss from both lists is `haskell/ghcide#952`, that was merged before ghcide-0.6.0.2 but no listed in the changelog for some reason. It seems its place would be the ghcide Changelog.
> 
> 
> 
> My idea was list all pr's without mention the subpackage (ghcide, hls-plugin-api, plugins), cause it would make generate the Changelog a little bit more laborious. Now it is simply matter of run `cabal run GenChangeLog.hs` and paste the output in `ChangeLog.md`

What is missing is the usual "upgrading to ghcide vX.X.X" referencing a ghcide change log

**Comment by jneira** [comment]
In fact all version bumps are missing, i'll do a new pr with that change

**Comment by pepeiborra** [comment]
But there is no corresponding ghcide version that you can reference? You will need to do a ghcide release too

**Comment by jneira** [comment]
@pepeiborra yeah, thanks for remind me it, there are breaking changes after 0.6.0.2
so i will bump ghcide version in that pr to 0.7.0, could you make the hackage release (afaik i have not hackage perm to do it)

**Comment by pepeiborra** [comment]
You do now: http://hackage.haskell.org/package/ghcide/maintainers/

**Pull request merged**
