### PR TITLE
bump ghcide submodule

### PR DESCRIPTION
**Pull request by wz1000**
For https://github.com/haskell/ghcide/pull/784

### CODE REVIEW

**Comment by alanz** [comment]
What about #395?  I presume these two should be combined?

**Comment by wz1000** [comment]
Yes, this supersedes that.

**Comment by Ailrun** [comment]
It looks like there are few codes that should be updated alongside this bump.

**Comment by pepeiborra** [comment]
https://github.com/haskell/ghcide/pull/791 should hopefully fix the test errors here

**Pull request merged**
