### PR TITLE
Fix references to old names

### PR DESCRIPTION
**Pull request by fendor**
See https://github.com/haskell/haskell-language-server/blob/master/haskell-language-server.cabal#L1821

### CODE REVIEW

**Comment by fendor** [comment]
Genuine bugs uncovered :)

**Comment by michaelpj** [comment]
How did this not just break before??

**Comment by michaelpj** [comment]
The horror :scream:

**Comment by fendor** [comment]
A lot of our tests are running (or not running) but failing or not failing for the wrong reasons, also see #4130 and #4036.

**Pull request closed without merging**
