### PR TITLE
Add ghc 9.2.1 to gitlab ci

### PR DESCRIPTION
**Pull request by jneira**
* removing the integer-simple workaround, as alpine based ghcs installed by ghcup uses integer-gmp
* removing the nix config as afaics it is not used anymore
* triggered a build in the gilab repo: https://gitlab.haskell.org/haskell/haskell-language-server/-/pipelines/46447

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2636"></a>

### CODE REVIEW

**Review by hasufell — APPROVED** [review]

**Comment by jneira** [comment]
windows build is failing with:

```
Packages (1) zip-3.0-3
Total Installed Size:  0.45 MiB
Net Upgrade Size:      0.00 MiB
:: Proceed with installation? [Y/n] 
checking keyring...
downloading required keys...
:: Import PGP key 5F92EFC1A47D45A1, "Alexey Pavlov <alexpux@gmail.com>"? [Y/n] error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
```

**Comment by jneira** [comment]
@hasufell the last ci pipeline (https://gitlab.haskell.org/haskell/haskell-language-server/-/pipelines/46449) did not build the matrix for ghc-9.2.1. do you know what is missing to make it honour the changes in https://github.com/haskell/haskell-language-server/pull/2636/files#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7R21?

**Comment by jneira** [comment]
Also freebsd builds are failing with:

```
Starting     retrie-1.1.0.0 (lib)
Building     retrie-1.1.0.0 (lib)
/usr/home/vagrant/builds/0/haskell-haskell-language-server/o7rN9PEs/0/haskell/haskell-language-server/.gitlab/common.sh: line 46:  2772 Killed                  "$@"
+ error 'cabal v2-build -O2 -w ghc-8.10.7 --project-file cabal.project --disable-profiling --disable-tests --enable-executable-stripping --enable-split-sections exe:hls exe:hls-wrapper failed'
+ echo_color '0;31' 'cabal v2-build -O2 -w ghc-8.10.7 --project-file cabal.project --disable-profiling --disable-tests --enable-executable-stripping --enable-split-sections exe:hls exe:hls-wrapper failed'
+ local 'color=0;31'
+ local 'msg=cabal v2-build -O2 -w ghc-8.10.7 --project-file cabal.project --disable-profiling --disable-tests --enable-executable-stripping --enable-split-sections exe:hls exe:hls-wrapper failed'
+ echo -e '\033[0;31mcabal v2-build -O2 -w ghc-8.10.7 --project-file cabal.project --disable-profiling --disable-tests --enable-executable-stripping --enable-split-sections exe:hls exe:hls-wrapper failed\033[0m'
cabal v2-build -O2 -w ghc-8.10.7 --project-file cabal.project --disable-profiling --disable-tests --enable-executable-stripping --enable-split-sections exe:hls exe:hls-wrapper failed
```

it seems cabal is failing building retrie but i dont see the cabal error

**Comment by hasufell** [comment]
> Also freebsd builds are failing with:
> 
> ```
> Starting     retrie-1.1.0.0 (lib)
> Building     retrie-1.1.0.0 (lib)
> /usr/home/vagrant/builds/0/haskell-haskell-language-server/o7rN9PEs/0/haskell/haskell-language-server/.gitlab/common.sh: line 46:  2772 Killed                  "$@"
> + error 'cabal v2-build -O2 -w ghc-8.10.7 --project-file cabal.project --disable-profiling --disable-tests --enable-executable-stripping --enable-split-sections exe:hls exe:hls-wrapper failed'
> + echo_color '0;31' 'cabal v2-build -O2 -w ghc-8.10.7 --project-file cabal.project --disable-profiling --disable-tests --enable-executable-stripping --enable-split-sections exe:hls exe:hls-wrapper failed'
> + local 'color=0;31'
> + local 'msg=cabal v2-build -O2 -w ghc-8.10.7 --project-file cabal.project --disable-profiling --disable-tests --enable-executable-stripping --enable-split-sections exe:hls exe:hls-wrapper failed'
> + echo -e '\033[0;31mcabal v2-build -O2 -w ghc-8.10.7 --project-file cabal.project --disable-profiling --disable-tests --enable-executable-stripping --enable-split-sections exe:hls exe:hls-wrapper failed\033[0m'
> cabal v2-build -O2 -w ghc-8.10.7 --project-file cabal.project --disable-profiling --disable-tests --enable-executable-stripping --enable-split-sections exe:hls exe:hls-wrapper failed
> ```
> 
> it seems cabal is failing building retrie but i dont see the cabal error

```
cabal: Failed to build aeson-1.5.6.0 (which is required by exe:hls from
hls-1.5.1.0 and exe:hls-wrapper from hls-1.5.1.0). The build process was
killed (i.e. SIGKILL). The typical reason for this is that there is not enough
memory available (e.g. the OS killed a process using lots of memory).
Failed to build ghc-lib-parser-8.10.7.20210828 (which is required by exe:hls
from hls-1.5.1.0). The build process was killed (i.e. SIGKILL). The typical
reason for this is that there is not enough memory available (e.g. the OS
killed a process using lots of memory).
```

the machine ran out of memory.

**Comment by hasufell** [comment]
> @hasufell the last ci pipeline (https://gitlab.haskell.org/haskell/haskell-language-server/-/pipelines/46449) did not build the matrix for ghc-9.2.1. do you know what is missing to make it honour the changes in https://github.com/haskell/haskell-language-server/pull/2636/files#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7R21?

The pipeline you linked doesn't include the commit that adds 9.2.1 to gitlab. So you seem to have mixed something up.

**Comment by jneira** [comment]
ugh :facepalm:  you are right, wrong branch

**Comment by jneira** [comment]
> the machine ran out of memory.
> 
> Maybe `-O1` and `--jobs=1` will help.

thanks will try for bsd-12, however the log i attached in for bsd-13 and there is no mention to oom there. Will try -j1 anyways

**Comment by jneira** [comment]
New pipelines:
* https://gitlab.haskell.org/haskell/haskell-language-server/-/pipelines/46479 : with 9.2.1, without -j1 for freebsd
* https://gitlab.haskell.org/haskell/haskell-language-server/-/pipelines/46480: with 9.2.1 and -j1 for freebsd

**Comment by jneira** [comment]
The windows issue is related with msys gpg keys, similar to https://github.com/msys2/MSYS2-packages/issues/2397 but with another signer

**Comment by jneira** [comment]
* https://gitlab.haskell.org/haskell/haskell-language-server/-/pipelines/46483: with the windows fix

**Comment by jneira** [comment]
The las pipeline was almost succesfull but freebsd12 and 13 for ghc-9.2.1, the error in both cases is

```
  Please ensure the following distro packages are installed before continuing (you can exit ghcup and return at any time): curl gcc gmp gmake ncurses perl5 libffi libiconv
[ Debug ] Identified Platform as: FreeBSD, 12.2-RELEASE
[ Debug ] last access was 0.005622088s ago, cache interval is 300s
[ Debug ] Decoding yaml at: /usr/home/vagrant/builds/0/haskell-haskell-language-server/1B9-s-2K/0/haskell/haskell-language-server/toolchain/.ghcup/cache/ghcup-0.0.6.yaml
[ Error ] Unable to find a download for the requested version/distro.
"_eghcup --cache install ghc 9.2.1" failed!
```

It seems a thing we have to fix in ghcup itself so i am gonna merge this. If we need more changes for freebsd we could do a new one

**Comment by hasufell** [comment]
There are no freebsd bindists: https://downloads.haskell.org/~ghc/9.2.1/

**Comment by jneira** [comment]
ok will remove 9.2.1 for freebsd then (or are you planning to publish unofficial bindists for?)

**Comment by hasufell** [comment]
> or are you planning to publish unofficial bindists for?

no, afair FreeBSD is broken on 9.2.1 or so

**Pull request merged**
