### PR TITLE
Update implicit-hie & ghcide

### PR DESCRIPTION
**Pull request by Avi-D-coder**
> # Changelog for implicit-hie-cradle
> 
> ## 0.3.0.0
> Match `implicit-hie`'s cradle type ordering.
> This is technically a breaking change.

### CODE REVIEW

**Comment by Avi-D-coder** [comment]
`allow-newer` is needed until https://github.com/haskell/ghcide/pull/905 lands.
Should we just wait and upgrade ghcide then?

**Comment by jneira** [comment]
> Should we just wait and upgrade ghcide then?
As it does not fix an ugly bug i would wait to ghcide, yeah.

**Comment by Avi-D-coder** [comment]
It fixes https://github.com/Avi-D-coder/implicit-hie/issues/24, but I agree it should wait.

**Comment by jneira** [comment]
oh yeah, i've just read your comment in the relevant issue.

**Review by jneira — APPROVED** [review]
LGTM, will merge when ci is green

**Pull request merged**
