### PR TITLE
Hlint more partial functions, and Debug.Trace

### PR DESCRIPTION
**Pull request by michaelpj**
Turns out that for functions which are typically imported in multiple ways, you need to list both explicitly, and you can't combine them (see the linked HLint issue). So I did that and added some more exceptions.

I also banned `Debug.Trace`, removing a couple of dead usages and adding exceptions for the existing (!) usages.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3000"></a>

### CODE REVIEW

**Comment by wz1000** [comment]
Can we have global exceptions for `traceEvent`, `traceEventIO`, `traceMarker` and `traceMarkerIO`? These should cover some of the existing module exceptions.

**Comment by michaelpj** [comment]
I'm not sure if I can do that easily, I might have to switch to explicitly listing the banned functions from `Debug.Trace`.

**Comment by michaelpj** [comment]
I'm doing that, but in fact it doesn't let us get rid of any exceptions, since all of those modules also use non-eventlog tracing functions :shrug:

**Comment by wz1000** [comment]
Maybe change those instances to use the existing log mechanism where it is easy? Perhaps a job for another time.

**Comment by drsooch** [comment]
Is there no way to ignore whole directories? For example the test suites seem like it would be ok to allow certain partial functions

**Comment by michaelpj** [comment]
Not sure, I think it works off them module name anyway. I'm also not too bothered by it - the explicit list is not actually that long!

**Comment by drsooch** [comment]
Fair enough. Just looks tedious 😂

**Review by drsooch — APPROVED** [review]

**Pull request merged**
