### PR TITLE
Disable auto extend import lists in completions

### PR DESCRIPTION
**Pull request by pepeiborra**
It seems that this feature needs a bit more work, as reported in #679

I am disabling it locally in HLS rather than in ghcide

### CODE REVIEW

**Comment by expipiplus1** [comment]
Does this fix: https://github.com/haskell/haskell-language-server/issues/682 I wonder

**Review by jneira — APPROVED** [review]
LGTM, but we have to remember that building hls using ghcide hackage release would enable it

**Comment by pepeiborra** [comment]
> LGTM, but we have to remember that building hls using ghcide hackage release would enable it

To build hls using ghcide hackage you would have to edit the `cabal.project` file. If someone does that, then they probably know what they are doing.

**Comment by jneira** [comment]
@pepeiborra definitely is not the regular way to install it but see #484 for example

**Pull request merged**
