### PR TITLE
Eval plugin for GHC 9.4

### PR DESCRIPTION
**Pull request by wz1000**
Supersedes #3249 and depends on #3390

### CODE REVIEW

**Comment by michaelpj** [comment]
Looks like Pepe's question never got answered (https://github.com/haskell/haskell-language-server/pull/3249#discussion_r990634700), but I'm okay with this anyway. Has conflicts now.

**Comment by michaelpj** [comment]
What's the status of this?

**Comment by wz1000** [comment]
This is ready for review

@pepeiborra `setupDynFlagsForGHCiLike` doesn't do much as setting the optimisation level to 0 sets the same set of flags.

**Comment by pepeiborra** [comment]
> The plugin was implemented by calling "load" which circumvents all of HLSs caching mechanisms for interface files and linkables. Instead we should work like the other typechecking functions which get all the stuff we need using HLS rules and setup the HscEnv with all the state in the right places.

Is there any way to check this in a test? Or a benchmark? Seems like an important property.

**Review by pepeiborra — APPROVED** [review]

**Comment by wz1000** [comment]
> > The plugin was implemented by calling "load" which circumvents all of HLSs caching mechanisms for interface files and linkables. Instead we should work like the other typechecking functions which get all the stuff we need using HLS rules and setup the HscEnv with all the state in the right places.
> 
> Is there any way to check this in a test? Or a benchmark? Seems like an important property.

I don't thin there is an easy way to do this. We can blacklist the `load` family of functions using hlint.

**Comment by michaelpj** [comment]
Blacklisting the functions sounds good!

**Comment by wz1000** [comment]
I have added an hlint rule and also fixed a regression that caused the eval plugin not to work due to https://github.com/haskell/haskell-language-server/pull/3414 landing. See the comment in the last commit for details.

**Pull request merged**
