### PR TITLE
Update formatting hooks to not include Wingman

### PR DESCRIPTION
**Pull request by Ailrun**

### CODE REVIEW

**Review by isovector — APPROVED** [review]
<3 thanks so much! I really appreciate it!

**Comment by Ailrun** [comment]
@jneira How did you merge a PR like this, which does not invoke every check?

**Comment by jneira** [comment]
@Ailrun allowing administrators to merge prs not fullfilling the branch protection rueles in setting, merging and enable full protection thereafter
I am gonna prepare a pr to unblock those prs asap

**Comment by Ailrun** [comment]
Thanks, it works.

**Pull request merged**
