### PR TITLE
use versioned hackage libraries

### PR DESCRIPTION
**Pull request by smunix**
`ormolu_0_5_3_3` has been removed from nixpkgs. To prevent future breaks, let's pull specific versions from hackage when they are available.

### CODE REVIEW

**Review by fendor — APPROVED** [review]
LGTM!

**Comment by fendor** [comment]
Are the changes supposed to fix nix CI?

**Comment by smunix** [comment]
> Are the changes supposed to fix nix CI?

No, they just prevent breaks on our next update to nixpkgs. Ormolu version has been upgraded on Nix

**Comment by cydparser** [comment]
There is a [comment in flake.nix](https://github.com/haskell/haskell-language-server/blob/c501f386b55be0f3ad0a8238dd9d135b7b26fe45/flake.nix#L141) stating not to use `callHackage`. @berberman, is that comment still relevant?

**Comment by cydparser** [comment]
@smunix, I've fixed CI in https://github.com/haskell/haskell-language-server/pull/3724.

**Comment by berberman** [comment]
> There is a [comment in flake.nix](https://github.com/haskell/haskell-language-server/blob/c501f386b55be0f3ad0a8238dd9d135b7b26fe45/flake.nix#L141) stating not to use `callHackage`. @berberman, is that comment still relevant?

`callHackage` works only if the corresponding version is in https://github.com/commercialhaskell/all-cabal-hashes, so previously we used `callCabal2nix` with `fetchurl` for very new packages. Given that now we have those package sources in flake inputs, I think we can delete this comment now.

For this PR, it should be fine to use `callHackage`.

**Comment by smunix** [comment]
`haskell-language-server-96` requires `ormolu 0.7`, and `nix` can't build that version off of hackage. I'm closing this PR for now

**Pull request closed without merging**
