### PR TITLE
Upgrade to latest lsp / lsp-types / lsp-test

### PR DESCRIPTION
**Pull request by jhrcek**
~New version of lsp* has not been released yet, but I upgraded hls codebase to master version to be able to test https://github.com/haskell/lsp/pull/566~

UPDATE: we're not going to merge the "disable progress messages" PR in lsp repo,
but this PR can still be used because it contains all the fixes to breaking changes in lsp repo.

### CODE REVIEW

**Comment by soulomoon** [comment]
Is the new lsp released yet, can't wait to use it since 
https://github.com/haskell/haskell-language-server/issues/4194 is causing a lot of 3 second wait 0 0

**Comment by jhrcek** [comment]
It's not released yet. I just rebased this PR on master + switched to latest master commit of lsp repo.
It compiles, but there are bunch of test failures. I'll look at those over next week.

**Comment by jhrcek** [comment]
@soulomoon @michaelpj updated to lsp master, this is basically ready.
I'd suggest we release the latest changes in lsp repo to master and then switch this PR to use hackage releases of those packages and merge.

**Comment by michaelpj** [comment]
Yep, I'll do a release.

**Comment by soulomoon** [comment]
Great

**Comment by michaelpj** [comment]
Haha, I had just done that locally. You are very on it ;)

**Comment by jhrcek** [comment]
That's what it's like having github notifications enabled and few minutes to spare between meetings :smile:

**Review by michaelpj — APPROVED** [review]
Thanks so much for dealing with all this, much appreciated.

**Review by fendor — APPROVED** [review]

**Review by soulomoon — APPROVED** [review]
LGTM!

**Pull request merged**
