### PR TITLE
Add code actions for disabling a warning in the current file

### PR DESCRIPTION
**Pull request by georgefst**
Previously known as haskell/ghcide#897.

Progress towards #705.

### CODE REVIEW

**Comment by georgefst** [comment]
Fairly confident tests should pass now.

Are we squash-merging these days? Commit history here is a bit noisy due to some carelessness on my part...

**Comment by Ailrun** [comment]
@georgefst Mostly yes, though some manual merge is done as a normal merge, automated ones with "merge me" label is done as a squash merge.

**Comment by georgefst** [comment]
... and we're done. Closes #571.

There are a lot of tests which rely on the exact position in which a particular action happens to appear in the list returned by `getCodeActions`. This is pretty brittle. I've rewritten the ones that were broken by this change, but we might want to take a look at improving the others.

**Review by jneira — APPROVED** [review]
Looks great, this is a nice feature and includes a solid test suite, thanks!

**Pull request merged**
