### PR TITLE
Reenable HLS example benchmark

### PR DESCRIPTION
**Pull request by pepeiborra**
The example was commented out in #1388

### CODE REVIEW

**Comment by wz1000** [comment]
hie-bios has been updated. Should we check if it fixes the timeouts?

**Comment by pepeiborra** [comment]
Oh, that's a good point, let me repurpose the PR

**Comment by wz1000** [comment]
Benchmarks didn't time out but all of them failed :(

I've also noticed that all the "code actions" benchmarks have been failing for lsp-test since at least the hie-bios update.

**Review by Ailrun — APPROVED** [review]
Awesome, now it works! Thank you

**Pull request merged**
