### PR TITLE
update LTS for GHC 8.10.6

### PR DESCRIPTION
**Pull request by peterbecich**
https://www.stackage.org/lts-18.7

### CODE REVIEW

**Comment by jneira** [comment]
thanks for the update, have you revised if any of the extra-deps could be removed?

**Comment by peterbecich** [comment]
Good idea, I've updated `extra-deps`.

I believe these are all the diffs between `nightly-2021-06-14` and the new LTS, including the updated/removed `extra-deps`:
```

-Cabal 3.0.2.0
+Cabal 3.2.1.0

-bytestring-encoding 0.1.0.0
+bytestring-encoding 0.1.1.0

-clock 0.7.2
+clock 0.8.2

-ghc-api-compat 8.6.1
+ghc-api-compat 8.10.6

-ghc-check 0.5.0.4
+ghc-check 0.5.0.5

-heapsize 0.3.0
+heapsize 0.3.0.1

-monad-dijkstra 0.1.1.2
+monad-dijkstra 0.1.1.3

-semigroups 0.18.5
+semigroups 0.19.1

-some 1.0.1
+some 1.0.2

-temporary 1.2.1.1
+temporary 1.3
```

**Comment by peterbecich** [comment]
Shoul I make `stack-8.10.6.yaml` the default `stack.yaml`?

**Comment by jneira** [comment]
> 
> 
> Should I make `stack-8.10.6.yaml` the default `stack.yaml`?

i think we could use directly 8.10.7, once we are sure it is stable

**Comment by jneira** [comment]
many thanks for revising the extra deps, it looks nice, do you think it is ready to merge (so it can be unmarked as draft?

**Comment by peterbecich** [comment]
Sure thing, I believe it is ready to merge. Thx

**Comment by jneira** [comment]
nice, could you cherry-pick or apply manually https://github.com/haskell/haskell-language-server/commit/67b786c1c471d248e9930036aec2197f4f83e025 to unblock CI?

**Review by jneira — APPROVED** [review]
many thanks, happy to see contributions which take care of build config files :slightly_smiling_face:

**Comment by jneira** [comment]
circle ci status checks are stale, lets see if the next merge with mater fix them

**Pull request merged**
