### PR TITLE
Don't insert parentheses for top-level tactics holes

### PR DESCRIPTION
**Pull request by isovector**
We don't need to always insert parentheses! It's a good idea when grafting in general, but in the tactics plugin we know the context we're working in. This PR is a quick patch to not call the parenthesizing routines if we're already in a top-level hole.

### CODE REVIEW

**Review by konn — APPROVED** [review]
LGTM 👍

**Review by jneira — APPROVED** [review]
lgtm too

**Comment by Ailrun** [comment]
It looks like automatic merge breaks a golden file.

**Comment by isovector** [comment]
Test is fixed!

**Pull request merged**
