### PR TITLE
Update Fourmolu to 0.2

### PR DESCRIPTION
**Pull request by georgefst**
This brings a lot of new options including leading commas and better import/export lists.

Apologies for the large diff - I took the opportunity to format and tidy things up a bit. Nothing interesting has actually changed other than adapting to a slightly different API for loading config files. We also now use indentation from the editor's settings, if it is not otherwise set.

### CODE REVIEW

**Comment by georgefst** [comment]
Replaces #445.

**Comment by georgefst** [comment]
That last change has nothing to do with Fourmolu... But bumping `index-state` brings in an incompatible version of `refinery`.

**Comment by georgefst** [comment]
It looks like #431 adapts to the updated refinery.

**Review by bubba — APPROVED** [review]
LGTM, I think we can get this into the 0.5 release

**Comment by georgefst** [comment]
> LGTM, I think we can get this into the 0.5 release

Thanks, that's what I was hoping to hear!

**Pull request merged**
