### PR TITLE
hls-hlint-plugin work with GHC 9.6

### PR DESCRIPTION
**Pull request by wavewave**
so enable the flags and lift up buildable: False.

### CODE REVIEW

**Comment by michaelpj** [comment]
This is still marked as draft, anything more needed here?

**Comment by wavewave** [comment]
Oh. nothing more to work. sorry. It was a draft since it was on top of the other wip branch and I didn't realize it was merged.

**Comment by georgefst** [comment]
I've just seen this, after opening https://github.com/haskell/haskell-language-server/pull/3565 which heavily overlaps. Could we make this PR for HLint only? Since the other one is further along for Fourmolu, and in particular, I'm fairly sure is going to pass CI this time round.

**Comment by wavewave** [comment]
yeah. no problems. let's first merge that #3565 first. Thanks! :-)

**Comment by joyfulmantis** [comment]
Obsolete as of https://github.com/haskell/haskell-language-server/pull/3677

**Pull request closed without merging**
