### PR TITLE
Refactor collectLiterals in AlternateNumberFormat.

### LINKED ISSUE #2490: 100% CPU usage with AlternateNumberFormat plugin
After upgrading haskell-language-server to b7949aa5c54d8319029cc2bfba164ce5f6eab924 I noticed that it used 100% CPU while staying otherwise responsive. I found this in the logs

```
2021-12-14 13:33:11.542240523 [ThreadId 8807] INFO hls:	finish: AlternateNumberFormat.CollectLiterals (took 1m32s)
2021-12-14 13:33:11.542255151 [ThreadId 975] DEBUG hls:	"Literals: [IntLiteral SrcSpanOneLine \"/home/phil/projects/nejla/app/backend/src/Handlers/Job.hs\" 173 27 34 \"1000000\" 1000000,IntLiteral SrcSpanOneLine \"/home/phil/projects/nejla/app/backend/src/Handlers/Job.hs\" 259 13 14 \"0\" 0,IntLiteral SrcSpanOneLine \"/home/phil/projects/nejla/app/backend/src/Handlers/Job.hs\" 260 55 56 \"1\" 1]"
```

* The mentioned line is just a `threadDelay 1000000` and haskell-language-server seems to produce one of these log lines every few minutes for a different literal in my code base.
* It's a 350 line module in a medium-sized project (14kloc) 
* Light use of Template Haskell and QuasiQuotes (some `$logDebug`s and quotes for string interpolation)
* No NumericalUnderscores

Unfortunately I can't link the code since it's proprietary.

### Your environment

Which OS do you use:
NixOS

Which lsp-client do you use:
emacs with lsp-mode
Describe your project (alternative: link to the project):
stack.yaml

### Steps to reproduce
Run haskell-language-server on my project as normal

### Expected behaviour
0% CPU usage after initial setup

### Actual behaviour
100% CPU usage permanently (or at least multiple hours)

### Include debug information

I don't have access to the machine right now but I'll reproduce them if required.

Execute in the root of your project the command `haskell-language-server-wrapper --debug .` and paste the logs here:
(if you are using the vscode extension check the executable location [here](https://github.com/haskell/vscode-haskell#downloaded-binaries))
<details>
<summary>
Debug output:
</summary>

```
<paste your logs here>
```
</details>

Paste the logs from the lsp-client, you can check instructions about for VS Code [here](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
<paste your logs here>
```
</details>

### PR DESCRIPTION
**Pull request by drsooch**
This is not the final iteration I'm just looking for some quick feedback and suggestions:

This commit resolves #2490, but exposes other issues.

- Re-enable the alternateNumberFormat plugin

- Refactor collectLiterals to look for HsLit and HsOverLit directly
  rather than HsExpr.

- This new change removes the issue of finding duplicate Literal
  entries, as well as drastically reducing the time to parse

ISSUE:

- Currently the parsing only captures literals on the RHS of the
  function declaration. Patterns are not being matched properly. This
  was found in the prior iteration, but was remediated (at the cost of
  performance). As a result, some tests will fail.

NOTES:

- There are two implementations of `collectLiterals` one is `collectLiterals` and the other is `collectLiterals'` both function the same and are "equally" performant. However both suffer from the issue mentioned above where patterns are not captured...

If anyone has some advice/help (especially regarding the missing LHS literals) that would be great.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2516"></a>

### CODE REVIEW

**Comment by jneira** [comment]
Hi, thanks for working in the fix, maybe the best way to reenable the plugin could be start the pr with a revert of the commit disabling it (to restore docs and other changes)

**Comment by pepeiborra** [comment]
> If anyone has some advice/help (especially regarding the missing LHS literals) that would be great.

Have you read the original SYB [paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2003/01/hmap.pdf)? I read it a long time ago and don't remember the details, but I suspect that a simple traversal cannot collect literals inside expressions inside patterns inside expressions. 

So I think your `mkQ2` traversal was a step in the right direction to handle both `HsExpr` and `HsPat`. Did you investigate using `extQ` instead of rolling your own thing?

**Comment by drsooch** [comment]
> Hi, thanks for working in the fix, maybe the best way to reenable the plugin could be start the pr with a revert of the commit disabling it (to restore docs and other changes)

I'm going to close this once I have a fix. Then I'll reopen a PR with a clean history.

**Comment by drsooch** [comment]
> > If anyone has some advice/help (especially regarding the missing LHS literals) that would be great.
> 
> Have you read the original SYB [paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2003/01/hmap.pdf)? I read it a long time ago and don't remember the details, but I suspect that a simple traversal cannot collect literals inside expressions inside patterns inside expressions.
> 
> So I think your `mkQ2` traversal was a step in the right direction to handle both `HsExpr` and `HsPat`. Did you investigate using `extQ` instead of rolling your own thing?

I'm ashamed... I didn't understand what you meant when you were comparing `HsPat` and `HsExpr` and then I realized the extraction function (`getLiteral`)  is expecting an `HsExpr` and would never traverse a Pattern in the first place...

Now I realize my original error. I've made a new change to include `Pat` as a possible choice to extract from. 

I chose to refrain from applying `everything (<>) (mkQ [] getLiteral)` inside of `getPattern` as I wanted to keep the types clean (refrain from making everything a list). 

This seems to capture most literals. I can imagine a pattern has been missed but I haven't exhaustively searched.

**Comment by pepeiborra** [comment]
Sorry, I probably meant `Pat` where I said `HsPat`, I'm not overly familiar with the ghc api naming scheme. 

How is the performance now?

**Comment by drsooch** [comment]
Performance looks good. It's back in line with other plugins. I don't have a heavy enough Haskell workload to do exhaustive testing. I went through large files in HLS to make sure there were no issues.

**Comment by drsooch** [comment]
Nevermind, I cleaned up the history on this branch. This is ready for PR.

**Review by Ailrun — APPROVED** [review]
Looks good to me. You checked the performance on HLS repo itself, right? I think then it's good to go.

**Review by jneira — APPROVED** [review]
looks great, many thanks for take care, I am sure people doing numeric stuff are gonna love this plugin

**Pull request merged**
