### PR TITLE
Revert "Send unhandled exceptions to the user (#2484)"

### PR DESCRIPTION
**Pull request by jneira**
* This reverts commit 0211f75c96402dda53be69473714134244763d95.
* That commit causes ghcide tests in windows hangs for all ghcs
* The test suite was marked incorrectly as ok due a bug in the workflows (fixed with #2493)
* See #2484 for more details

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2497"></a>

### CODE REVIEW

**Review by pepeiborra — APPROVED** [review]
Can you reproduce the problem locally? I don't have a Windows machine.


Can you share a link to a CI job showing the problem? I looked at the original PR and I don't see any hanging.

Approving based on trust.

**Comment by jneira** [comment]
> Can you reproduce the problem locally? I don't have a Windows machine.
> 

I did not try yet, will do

> Can you share a link to a CI job showing the problem? I looked at the original PR and I don't see any hanging.
> 

Collecting here the links:
* Run exhibiting the issue in the haskell repo: https://github.com/haskell/haskell-language-server/runs/4557599786?check_suite_focus=true (from pr https://github.com/haskell/haskell-language-server/pull/2493)
* Run in my fork exhibiting the issue in my repo: https://github.com/jneira/haskell-language-server/runs/4558206432?check_suite_focus=true (with pr https://github.com/jneira/haskell-language-server/pull/55)
* Run in my work with a succesful run after reverting: https://github.com/jneira/haskell-language-server/runs/4559275575?check_suite_focus=true (with pr https://github.com/jneira/haskell-language-server/pull/56)

> Approving based on trust.

thanks!

**Comment by pepeiborra** [comment]
I have looked at the 3 linked failures and I don't see any hanging. The jobs seem to be taking a very long time to build ghcide and then the ghcide test suite, which suggests a problem with CI caching?
I am out of touch with the CI setup after the recent changes, but I don't think we should be reverting this PR without more evidence.

**Review by pepeiborra — CHANGES_REQUESTED** [review]
Withholding approval until we have more evidence that this PR caused hangs

**Comment by jneira** [comment]
I've added a fourth link to the original pr last failing run before the merge in master.

Not sure what additional evidence can I include:
* the original pr failing run the ghcide test suite: cancelled after 4h 25 min in the middle of `initialize response capabilities` test group
* a posterior build with the pr included cancelled after 2h 9m hanged in the same test group
* one build in my fork with the commit included, cancelled after 4h 39m hanged in the same test group. To demonstrate my fork with a separate cache also reproduced the problem
* the successful run in my fork reversing the pr
* the successful run of this pr reverting the pr

**Comment by jneira** [comment]
to check if the cache is related (don't see how the cache can make hang a test at runtime but still) i am gonna open another pr invalidating it

**Comment by pepeiborra** [comment]
Is it the "text doc sync" test that is handling? Please try a local repro and share the log of messages

**Comment by jneira** [comment]
all runs, the failing and successful ones are using the same cache so...

**Comment by michaelpj** [comment]
Hmm, maybe this is actually a caching issue? It does seem like there's more recompilation going on that I would expect if the caching was working.

**Comment by jneira** [comment]
> Is it the "text doc sync" test that is handling? Please try a local repro and share the log of messages

I am not at home right now but I ve opened a pr in my repo with LSP msgs enabled in the first call to tests

https://github.com/jneira/haskell-language-server/pull/57

**Comment by jneira** [comment]
The run https://github.com/haskell/haskell-language-server/runs/4561717143?check_suite_focus=true
from the pr https://github.com/jneira/haskell-language-server/pull/57 with a fresh cache has failed with the same hang so i think it is clear the cache is not related with the bug

**Comment by jneira** [comment]
I think is is clear this revert unblocks the ciandthere are several prs in the queue to be merged. 
We could continue working in the diagnose and the fix afterwards.

The pr with lsp messages enabled has ended, the full log can be downloaded here: https://github.com/jneira/haskell-language-server/suites/4693272570/logs?attempt=1

**Review by pepeiborra — APPROVED** [review]

**Comment by soulomoon** [comment]
This is still ghosting us sometimes, see https://github.com/haskell/haskell-language-server/actions/runs/8924119343/job/24509825742?pr=4202

**Pull request merged**
