### PR TITLE
Add support for `.env` shells to `flake.nix`

### PR DESCRIPTION
**Pull request by Gabriella439**
The main motivation for this change is to enable development of HLS plugins by generating a `.env` shell for every package in this repository.

Example usage:

```ShellSession
$ nix develop .#haskell-language-server-dev-env.hls-fourmolu-plugin
```

This is a plain shell, though, without any tooling installed, identical to the one that Nixpkgs provides by default.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3322"></a>

### CODE REVIEW

**Review by guibou — APPROVED** [review]
Thank you.

**Comment by guibou** [comment]
@Gabriella439 Thank you for this contribution.

Is it possible to add a bit of documentation (In the different Readme or directly in the flake file) so users will easily understand the difference between the different shells?

This being said, I approved, so just add documentation if you have time and feel it, that's not a requirement.

**Comment by michaelpj** [comment]
@Gabriella439 are you interested in helping to maintain the nix setup in this repo? You would be welcome to :) If so you could add yourself to CODEOWNERS.

**Comment by Gabriella439** [comment]
Yes, I am interested in helping maintain the Nix setup!  I'll add myself as a CODEOWNER in a separate PR, though

**Pull request merged**
