### PR TITLE
Add windows to ghcup artifacts and generate sha256 sums

### PR DESCRIPTION
**Pull request by jneira**
* So the next release will generate it as well

### CODE REVIEW

**Review by Ailrun — APPROVED** [review]
Sorry for the delay from my side; I'm quite busy because of POPL...
Anyway, thank you very much for fixing this!

**Comment by jneira** [comment]
* I've added a build job step to generate sha256 sums, to make progress on #1438 
* I've test the build here: https://github.com/jneira/haskell-language-server/actions/runs/977031034
* It generates those artifacts: https://github.com/jneira/haskell-language-server/releases/tag/1.2.0-ghcup-sha256

**Comment by jneira** [comment]
@maerwald the sha256 sums looks a little bit hairy with those long paths, but he hashes are correct:

```
SHA256 (haskell-language-server-Linux-1.2.0-ghcup-sha256.tar.gz/haskell-language-server.tar.gz) = 831dec6af19e7334fb3519c55a5e5a2f36fca78335a18cb7175528d9f0a539e3
SHA256 (haskell-language-server-Linux-8.10.2.gz/haskell-language-server-8.10.2.gz) = 7cf9557dce3fcfc133ec4afe9ca6d53008b28d1942815e7be8b8eae2d6a4357d
SHA256 (haskell-language-server-Linux-8.10.3.gz/haskell-language-server-8.10.3.gz) = f2de97af53aa86c4e46d0be8978ec3e9ab1c46dbeaafd57814f00d1cd74efee3
SHA256 (haskell-language-server-Linux-8.10.4.gz/haskell-language-server-8.10.4.gz) = fc601f9fbf4f34ac71f1d943bc2bbb12c4caf0903df1b03fe20f0a0b7da5c95c
SHA256 (haskell-language-server-Linux-8.10.5.gz/haskell-language-server-8.10.5.gz) = 0dd6661da66cb3384cf96bcebabb13f3d3d019288102a62c6a6054577a9c3014
SHA256 (haskell-language-server-Linux-8.6.4.gz/haskell-language-server-8.6.4.gz) = 863df83a8c0ddb6d61fcfc9bac663c1cc9354c15bc2c15eaf2c1ad0c6a7ed400
SHA256 (haskell-language-server-Linux-8.6.5.gz/haskell-language-server-8.6.5.gz) = cb38506a9f7578c89c4f50165038df87f2512f61ff766b7a74034a5beb69f1c7
SHA256 (haskell-language-server-Linux-8.8.3.gz/haskell-language-server-8.8.3.gz) = 1834643afd39335597658b99e2ad11281d1b6d7bccb6e8dbd87af0db123f4c92
SHA256 (haskell-language-server-Linux-8.8.4.gz/haskell-language-server-8.8.4.gz) = fdfe18ef218e49bb30f2888fa0fe75b84bf943e3e664a225d54c76dbee863247
SHA256 (haskell-language-server-Linux-9.0.1.gz/haskell-language-server-9.0.1.gz) = c5bb58c32ad8a9d87a48cc9843eaba9eef0ce3d3657a6ada39e5de89175304a0
SHA256 (haskell-language-server-Windows-1.2.0-ghcup-sha256.tar.gz/haskell-language-server.tar.gz) = 4a6386d1722ca89038b0d4da13be20e050b4834af77e34c8df3335918146944b
SHA256 (haskell-language-server-Windows-8.10.2.2.exe.zip/haskell-language-server-8.10.2.zip) = 8e2efb192aa6bbdc901e15a1b86371751a11b0dcd3a290a40b913c7664daea88
SHA256 (haskell-language-server-Windows-8.10.3.exe.zip/haskell-language-server-8.10.3.zip) = 75520b2b9bd148511473aa5712c40a26e855f3ed190a76bd381b919068322fb7
SHA256 (haskell-language-server-Windows-8.10.4.exe.zip/haskell-language-server-8.10.4.zip) = 5f2a6f150932d65b1f1933a62391e029a40a69c8717428d11c83155fb4e1e1a6
SHA256 (haskell-language-server-Windows-8.10.5.exe.zip/haskell-language-server-8.10.5.zip) = 6ed7d668b8e282a9cb1c4ecf27c19d35c3d3dbac3cc060cf07e3690ed0602f59
SHA256 (haskell-language-server-Windows-8.6.4.exe.zip/haskell-language-server-8.6.4.zip) = 02db82d2e93f0a42a3244318ea7256dbc09c026aa21f3f52c692ac050fe0e130
SHA256 (haskell-language-server-Windows-8.6.5.exe.zip/haskell-language-server-8.6.5.zip) = 97546e667ee146371f2e72539524cbde4d44790801cd28f1ce368a868743082a
SHA256 (haskell-language-server-Windows-9.0.1.exe.zip/haskell-language-server-9.0.1.zip) = 5fa773adebe5d3a1f21df40ee197f47d52e74692b6f02cd9dad1c83889c48988
SHA256 (haskell-language-server-macOS-1.2.0-ghcup-sha256.tar.gz/haskell-language-server.tar.gz) = d5f6d72b6c8eb047c90b60dc2fb2ce7eccd9f08c51603d812751c5ff920732df
SHA256 (haskell-language-server-macOS-8.10.2.gz/haskell-language-server-8.10.2.gz) = 939569b96a178f64dda2af52ed97a9402fd0abb4b389a8e1ded35f98e803470d
SHA256 (haskell-language-server-macOS-8.10.3.gz/haskell-language-server-8.10.3.gz) = 4d2b4fb06420d0afa152d098826f33f6884b9926146e599560fac2a8a30d01c4
SHA256 (haskell-language-server-macOS-8.10.4.gz/haskell-language-server-8.10.4.gz) = 98ccc1ecb253e04fe6e1173d0f1aad1c4c3c8dc1bdcf074c74b52a22b245d554
SHA256 (haskell-language-server-macOS-8.10.5.gz/haskell-language-server-8.10.5.gz) = 70a32b36626d51b15de1af77dc410b3cdcc4f328128e36ebe5c8fcd76f85dd4b
SHA256 (haskell-language-server-macOS-8.6.4.gz/haskell-language-server-8.6.4.gz) = 26a25411961173bd8d699ebfed49aa4eaa5e6be53b91dc9446e403128d201e1e
SHA256 (haskell-language-server-macOS-8.6.5.gz/haskell-language-server-8.6.5.gz) = 1a3c50c0faab5a151f08c4056b75b3929bc069e922e750830267e8d475e8cb94
SHA256 (haskell-language-server-macOS-8.8.3.gz/haskell-language-server-8.8.3.gz) = 53e190a675ee291f8513568053c4268c09f319f4f2c3aa550d2b864090ffb930
SHA256 (haskell-language-server-macOS-8.8.4.gz/haskell-language-server-8.8.4.gz) = c79aa15fd8c1d946c8c628a0cd0fd801a242e3e775db0ab21f1fdffc77125a33
SHA256 (haskell-language-server-macOS-9.0.1.gz/haskell-language-server-9.0.1.gz) = ce061bc9800f3c9da0c0e16a167c1ed42c19962ece664df0b6c46468d3fc9cf4
SHA256 (haskell-language-server-wrapper-Linux.gz/haskell-language-server-wrapper.gz) = 677e822ef0adbbf60f612167cff40cf7fbfe4bc3468f1e98a88d40f4b9cd75c6
SHA256 (haskell-language-server-wrapper-Windows.exe.zip/haskell-language-server-wrapper.zip) = 9c5eb6d84c434fe0207e1485179a99a33425333541b45cd51b04aa10727db308
SHA256 (haskell-language-server-wrapper-macOS.gz/haskell-language-server-wrapper.gz) = 3a1aa7d2ccb70125bea5ba6b74aa087214d38316ea4c6e657ffbb26b2dbc2fef
```

**Comment by jneira** [comment]
The sums file looks nicer now:

```
SHA256 (haskell-language-server-Linux-1.2.0-ghcup-sha256.tar.gz) = d21002c8bfa55df11aeffc2fbf35d3e8e973da5bc098646163d9bcd8308825eb
SHA256 (haskell-language-server-Linux-8.10.2.gz) = be714792cec7239eb9c5152e56846279d9c4c2ce89e3d8ae8c538008234f62a1
SHA256 (haskell-language-server-Linux-8.10.3.gz) = 182135631a1a37f024c61a94c8c1147a3c1fdfd6a2acfe58cf1f84d19bce0381
SHA256 (haskell-language-server-Linux-8.10.4.gz) = e979baf02884c0678f62240562470fbfd971967a664260219978cbc1fc667a3a
SHA256 (haskell-language-server-Linux-8.10.5.gz) = 2ffac811042a8cbaef3da172e0dc2bc31a242d99ce2d16aa5fe91d1bd81a2008
SHA256 (haskell-language-server-Linux-8.6.4.gz) = 508588b25d57e661dd9ce925d7cee7ffb8d902e7b46a39638323eeea963a213d
SHA256 (haskell-language-server-Linux-8.6.5.gz) = 358e0561ed3d3c5c91fb094b43bb246984562fa796385751a62a5cd2fd3cd849
SHA256 (haskell-language-server-Linux-8.8.3.gz) = 4f13e34803ba52c438cb93b306c2569d3dcfd8ab08777f928011be5757efad8d
SHA256 (haskell-language-server-Linux-8.8.4.gz) = dd736587d2ac67abe1fe670e0d27c577e425ff7a9efcce82493c740e9d57eedb
SHA256 (haskell-language-server-Linux-9.0.1.gz) = 817745279c305143fa0855e2bcbee591784ff317a57c15c01e1199fe211657d5
SHA256 (haskell-language-server-Windows-1.2.0-ghcup-sha256.tar.gz) = 1d1851e9976fb3706ff67786a18f4f34854aa1d142b0c108dabd022c725e16e8
SHA256 (haskell-language-server-Windows-8.10.2.2.exe.zip) = e043b3b20b94ea37d9197393886c8f5bfbdd3e0bd01549fe630549f38208e1d0
SHA256 (haskell-language-server-Windows-8.10.3.exe.zip) = 1eaa8638580bed8e0ba8c4b6658d69bba52d3d759010531b6e25a705859449fb
SHA256 (haskell-language-server-Windows-8.10.4.exe.zip) = ddf9d461c8cccfc74cca25a3fbf6ff63c79e3c1a1f397620582fdeda7d196674
SHA256 (haskell-language-server-Windows-8.10.5.exe.zip) = b1e9e2b6fc669dc6745dbbdaba052a71f63f72b85edec418ad152a7bbd6e7ab3
SHA256 (haskell-language-server-Windows-8.6.4.exe.zip) = 4b2f7900354eab907e617de3b8e842ad9fce2d287a5eb050765e9b80ab269f00
SHA256 (haskell-language-server-Windows-8.6.5.exe.zip) = 7bb9b13a51476537ef8a891a756e1ef32382410fcc2d43448131ddbf1c9f15fa
SHA256 (haskell-language-server-Windows-9.0.1.exe.zip) = 5f003ed005fdf8449b61b17406d80415b2507ee9f0aa74fc6ffb7b89d3b8278a
SHA256 (haskell-language-server-macOS-1.2.0-ghcup-sha256.tar.gz) = f4fe89d573cdb8f97fae1bfa94797e78503cfd33f326b93c4f7f7a2c241f40e1
SHA256 (haskell-language-server-macOS-8.10.2.gz) = 2419709f1c9171de4a01e35c39f76a92abb8e5c35749a1eb2fb2b31f001e913b
SHA256 (haskell-language-server-macOS-8.10.3.gz) = ecfd7f009c2d7b64fbbfcaaf7572e3502b875e74ba4ff7d278b094b9705b675b
SHA256 (haskell-language-server-macOS-8.10.4.gz) = 9af366d820c445a01369084b1dd47bc22e6f401236b3a4b2efe15e46ccf0dbb9
SHA256 (haskell-language-server-macOS-8.10.5.gz) = a397f36d72177c82a36e2f8c7d23340478432c3ddc3578adbbf0abe8031d181c
SHA256 (haskell-language-server-macOS-8.6.4.gz) = 58bac4d6ae7c70ccd9542f188efbcc7c3711b16536c61d59e55ffc3f1660c4fa
SHA256 (haskell-language-server-macOS-8.6.5.gz) = 19e39a17990fb004ac95afc2948c3a7260c5b8eda8c0ff1e5b9b8fe7aaae298d
SHA256 (haskell-language-server-macOS-8.8.3.gz) = a1a2046fc9ba25709994677f6cf6d768432ebc63797c8a7df162af4553a4a486
SHA256 (haskell-language-server-macOS-8.8.4.gz) = 5a0ba5cd7e4b1caad92e555e61fe0f3df287a83c1396ab575a534f13eeb099c4
SHA256 (haskell-language-server-macOS-9.0.1.gz) = 0a04465653f4ba202158685b8cccffcfbc98b2d089ceabbb52bb6cc86a09a91e
SHA256 (haskell-language-server-wrapper-Linux.gz) = bad5fcbf5ab21f1587133ce26b65e85a59464a2076899d96863d4492d2e3b5a6
SHA256 (haskell-language-server-wrapper-Windows.exe.zip) = 581f5a72f89b9bca94d4f6de1f9cb3ca6255a42ad58543fb46fbf8033b3953b4
SHA256 (haskell-language-server-wrapper-macOS.gz) = b4d00fbc4b58f7990c0e72fe61e44ccb2aafbb2651cc4e90a039337b7df0093b
```

**Review by wz1000 — APPROVED** [review]

**Review by berberman — APPROVED** [review]
> This repository is currently unmaintained by a team of developers at GitHub. The repository is here and you can use it as an example, or in Actions. However please be aware that we are not going to be updating issues or pull requests on this repository. (https://github.com/actions/upload-release-asset)

It looks like `actions/upload-release-asset` is obsolete, and we should use [`softprops/action-gh-release`](https://github.com/softprops/action-gh-release) to upload the assets.

**Pull request merged**
