### PR TITLE
Boot files

### LINKED ISSUE #2362: hls does not work in the ghcup-hs codebase
* As reported by @hasufell here: https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/286hls does not work in `lib/GHCup.hs`(f.e.) from our beloved cousin project
* I tried in windows and i got the ide features in some utility modules, i have to check it which one
* We should recollect the usual logs as described https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html#troubleshooting-the-server

### PR DESCRIPTION
**Pull request by pepeiborra**
Fixes the regression in #2365 addressing 2 problems identified by @mpickering and @wz1000 
Tested with the repros described in that ticket (using the ghc codebase).

Does not_fix #2362 but that appears to be a slightly different problem (and verified it's not a regression).

I don't know if I'll have time to add a new test before next weekend

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2377"></a>

### CODE REVIEW

**Review by wz1000 — COMMENTED** [review]
Seems fine to me, I will try to come up with a test case.

**Comment by guibou** [comment]
I tested that this also closes #2385.

**Comment by jneira** [comment]
maybe a regression test based on #2385 would be great, sad it is not reproducible with the simple case described in the issue

**Comment by guibou** [comment]
@jneira I discovered at the end of writting the issue that boot file may be involved. So my repro without boot file was not succesful.

I was at work, so a bit busy by "we need to fix HLS right now", but I'll try to write a repro when I'll get a bit of time.

**Comment by pepeiborra** [comment]
I basically gave up on constructing a test case for this, so any ideas will be appreciated @guibou @wz1000 
In the meantime we should land this and start thinking about an HLS 1.5.1 release @jneira

**Comment by mpickering** [comment]
Perhaps the boot5688 test in the GHC tree triggers this case?

**Comment by pepeiborra** [comment]
> Perhaps the boot5688 test in the GHC tree triggers this case?

That worked, it fails without this patch and succeeds with it. Test added now, thanks Matt.

**Comment by guibou** [comment]
Damned, I did not saw @mpickering answer before starting to work on my repro.

Here is my repro: https://github.com/guibou/hls_repro_2385, in case it may help.

In any case, thank you for providing a solution for this problem.

**Review by jneira — APPROVED** [review]
Perfect, regression test included, thanks @pepeiborra for the fix and everyone for the help

Will cut a 5.1 release asap after merge this

**Comment by jneira** [comment]
> Damned, I did not saw @mpickering answer before starting to work on my repro.
> 
> Here is my repro: https://github.com/guibou/hls_repro_2385, in case it may help.
> 
> In any case, thank you for providing a solution for this problem.

Thanks for working in the repro anyways 👍

**Comment by jneira** [comment]
there are almost as flaky tests in ubuntu than windows lately :worried:

**Pull request merged**
