### PR TITLE
[skip ci] Remove myself from codeowners

### PR DESCRIPTION
**Pull request by jneira**
Cause i am getting lot of notifications i dont have time to attend and i dont expect that will change in the foresee future
Thanks in advance!

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3230"></a>

### CODE REVIEW

**Review by fendor — APPROVED** [review]
Hope to see you around! :heart:

**Comment by michaelpj** [comment]
:'(

**Comment by pepeiborra** [comment]
Thank you for all your work!

**Comment by jneira** [comment]
consequently I will also remove myself as repo admin and stay as regular writer

**Pull request merged**
