### PR TITLE
[WIP] "Replace with type synonym" action

### PR DESCRIPTION
**Pull request by mpardalos**
Adds an action to replace instances of the RHS of type synonyms in a type with their equivalent type synonym.

Also adds some tests for the retrie plugin.

Addresses #506

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/1515"></a>

### CODE REVIEW

**Comment by pepeiborra** [comment]
Can you attach some description and/or screenshots showing how this feature works? 

The retrie plugin already offers code actions to fold and unfold type synonyms, isn't that what you want?

image

**Comment by mpardalos** [comment]
I don't yet have the feature working, I just opened this PR to declare I'm working on the issue, once I have some screenshots I will attach them here. I can close the PR and reopen once the feature is actually working.

This PR is closely related to that feature but it's about adding that hint **to the use site**, in order to fold one instance of a type synonym. It should be useful for synonyms that come from libraries.

**Comment by mpardalos** [comment]
Part of the work of the feature is done. You can apply type synonyms at single usage sites.

usage

What remains is to *only* suggest relevant type synonyms. We are currently suggesting any type synonym in scope, even though the relevant action does nothing.

**Comment by mpardalos** [comment]
The plugin will now only suggest relevant type synonyms:

example2

I have not been able to include suggestions for imported type synonyms, and those would probably be the most useful.

**Comment by michaelpj** [comment]
Closing as dead.

**Pull request closed without merging**
