### PR TITLE
FindImports: ThisPkg means some home unit, not "this" unit

### PR DESCRIPTION
**Pull request by wz1000**
This bug prevents package imports from working within a multi unit session.

### CODE REVIEW

**Comment by michaelpj** [comment]
What happened before? A crash?

**Comment by wz1000** [comment]
It just wasn't able to resolve those imports, because it tried to look from them in the current unit instead of *some* home unit.

**Review by soulomoon — APPROVED** [review]
LGTM

**Comment by michaelpj** [comment]
I guess I mean did the test fail before this? but I assume so

**Pull request merged**
