### PR TITLE
Enable hls-tactics-plugin tests in CI

### PR DESCRIPTION
**Pull request by isovector**
I noticed in #1472 that my tests were red but CI was fine. Turns out the tests aren't running in CI!

### CODE REVIEW

**Review by jneira — COMMENTED** [review]
We should update the mergify config file (and the CI check in github itself)

**Comment by isovector** [comment]
@jneira do you know what changes need to be made? I'm out of my depth on this stuff.

**Comment by Ailrun** [comment]
Actually in this case you don't need to update `mergify.yml`, as your change is a part of "test" workflow.

**Review by Ailrun — APPROVED** [review]
Thanks!

**Comment by isovector** [comment]
Yay! tests are now failing in CI. Should be fixed when #1472 lands.

**Pull request merged**
