### PR TITLE
Stan: Avoid terminal colors in messages

### PR DESCRIPTION
**Pull request by andys8**
Solves #3089

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3090"></a>

### CODE REVIEW

**Comment by michaelpj** [comment]
Build fails with 8.10.7, I think because that forces an older version of `stan` that doesn't expose `unCategory`?

**Review by uhbif19 — APPROVED** [review]

**Comment by uhbif19** [comment]
@andys8 Stan does not work with GHC >8.10 (https://github.com/kowainik/stan/issues/423).

I does not understand how it seems to work with 9.2 in your case.

**Comment by andys8** [comment]
Maybe it's just skipped in that case?

https://github.com/andys8/haskell-language-server/blob/f274919bccc02d139295dedfc5f2e4ec8db313fd/plugins/hls-stan-plugin/hls-stan-plugin.cabal#L26-L29

**Comment by michaelpj** [comment]
Yeah, I think that means it was just unconditionally broken. There is a small mystery in that your original report said you were using GHC 9.2 which shouldn't have been possible!

**Comment by andys8** [comment]
> There is a small mystery in that your original report said you were using GHC 9.2 which shouldn't have been possible!

Ah, I can help solve the mystery. The system ghc version is indeed 9.2, and I think also hls is build with it.

The project where the screenshot is from is a stack project using 8.10.7 though.

Still the output of `--probe-tools` in that directory looks like this. It also says "found on $PATH".

```
haskell-language-server-wrapper --probe-tools
haskell-language-server version: 1.7.0.0 (GHC: 9.2.4) (PATH: /home/andreas/.ghcup/bin/haskell-language-server-wrapper-1.7.0.1)
Tool versions found on the $PATH
cabal:          3.8.1.0
stack:          2.7.5
ghc:            9.2.4
```

**Comment by michaelpj** [comment]
Hmm, interesting. So for stack users this is potentially misleading, we really want to report the GHC that stack would use for the project or something.

**Comment by andys8** [comment]
Is the failing benchmark check related to this pull request?

image

And as a followup to the "ghc mystery" we could add the output of `stack ghc -- --numeric-version` to the output of `--probe-tools`, see https://github.com/haskell/haskell-language-server/pull/3093

**Comment by pepeiborra** [comment]
The bench failure is unrelated - our CI fails to upload the cache artifacts! I don't know why this happens, retried and hopefully it will go through but long term it would be great if someone could figure it out

**Pull request merged**
