### PR TITLE
Bump plugins versions

### PR DESCRIPTION
**Pull request by pepeiborra**
The plugins were all updated to lsp-1.0 in #1284 and need a minor version bump in order to be upload able to Hackage. 

I am also going to upload all the plugins I have Hackage maintainer access (class, imports, and retrie). This is in order to make them usable with ghcide 0.7.5.0, which was released earlier today. 

Ideally we would have a CI job that would detect Cabal version updates and automatically upload to Hackage.

### CODE REVIEW

**Comment by jneira** [comment]
> Ideally we would have a CI job that would detect Cabal version updates and automatically upload to Hackage.

As proposed in #1310

**Comment by jneira** [comment]
Maybe hls-plugin-api should hide lsp to plugins (and ghcide?), with reexports or something, to cut at least in some cases the upgrade in cascade

**Review by jneira — APPROVED** [review]
lgtm, i've added you to the maintainer group of hls-hlint-plugin, but i can do the upload if you are busy

**Comment by pepeiborra** [comment]
Updated also the minBounds in haskell-language-server.cabal. I am tempted to make these hard bounds (`==`) instead of minBounds to avoid `cabal install` failures as seen in #1395

**Comment by jneira** [comment]
please take a look to #1310 before merging

**Comment by pepeiborra** [comment]
@jneira What do you mean???

**Comment by jneira** [comment]
in that issue we were debating about bump up all project packages to 1.0 , in the face of a next hackage release
as this pr was mainly bumping out package versions we could did that change here

**Pull request merged**
