### PR TITLE
Enable highlight unittests

### PR DESCRIPTION
**Pull request by peterwicksstringfield**
Well, the one highlight unit test.

This PR has a commit in common with #657 . This shared commit moves some utility functions. Leave comments wherever is convenient. Merging both PRs will not produce a merge conflict, nor will it duplicate the commit.

### CODE REVIEW

**Comment by jneira** [comment]
stack is being more strict than cabal:
```
Progress 8/10: haskell-language-server haskell-language-server    > /root/build/test/utils/Test/Hls/Util.hs:320:11: error: [-Wname-shadowing, -Werror=name-shadowing]
Progress 8/10: haskell-language-server haskell-language-server    >     This binding for ‘pred’ shadows the existing binding
Progress 8/10: haskell-language-server haskell-language-server    >       imported from ‘Prelude’ at test/utils/Test/Hls/Util.hs:2:8-20
Progress 8/10: haskell-language-server haskell-language-server    >       (and originally defined in ‘GHC.Enum’)
Progress 8/10: haskell-language-server haskell-language-server    >     |
Progress 8/10: haskell-language-server haskell-language-server    > 320 |     where pred (CACodeAction ca) = all (`T.isInfixOf` (ca ^. L.title)) s
Progress 8/10: haskell-language-server haskell-language-server    >     |           ^^^^
Progress 8/10: haskell-language-server haskell-language-server    > 
```

**Comment by jneira** [comment]
I am afraid that there is a small conflict

**Comment by peterwicksstringfield** [comment]
Should be fixed whenever CI finishes.

**Review by jneira — APPROVED** [review]
Thanks once again 😃

**Comment by peterwicksstringfield** [comment]
:). Thank you for reviewing changes and helping me merge things. HLS is a cool project and I am glad to be able to contribute to it.

**Pull request merged**
